### ISSUE TITLE
cwl-runner: setting the PATH .

### ISSUE THREAD

**Issue by lindenb** [common-workflow-language/common-workflow-language#103]
I wrapped a tool in a bash script `mytool.bash` . If I just set the PATH to add this tool, it is not found by cwl-runner 

```
$ export PATH=${PWD}:${PATH}

$ ls -la mytool.bash 
-rwxrwxr-x 1 lindenb lindenb 1079 Aug  3 16:08 mytoolbash

$ which graph2cwl.bash 
/home/lindenb/tmp/mytool.bash

$ cwl-runner  test.cwl
cwl-runner 1.0.20150728161219
Must provide input in the form of a json file or command line parameters.
[job 166667916] exec mytool.bash 1
'mytool' not found
[job 166667916] completed permanentFail
```

setting a full path in the tool section is OK. However, gcc is called in mytool.bash, and then I get: 

```
gcc: error trying to exec 'cc1': execvp: No such file or directory
Exception while running job
```

**Comment by tetron** [comment]
There's two different things going on here.

1) I don't know why `mytool.bash` is being executed as `mytool`.  Can you post your CWL file that demonstrates the bug?

2) The 2nd behavior is expected according to the spec:
> When executing the tool, the child process must not inherit environment variables from the parent process. The tool must execute in a new, empty environment, containing only environment variables defined by EnvVarRequirement, the default environment of the Docker container specified in DockerRequirement (if applicable), and TMPDIR.

The rationale is that you want to declare the runtime environment as explicitly as possible.  So the best approach would be to add a job input parameter with the desired value for $CC and set it with `EnvVarRequirement`:

```yaml
inputs:
  - id: "#cc"
    type: File
    label: Path to the C compiler to use.
requirements:
  - class: EnvVarRequirement
    envDef:
      - envName: CC
        envValue:
          engine: "cwl:JsonPointer"
          script: job/cc/path
```

In your job:
```json
{
  "cc": {
    "class": "File",
    "path": "/usr/bin/gcc"
   }
}
```

Of course, if setting environment variables for each program is not practical, you can also set $PATH using  `EnvVarRequirement` as well.
