### ISSUE TITLE
proposal: scoped identifiers

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#105]
One user-unfriendly aspect of CWL is that identifiers are document
scoped, and require the "#" sigil everywhere.  This puts a burden on
CWL authors to avoid name conflicts even between unrelated parts of a
workflow, and it is inconsistent with the related usage in HTML/XML
where a section is identifier as `<p id="foo">` and the "#" sigil is
only used when making a reference:
`<a href="#foo">`.

There is a reason for this; CWL is based on JSON-LD and uses RFC 3986
URI relative reference resolution rules (which treat document
fragments as opaque) and does not have a concept of implicit scope
(you can have explicit scope by declaring nested JSON-LD contexts.)

However, CWL is not actually JSON-LD; CWL documents are YAML (not
plain JSON) and support "import" and "include" preprocessing
directives.  We can take advantage of this preprocessing step to
support scoped identifiers and make CWL documents just a little bit
easier to read and write.

Here are the proposed rules:
 - An object with an "id" sets the base URL used for resolution of
nested objects
 - A relative id that does not not start with "#" is joined with the
base URL fragment
   - If there is no fragment in the base URL, set the fragment portion
of the base URL
   - If there is a fragment in the base URL, join the base URL
fragment with the relative id, separated "/"
 - A relative id that does start with "#" remains document scoped and
replaces the fragment of the base URL.
 - Cross references remain document scoped and must start with "#"

This turns out to be a fairly small change to the existing reference
resolution code, I have pushed this to the "scoped-ids" branch on github.

To make this concrete, here is an example workflow with scoped
identifiers.  Note far fewer instances of "#" and much more uniform
naming of nested identifiers.

```yaml
id: main
class: Workflow
inputs:
  - id: infile
    type: File
  - id: term
    type: string
outputs:
  - id: outfile
    type: File
    source: "#main/search/result"

steps:
  - id: index
    run: "#index"
    inputs:
      - { id: file, source: "#main/infile" }
    outputs:
      - id: result

  - id: search
    run: "#search"
    inputs:
      - { id: file, source: "#main/index/result" }
      - { id: term, source: "#main/term" }
    outputs:
      - id: result
```

The above workflow, after preprocessing to resolve the scoped identifiers into
their actual identifiers.

```yaml
id: "#main"
class: Workflow
inputs:
  - id: "#main/infile"
    type: File
  - id: "#main/term"
    type: string
outputs:
  - id: "#main/outfile"
    type: File
    source: "#main/search/result"

steps:
  - id: "#main/index"
    run: "#index"
    inputs:
      - { id: "#main/index/file", source: "#main/infile" }
    outputs:
      - id: "#main/index/result"

  - id: "#main/search"
    run: "#search"
    inputs:
      - { id: "#main/search/file", source: "#main/index/result" }
      - { id: "#main/search/term", source: "#main/term" }
    outputs:
      - id: "#main/search/result"
```

For reference, here is the draft-2 workflow the above workflow is based on.

```yaml
id: "#main"
class: Workflow
inputs:
  - id: "#infile"
    type: File
  - id: "#term"
    type: string
outputs:
  - id: "#outfile"
    type: File
    source: "#search.search_result"

steps:
  - run: {import: "#index"}
    inputs:
      - { id: "#index.index_file", source: "#infile" }
    outputs:
      - id: "#index.index_result"

  - run: {import: "#search"}
    inputs:
      - { id: "#search.search_file", source: "#index.index_result" }
      - { id: "#search.search_term", source: "#term" }
    outputs:
      - id: "#search.search_result"
```
