### ISSUE TITLE
Unable to validate workflow with CommandLineBinding

### ISSUE THREAD

**Issue by slnovak** [common-workflow-language/common-workflow-language#116]
If you take a look at the [bwa-mem-tool.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/0dd5ecd67ad1b7ebb1ef758e785b3471ce3d6ec7/conformance/draft-2/bwa-mem-tool.cwl) workflow definition in conformance tests, you'll notice the following:

1. In the `inputs` section of the workflow document, there's an `inputBinding` property that describes `position` ([ref](https://github.com/common-workflow-language/common-workflow-language/blob/0dd5ecd67ad1b7ebb1ef758e785b3471ce3d6ec7/conformance/draft-2/bwa-mem-tool.cwl#L13-L15)).

2. From what I can see, `Binding` does not have `position` as a field. ([ref](https://github.com/common-workflow-language/common-workflow-language/blob/0dd5ecd67ad1b7ebb1ef758e785b3471ce3d6ec7/schemas/draft-2/cwl-avro.yml#L847-L876))

3. However, `CommandLineBinding` does have `position` as a field. ([ref](https://github.com/common-workflow-language/common-workflow-language/blob/0dd5ecd67ad1b7ebb1ef758e785b3471ce3d6ec7/schemas/draft-2/cwl-avro.yml#L1104-L1106))

How is this passing conformance tests?

It seems like that the `InputParameter` record should include `CommandLineBinding` as a type for the `inputBinding` field. For example:

```yaml
- name: InputParameter
  type: record
  extends: Parameter
  docAfter: Parameter
  specialize: {Schema: InputSchema}
  fields:
    - name: id
      type: string
      jsonldPredicate: "@id"
      doc: "The unique identifier for this parameter object."
    - name: "inputBinding"
      type: [ "null", "Binding", "CommandLineBinding" ]
```

Alternatively, allow the `Process` record to have `CommandInputParameter` types in the `inputs` [field](https://github.com/common-workflow-language/common-workflow-language/blob/0dd5ecd67ad1b7ebb1ef758e785b3471ce3d6ec7/schemas/draft-2/cwl-avro.yml#L1014-L1017).
