### ISSUE TITLE
cwl-runner draft2 record type

### ISSUE THREAD

**Issue by portah** [common-workflow-language/common-workflow-language#121]
I have this CommandLineTool file https://github.com/SciDAP/workflows/blob/master/tools/bedtools-genomecov.cwl, I just have added next code to a working CWL file:
```
  - class: SchemaDefRequirement                                                                                                                                                                         
    types:                                                                                                                                                                                              
      - name: "#depts"                                                                                                                                                                                  
        type: "record"                                                                                                                                                                                  
        fields:                                                                                                                                                                                         
          - name: "#dept"                                                                                                                                                                               
            type:                                                                                                                                                                                       
              type: enum                                                                                                                                                                                
              name: "JustDepts"                                                                                                                                                                         
              symbols: ["-bg","-bga","-d"]      
```
Somewhere in inputs I have:
```
  - id: "#dept"                                                                                                                                                                                         
    type: ["null","#depts"]     
```
Now I can't provide arguments to cwl-runner command line and usage shows standard cwl-runner usage

**Comment by ntijanic** [comment]
Hi, Portah.

Can you try the same workflow without leading "#" in names of types and fields? It's only used for port identifiers and these are Avro structures. So:

```
  - class: SchemaDefRequirement                                                                                                                                                                         
    types:                                                                                                                                                                                              
      - name: "depts"                                                                                                                                                                                  
        type: "record"                                                                                                                                                                                  
        fields:                                                                                                                                                                                         
          - name: "dept"  # Also update "#scale" to "scale"                                                                                                                                                                             
            type:                                                                                                                                                                                       
              type: enum                                                                                                                                                                                
              name: "JustDepts"                                                                                                                                                                         
              symbols: ["-bg","-bga","-d"]   
```

and 

```
  - id: "#dept"                                                                                                                                                                                         
    type: ["null","depts"]   
```
