### ISSUE TITLE
Proposal: define types at top file level

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#124]
Allow users to define types at top level of files.  Parameters can reference these in the `type` field.

Example:

```
- id: FooType
  type: string
  inputBinding:
    prefix: "-o"

- id: BarTool
  type: CommandLineTool
  inputs:
    - id: output
      type: "#FooType"
```

This obsoletes SchemaDefRequirement.
