### ISSUE TITLE
Outputs glob and stdout

### ISSUE THREAD

**Issue by portah** [common-workflow-language/common-workflow-language#130]
I do a commandLineTool for linux sort command and would like to have output file the same as input+suffix
```
outputs:
  - id: "#sorted"
    type: File
    description: "The sorted file"
    outputBinding:
      glob:
        engine: node-engine.cwl
        script: $job.input.path + '.sorted'

stdout:
  engine: node-engine.cwl
  script: $job.input.path + '.sorted'
```
The error is:
```
root@vagrant-ubuntu-vivid-64:/workflows/tools# ./linux-sort.cwl ./linux-sort-job.json 
/usr/local/bin/cwl-runner 1.0.20150918080732
[job 140486033891920] /workflows/tools$ docker run -i --volume=/workflows/tools/test-files/rna.SRR948778.bedGraph:/tmp/job49442782_test-files/rna.SRR948778.bedGraph:ro --volume=/workflows/tools:/tmp/job_output:rw --volume=/tmp/tmpMJqZqf:/tmp/job_tmp:rw --workdir=/tmp/job_output --user=0 --rm --env=TMPDIR=/tmp/job_tmp --env=PATH=/usr/local/bin/:/usr/bin:/bin ubuntu:15.04 sort -k1,1 -k2,2n /tmp/job49442782_test-files/rna.SRR948778.bedGraph > /workflows/tools/./test-files/rna.SRR948778.bedGraph.sorted
Error while running job: No matches for output file with glob: '/tmp/job49442782_test-files/rna.SRR948778.bedGraph.sorted'
[job 140486033891920] completed permanentFail
Final process status is permanentFail
{}root@vagrant-ubuntu-vivid-64:/workflows/tools# 
```
