### ISSUE TITLE
Output file parameters can appear on command line

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#137]
Propose an input type that represents a filename for a file that doesn't exist yet.

**Comment by tetron** [comment]
Design sketch:

```
class: CommandLineTool
      requirements:
        - import: node-engine.cwl
      inputs:
        - id: "#genome1"
          type: string

        - id: "#genome2"
          type: string

        - id: "outfilename"
          type: OutputFile
          default: "{genome1}To{genome2}.over.chain.gz"
          inputBinding:
            position: 1
            prefix: "-o"
            valueFrom:
              engine: node-engine.cwl
              script: |
                {
                  var temp=$self.replace("{genome1}",$job['genome1']).replace("{genome2}",$job['genome2']);
                  return temp;
                }

      outputs:
        - id: "#overchain"
          type: File
          outputBinding:
            outputFile: "#outfilename"
```

**Comment by tetron** [comment]
Design sketch:

```
class: CommandLineTool
      requirements:
        - import: node-engine.cwl
      inputs:
        - id: "#genome1"
          type: string

        - id: "#genome2"
          type: string

      outputs:
        - id: "#overchain"
          type: File
          inputBinding:
            position: 1
            prefix: "-o"
            valueFrom: "$($job.genome1)To$($job.genome2).over.chain.gz"
stdout:
    valueFrom: "#overchain"
```
