### ISSUE TITLE
Proposal: ResourceRequirement

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#141]
```
requirements:
 - class: ResourceRequirement
   coresMin:  1
   coresMax: 4
   ramMin 1024
   ramMax: 4096
   tmpdirMin: 1024
   tmpdirMax: 1024
   outdirMin: 1024
   outdirMax: 1024
```

"min" is the minimum amount of a resource that must be reserved to schedule a job.  If "min" cannot be satisfied, the job should not be run.

"max" is the maximum amount of a resource that the job shall be permitted to use.  If a node has sufficient resources, multiple jobs may be scheduled on a single node provided each job's "max" resource requirements are met.  If a job attempts to exceed its "max" resource allocation, an implementation may deny additional resources, which may result in job failure.

If "min" is specified but "max" is not, then "max" == "min"
If "max" is specified by "min" is not, then "min" == "max".

It is an error if max < min.

If neither "min" nor "max" is specified for a resource, an implementation may provide a default.

cores: reserved number of CPU cores
ram: reserved RAM in megabytes (2**20)
tmpdir: reserved filesystem based storage for the designated temporary directory, in megabytes
outdir: reserved filesystem based storage for the designated output directory, in megabytes
