### ISSUE TITLE
commandLineTool redundant description can brake workflow 

### ISSUE THREAD

**Issue by portah** [common-workflow-language/common-workflow-language#142]
How to reproduce
Workable standalone commandLineTool, pay attention to id: "#split",type null and default: false:
```
class: CommandLineTool
inputs:
  - id: "#input"
    type: File
    inputBinding:
      position: 1

  - id: "#split"
    type: ["null",boolean]
    default: false
    inputBinding:
      position: 4
      prefix: "-split"
```
When it is part of the workflow and inputs has '- {id: "#genomecov.split", default: true }':
```
steps:
  - id: "#genomecov"
    run: {import: ../../tools/bedtools-genomecov.cwl}
    inputs:
      - {id: "#genomecov.input", source: "#input"}
      - {id: "#genomecov.genomeFile", source: "#genomeFile"}
      - {id: "#genomecov.genomecoverageout", default: "genomecov.bed" }
      - {id: "#genomecov.dept", default: '-bg' }
      - {id: "#genomecov.split", default: true }
      - {id: "#genomecov.scale", source: "#scale" }
    outputs:
      - {id: "#genomecov.genomecoverage"}
```

Then running command does not have -split parameter, but if I remove default: false in '#split' everything fine.

```
  - id: "#split"
    type: ["null",boolean]
    inputBinding:
      position: 4
      prefix: "-split"
```

**Comment by ntijanic** [comment]
I can't find it explicitly in the docs, but it seems `WorkflowStepInput.default` should override `InputParameter.default`, so it may be a bug in cwltool.

@tetron What are the semantics of the `default` property on `InputParameter`? Does the default value replace the `null` in the Job object before it reaches expressions? If someone specifies `default` on some input port (step or process), is there a way to pass a `null` as value explicitly (it seems like connected data should override Step.default even if null, but not sure)?

Tools may have their defaults if arguments are not supplied, but we shouldn't pass them explicitly on the command line. So, I assume this is mostly useful for `WorkflowInputParameter.default` but works in generalized way.

Since it's hard to specify a default File input (and keep the WF portable) and other WF input configurations can have their defaults on Steps, do we even need the `default` property on non-step inputs?

**Comment by portah** [comment]
In some situations when I have javascript code that checks some inputs value:
```yaml
outputs:
  - id: "#indices"
    type: ["null",File]
    outputBinding:
      glob: |
        ${
          if (inputs.runMode != "genomeGenerate")
            return [];
          return inputs.genomeDir+"/Genome";
        }
```

The parameter *runMode* is optional it is not required in a job file. Without default value *inputs.runMode* is null so I can check if it's null or not but it will be less readable.

For some tools they have regex in those params so it's good to have them in the CWL.
