### ISSUE TITLE
Proposal: DockerSocketRequirement

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#143]
```
requirements:
  - class: DockerSocketRequirement
    additionalDockerImages:
      # Optional additional Docker images to be pulled.
      - class: DockerRequirement
        ...
```

Require that the command should have access to the Docker socket.  If the command is itself run in Docker, this means the Docker socket must be made available inside the Docker container.  

If this requirement is present, the platform is strongly encouraged to arrange that file paths are consistent inside and outside the container, as paths that exist only inside the container cannot be passed to other containers.

Note there are inherent security problems with providing access to the Docker socket, so use of this feature should be limited to trusted environments running trusted workflows.  This feature is provided  to support existing container schemes that rely on Docker-in-Docker functionality.
