### ISSUE TITLE
'docker' not found error in workflow step after successfully running previous steps in Docker

### ISSUE THREAD

**Issue by vardaofthevalier** [common-workflow-language/common-workflow-language#162]
I'm experiencing a really strange error when attempting to run a series of workflow steps in Docker containers.  For some reason, the first 2 steps (running independently of each other) are able to successfully run in Docker and create the desired outputs.  However, the third step, which depends on the output of the previous two steps, fails with the following message:  'docker' not found

I'll paste in all of my code, which is probably not ideal because it's a lot, but currently the repo in which I'm tracking my changes is private and not ready to be publicized yet.  

Here is the top-level workflow (snapr-pipeline2.cwl):

```
#!/usr/bin/env cwl-runner

class: Workflow

inputs:
  - id: "#fasta_sequence_file"
    type: File
  - id: "#gene_set_file"
    type: File
  - id: "#input_bam_file"
    type: File
  - id: "#single_alignment_output_bam_file"
    type: string
  - id: "#single_alignment_output_bam_prefix"
    type: string
  - id: "#paired_alignment_output_bam_file"
    type: string
  - id: "#paired_alignment_output_bam_prefix"
    type: string

outputs:
  - id: "#build_genome_index_stdout"
    type: File
    source: "#build_genome_index.stdout"

  - id: "#build_transcriptome_index_stdout"
    type: File
    source: "#build_transcriptome_index.stdout"

  - id: "#single_end_alignment_stdout"
    type: File
    source: "#run_single_end_alignment.stdout"

  - id: "#single_end_alignment_output"
    type: File
    source: "#run_single_end_alignment.output"

steps:
  - id: "#build_genome_index"
    run: { import: snapr-index/snapr-index.cwl }
    inputs: 
      - { id: "#build_genome_index.fasta_sequence", source: "#fasta_sequence_file" }

    outputs:
      - { id: "#build_genome_index.genome" }
      - { id: "#build_genome_index.genome_index" }
      - { id: "#build_genome_index.genome_index_hash" }
      - { id: "#build_genome_index.overflow_table" }
      - { id: "#build_genome_index.stdout" }

  - id: "#build_transcriptome_index"
    run: { import: snapr-transcriptome/snapr-transcriptome.cwl }
    inputs:
      - { id: "#build_transcriptome_index.gene_set", source: "#gene_set_file" }
      - { id: "#build_transcriptome_index.fasta_sequence", source: "#fasta_sequence_file" }

    outputs:
      - { id: "#build_transcriptome_index.genome" }
      - { id: "#build_transcriptome_index.genome_index" }
      - { id: "#build_transcriptome_index.genome_index_hash" }
      - { id: "#build_transcriptome_index.overflow_table" }
      - { id: "#build_transcriptome_index.stdout" }

  - id: "#run_single_end_alignment"
    run: { import: snapr-single-alignment/snapr-single-alignment.cwl }
    inputs:
      - { id: "#run_single_end_alignment.genome_index_genome", source: "#build_genome_index.genome" }
      - { id: "#run_single_end_alignment.genome_index_genome_index", source: "#build_genome_index.genome_index" }
      - { id: "#run_single_end_alignment.genome_index_genome_index_hash", source: "#build_genome_index.genome_index_hash" }
      - { id: "#run_single_end_alignment.genome_index_overflow_table", source: "#build_genome_index.overflow_table" }
      - { id: "#run_single_end_alignment.transcriptome_index_genome", source: "#build_transcriptome_index.genome" }
      - { id: "#run_single_end_alignment.transcriptome_index_genome_index", source: "#build_transcriptome_index.genome_index" }
      - { id: "#run_single_end_alignment.transcriptome_index_genome_index_hash", source: "#build_transcriptome_index.genome_index_hash" }
      - { id: "#run_single_end_alignment.transcriptome_index_overflow_table", source: "#build_transcriptome_index.overflow_table" }
      - { id: "#run_single_end_alignment.output_bam_prefix", source: "#single_alignment_output_bam_prefix" }
      - { id: "#run_single_end_alignment.gene_set", source: "#gene_set_file" }
      - { id: "#run_single_end_alignment.input_bam_file", source: "#input_bam_file" }
      - { id: "#run_single_end_alignment.output_bam_file", source: "#single_alignment_output_bam_file" }

    outputs: 
      - { id: "#run_single_end_alignment.output" }
      - { id: "#run_single_end_alignment.stdout" }
```

The JSON file containing the inputs that I'm feeding to the workflow (snapr-pipeline2.json): 

```
{
  "fasta_sequence_file": {
    "class": "File",
    "path": "/cwl-data/workflows/snapr/inputs/sequence.fa"
  },
  "gene_set_file": {
    "class": "File",
    "path": "/cwl-data/workflows/snapr/inputs/annotation.gtf"
  },
  "input_bam_file": {
    "class": "File",
    "path": "/cwl-data/workflows/snapr/inputs/G20466.5637.2.bam"
  },
  "single_alignment_output_bam_file": "G20466.5637.2.single.bam",
  "single_alignment_output_bam_prefix": "G20466.5637.2.single",
  "paired_alignment_output_bam_file": "G20466.5637.2.paired.bam", 
  "paired_alignment_output_bam_prefix": "G20466.5637.2.paired"
}
```

Genome index building step (snapr-index/snapr-index.cwl):

```
#!/usr/bin/env cwl-runner

class: CommandLineTool

requirements:
  - class: DockerRequirement
    dockerPull: isbbheavner/snapr_1.0dev57_v2

inputs:
  - id: "#fasta_sequence"
    type: File
    inputBinding:
      position: 1

  - id: "#genome_index_dir"
    type: string
    default: "genome-index"
    inputBinding: 
      position: 2

outputs:
  - id: "#genome"
    type: File
    outputBinding: 
      glob: genome-index/Genome

  - id: "#genome_index"
    type: File
    outputBinding:
      glob: genome-index/GenomeIndex

  - id: "#genome_index_hash"
    type: File
    outputBinding:
      glob: genome-index/GenomeIndexHash

  - id: "#overflow_table"
    type: File
    outputBinding:
      glob: genome-index/OverflowTable

  - id: "#stdout"
    type: File
    outputBinding:
      glob: snapr-index.out



baseCommand: ["snapr", "index"]
stdout: snapr-index.out
```

Transcriptome index building step (snapr-transcriptome/snapr-transcriptome.cwl):

```
#!/usr/bin/env cwl-runner

class: CommandLineTool

requirements:
  - class: DockerRequirement
    dockerPull: isbbheavner/snapr_1.0dev57_v2

inputs:
  - id: "#gene_set"
    type: File
    inputBinding:
      position: 1

  - id: "#fasta_sequence"
    type: File
    inputBinding:
      position: 2

  - id: "#transcriptome_index_dir"
    type: string
    default: "transcriptome-index"
    inputBinding:
      position: 3


outputs:

  - id: "#genome"
    type: File
    outputBinding: 
      glob: transcriptome-index/Genome

  - id: "#genome_index"
    type: File
    outputBinding:
      glob: transcriptome-index/GenomeIndex

  - id: "#genome_index_hash"
    type: File
    outputBinding:
      glob: transcriptome-index/GenomeIndexHash

  - id: "#overflow_table"
    type: File
    outputBinding:
      glob: transcriptome-index/OverflowTable

  - id: "#stdout"
    type: File
    outputBinding:
      glob: snapr-transcriptome.out


baseCommand: ["snapr", "transcriptome"]
arguments:
  - valueFrom: "-O1000"
    position: 4

stdout: snapr-transcriptome.out
```

Single-end alignment step (snapr-single-alignment/snapr-single-alignment.cwl):

```
#!/usr/bin/env cwl-runner

# SNAPR Single End Alignment Tool

class: CommandLineTool

requirements:
  - class: DockerRequirement
    dockerPull: isbbheavner/snapr_1.0dev57_v2:latest

  - class: CreateFileRequirement
    fileDef:
      - filename: "genome-index/GenomeIndex"
        fileContent:
          engine: cwl:JsonPointer
          script: /job/genome_index_genome_index

      - filename: "genome-index/Genome"
        fileContent:
          engine: cwl:JsonPointer
          script: /job/genome_index_genome

      - filename: "genome-index/GenomeIndexHash"
        fileContent:
          engine: cwl:JsonPointer
          script: /job/genome_index_genome_index_hash

      - filename: "genome-index/OverflowTable"
        fileContent:
          engine: cwl:JsonPointer
          script: /job/genome_index_overflow_table

      - filename: "transcriptome-index/GenomeIndex"
        fileContent:
          engine: cwl:JsonPointer
          script: /job/transcriptome_index_genome_index

      - filename: "genome-index/Genome"
        fileContent:
          engine: cwl:JsonPointer
          script: /job/transcriptome_index_genome

      - filename: "transcriptome-index/GenomeIndexHash"
        fileContent:
          engine: cwl:JsonPointer
          script: /job/transcriptome_index_genome_index_hash

      - filename: "transcriptome-index/OverflowTable"
        fileContent:
          engine: cwl:JsonPointer
          script: /job/transcriptome_index_overflow_table

inputs:
  - id: "genome_index_genome"
    type: File

  - id: "genome_index_genome_index"
    type: File

  - id: "genome_index_genome_index_hash"
    type: File

  - id: "genome_index_overflow_table"
    type: File

  - id: "transcriptome_index_genome"
    type: File

  - id: "transcriptome_index_genome_index"
    type: File

  - id: "transcriptome_index_genome_index_hash"
    type: File

  - id: "transcriptome_index_overflow_table"
    type: File

  - id: "#output_bam_prefix"
    type: string

  - id: "#genome_index_dir"
    type: string
    default: "genome-index"
    inputBinding:
      position: 1

  - id: "#transcriptome_index_dir"
    type: string
    default: "transcriptome-index"
    inputBinding:
      position: 2

  - id: "#gene_set"
    type: File
    inputBinding:
      position: 3

  - id: "#input_bam_file"
    type: File
    inputBinding:
      position: 4

  - id: "#output_bam_file"
    type: string
    inputBinding:
      position: 5
      prefix: "-o"


outputs:
  - id: "#output"
    type: 
      type: array
      items: File
    outputBinding:
      glob: 
        engine: cwl:JsonPointer
        script: /job/output_bam_prefix

  - id: "#stdout"
    type: File
    outputBinding:
      glob: snapr-single-end-alignment.out


baseCommand: ["snapr", "single"]
stdout: snapr-single-end-alignment.out
```

And the output of "sudo cwl-runner --debug snapr-pipeline2.cwl snapr-pipeline2.json":

```
/usr/local/bin/cwl-runner 1.0.20151026181844
[workflow 56151952] initialized from file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-pipeline2.cwl
[workflow 56151952] starting
[workflow 56151952] job step file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-pipeline2.cwl#run_single_end_alignment not ready
[step 40244624] starting job step file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-pipeline2.cwl#build_genome_index of workflow 56151952
[job 40243920] initializing from file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-index/snapr-index.cwl as part of step 40244624
[job 40243920] {
    "fasta_sequence": {
        "path": "file:///cwl-data/workflows/snapr/inputs/sequence.fa", 
        "class": "File"
    }
}
[job 40243920] command line bindings is [
    {
        "position": [
            -1000000, 
            0
        ], 
        "valueFrom": "snapr"
    }, 
    {
        "position": [
            -1000000, 
            1
        ], 
        "valueFrom": "index"
    }, 
    {
        "position": [
            1, 
            "fasta_sequence"
        ], 
        "valueFrom": {
            "path": "/tmp/job435511017_inputs/sequence.fa", 
            "class": "File"
        }
    }, 
    {
        "position": [
            2, 
            "genome_index_dir"
        ], 
        "valueFrom": "genome-index"
    }
]
[job 40243920] path mappings is {
    "file:///cwl-data/workflows/snapr/inputs/sequence.fa": [
        "/cwl-data/workflows/snapr/inputs/sequence.fa", 
        "/tmp/job435511017_inputs/sequence.fa"
    ]
}
[job 40243920] /tmp/tmpgNBWPv$ docker run -i --volume=/cwl-data/workflows/snapr/inputs/sequence.fa:/tmp/job435511017_inputs/sequence.fa:ro --volume=/tmp/tmpgNBWPv:/tmp/job_output:rw --volume=/tmp/tmp3Ls__O:/tmp/job_tmp:rw --workdir=/tmp/job_output --user=0 --rm --env=TMPDIR=/tmp/job_tmp isbbheavner/snapr_1.0dev57_v2 snapr index /tmp/job435511017_inputs/sequence.fa genome-index > /tmp/tmpgNBWPv/snapr-index.out
Saving genome...3s
[job 40243920] completed success
[job 40243920] {
    "genome_index_hash": {
        "path": "/tmp/tmpgNBWPv/genome-index/GenomeIndexHash", 
        "size": 23639697960, 
        "class": "File", 
        "checksum": "sha1$68e53ba4294d39d698f424b876930419cfc89d43"
    }, 
    "overflow_table": {
        "path": "/tmp/tmpgNBWPv/genome-index/OverflowTable", 
        "size": 3577576044, 
        "class": "File", 
        "checksum": "sha1$3b7692c6485e231bfba6a46668d390f7265e3074"
    }, 
    "genome": {
        "path": "/tmp/tmpgNBWPv/genome-index/Genome", 
        "size": 3099862683, 
        "class": "File", 
        "checksum": "sha1$e8a4e05700eb1395a6726729f8179d6424ce1868"
    }, 
    "genome_index": {
        "path": "/tmp/tmpgNBWPv/genome-index/GenomeIndex", 
        "size": 42, 
        "class": "File", 
        "checksum": "sha1$685a15ef61e0721191f5ab104fec10997d7ffcc5"
    }, 
    "stdout": {
        "path": "/tmp/tmpgNBWPv/snapr-index.out", 
        "size": 3223, 
        "class": "File", 
        "checksum": "sha1$6e9f8a80f5a81e45467ea2fe33e99f753e2da02f"
    }
}
[workflow 56151952] step 40244624 completed
[job 40243920] Removing temporary directory /tmp/tmp3Ls__O
[step 40244112] starting job step file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-pipeline2.cwl#build_transcriptome_index of workflow 56151952
[job 59297104] initializing from file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-transcriptome/snapr-transcriptome.cwl as part of step 40244112
[job 59297104] {
    "gene_set": {
        "path": "file:///cwl-data/workflows/snapr/inputs/annotation.gtf", 
        "class": "File"
    }, 
    "fasta_sequence": {
        "path": "file:///cwl-data/workflows/snapr/inputs/sequence.fa", 
        "class": "File"
    }
}
[job 59297104] command line bindings is [
    {
        "position": [
            -1000000, 
            0
        ], 
        "valueFrom": "snapr"
    }, 
    {
        "position": [
            -1000000, 
            1
        ], 
        "valueFrom": "transcriptome"
    }, 
    {
        "position": [
            1, 
            "gene_set"
        ], 
        "valueFrom": {
            "path": "/tmp/job200329937_inputs/annotation.gtf", 
            "class": "File"
        }
    }, 
    {
        "position": [
            2, 
            "fasta_sequence"
        ], 
        "valueFrom": {
            "path": "/tmp/job200329937_inputs/sequence.fa", 
            "class": "File"
        }
    }, 
    {
        "position": [
            3, 
            "transcriptome_index_dir"
        ], 
        "valueFrom": "transcriptome-index"
    }, 
    {
        "position": [
            4, 
            0
        ], 
        "valueFrom": null, 
        "do_eval": "-O1000"
    }
]
[job 59297104] path mappings is {
    "file:///cwl-data/workflows/snapr/inputs/sequence.fa": [
        "/cwl-data/workflows/snapr/inputs/sequence.fa", 
        "/tmp/job200329937_inputs/sequence.fa"
    ], 
    "file:///cwl-data/workflows/snapr/inputs/annotation.gtf": [
        "/cwl-data/workflows/snapr/inputs/annotation.gtf", 
        "/tmp/job200329937_inputs/annotation.gtf"
    ]
}
[job 59297104] /tmp/tmpp8ejy3$ docker run -i --volume=/cwl-data/workflows/snapr/inputs/sequence.fa:/tmp/job200329937_inputs/sequence.fa:ro --volume=/cwl-data/workflows/snapr/inputs/annotation.gtf:/tmp/job200329937_inputs/annotation.gtf:ro --volume=/tmp/tmpp8ejy3:/tmp/job_output:rw --volume=/tmp/tmpcLmJ3R:/tmp/job_tmp:rw --workdir=/tmp/job_output --user=0 --rm --env=TMPDIR=/tmp/job_tmp isbbheavner/snapr_1.0dev57_v2 snapr transcriptome /tmp/job200329937_inputs/annotation.gtf /tmp/job200329937_inputs/sequence.fa transcriptome-index -O1000 > /tmp/tmpp8ejy3/snapr-transcriptome.out
Saving genome...0s
[job 59297104] completed success
[job 59297104] {
    "genome_index_hash": {
        "path": "/tmp/tmpp8ejy3/transcriptome-index/GenomeIndexHash", 
        "size": 214016, 
        "class": "File", 
        "checksum": "sha1$536546ab4cf76bf98d8ce9bcd4cc62c359c48b28"
    }, 
    "overflow_table": {
        "path": "/tmp/tmpp8ejy3/transcriptome-index/OverflowTable", 
        "size": 0, 
        "class": "File", 
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709"
    }, 
    "genome": {
        "path": "/tmp/tmpp8ejy3/transcriptome-index/Genome", 
        "size": 506, 
        "class": "File", 
        "checksum": "sha1$c8b93f5b50b21673c4c5fa02fc0d6ef83c2bc1fc"
    }, 
    "genome_index": {
        "path": "/tmp/tmpp8ejy3/transcriptome-index/GenomeIndex", 
        "size": 29, 
        "class": "File", 
        "checksum": "sha1$62563e15cbf7d350c7979560f62c7001ddaf7272"
    }, 
    "stdout": {
        "path": "/tmp/tmpp8ejy3/snapr-transcriptome.out", 
        "size": 16225419, 
        "class": "File", 
        "checksum": "sha1$a58d05c87e977a8a97231d727137f6d93ec04677"
    }
}
[workflow 56151952] step 40244112 completed
[job 59297104] Removing temporary directory /tmp/tmpcLmJ3R
[step 40244304] starting job step file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-pipeline2.cwl#run_single_end_alignment of workflow 56151952
[job 59294608] initializing from file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-single-alignment/snapr-single-alignment.cwl as part of step 40244304
[job 59294608] {
    "output_bam_prefix": "G20466.5637.2.single", 
    "transcriptome_index_overflow_table": {
        "path": "/tmp/tmpp8ejy3/transcriptome-index/OverflowTable", 
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709", 
        "class": "File", 
        "size": 0
    }, 
    "genome_index_overflow_table": {
        "path": "/tmp/tmpgNBWPv/genome-index/OverflowTable", 
        "checksum": "sha1$3b7692c6485e231bfba6a46668d390f7265e3074", 
        "class": "File", 
        "size": 3577576044
    }, 
    "genome_index_genome_index": {
        "path": "/tmp/tmpgNBWPv/genome-index/GenomeIndex", 
        "checksum": "sha1$685a15ef61e0721191f5ab104fec10997d7ffcc5", 
        "class": "File", 
        "size": 42
    }, 
    "transcriptome_index_genome_index": {
        "path": "/tmp/tmpp8ejy3/transcriptome-index/GenomeIndex", 
        "checksum": "sha1$62563e15cbf7d350c7979560f62c7001ddaf7272", 
        "class": "File", 
        "size": 29
    }, 
    "genome_index_genome": {
        "path": "/tmp/tmpgNBWPv/genome-index/Genome", 
        "checksum": "sha1$e8a4e05700eb1395a6726729f8179d6424ce1868", 
        "class": "File", 
        "size": 3099862683
    }, 
    "transcriptome_index_genome_index_hash": {
        "path": "/tmp/tmpp8ejy3/transcriptome-index/GenomeIndexHash", 
        "checksum": "sha1$536546ab4cf76bf98d8ce9bcd4cc62c359c48b28", 
        "class": "File", 
        "size": 214016
    }, 
    "output_bam_file": "G20466.5637.2.single.bam", 
    "transcriptome_index_genome": {
        "path": "/tmp/tmpp8ejy3/transcriptome-index/Genome", 
        "checksum": "sha1$c8b93f5b50b21673c4c5fa02fc0d6ef83c2bc1fc", 
        "class": "File", 
        "size": 506
    }, 
    "gene_set": {
        "path": "file:///cwl-data/workflows/snapr/inputs/annotation.gtf", 
        "class": "File"
    }, 
    "genome_index_genome_index_hash": {
        "path": "/tmp/tmpgNBWPv/genome-index/GenomeIndexHash", 
        "checksum": "sha1$68e53ba4294d39d698f424b876930419cfc89d43", 
        "class": "File", 
        "size": 23639697960
    }, 
    "input_bam_file": {
        "path": "file:///cwl-data/workflows/snapr/inputs/G20466.5637.2.bam", 
        "class": "File"
    }
}
[job 59294608] command line bindings is [
    {
        "position": [
            -1000000, 
            0
        ], 
        "valueFrom": "snapr"
    }, 
    {
        "position": [
            -1000000, 
            1
        ], 
        "valueFrom": "single"
    }, 
    {
        "position": [
            1, 
            "genome_index_dir"
        ], 
        "valueFrom": "genome-index"
    }, 
    {
        "position": [
            2, 
            "transcriptome_index_dir"
        ], 
        "valueFrom": "transcriptome-index"
    }, 
    {
        "position": [
            3, 
            "gene_set"
        ], 
        "valueFrom": {
            "path": "/tmp/job138427945_inputs/annotation.gtf", 
            "class": "File"
        }
    }, 
    {
        "position": [
            4, 
            "input_bam_file"
        ], 
        "valueFrom": {
            "path": "/tmp/job138427945_inputs/G20466.5637.2.bam", 
            "class": "File"
        }
    }, 
    {
        "position": [
            5, 
            "output_bam_file"
        ], 
        "prefix": "-o", 
        "valueFrom": "G20466.5637.2.single.bam"
    }
]
[job 59294608] path mappings is {
    "file:///cwl-data/workflows/snapr/inputs/G20466.5637.2.bam": [
        "/cwl-data/workflows/snapr/inputs/G20466.5637.2.bam", 
        "/tmp/job138427945_inputs/G20466.5637.2.bam"
    ], 
    "/tmp/tmpgNBWPv/genome-index/OverflowTable": [
        "/tmp/tmpgNBWPv/genome-index/OverflowTable", 
        "/tmp/job138427945_genome-index/OverflowTable"
    ], 
    "file:///cwl-data/workflows/snapr/inputs/annotation.gtf": [
        "/cwl-data/workflows/snapr/inputs/annotation.gtf", 
        "/tmp/job138427945_inputs/annotation.gtf"
    ], 
    "/tmp/tmpgNBWPv/genome-index/GenomeIndex": [
        "/tmp/tmpgNBWPv/genome-index/GenomeIndex", 
        "/tmp/job138427945_genome-index/GenomeIndex"
    ], 
    "/tmp/tmpgNBWPv/genome-index/Genome": [
        "/tmp/tmpgNBWPv/genome-index/Genome", 
        "/tmp/job138427945_genome-index/Genome"
    ], 
    "/tmp/tmpgNBWPv/genome-index/GenomeIndexHash": [
        "/tmp/tmpgNBWPv/genome-index/GenomeIndexHash", 
        "/tmp/job138427945_genome-index/GenomeIndexHash"
    ], 
    "/tmp/tmpp8ejy3/transcriptome-index/GenomeIndexHash": [
        "/tmp/tmpp8ejy3/transcriptome-index/GenomeIndexHash", 
        "/tmp/job138427945_transcriptome-index/GenomeIndexHash"
    ], 
    "/tmp/tmpp8ejy3/transcriptome-index/Genome": [
        "/tmp/tmpp8ejy3/transcriptome-index/Genome", 
        "/tmp/job138427945_transcriptome-index/Genome"
    ], 
    "/tmp/tmpp8ejy3/transcriptome-index/GenomeIndex": [
        "/tmp/tmpp8ejy3/transcriptome-index/GenomeIndex", 
        "/tmp/job138427945_transcriptome-index/GenomeIndex"
    ], 
    "/tmp/tmpp8ejy3/transcriptome-index/OverflowTable": [
        "/tmp/tmpp8ejy3/transcriptome-index/OverflowTable", 
        "/tmp/job138427945_transcriptome-index/OverflowTable"
    ]
}
[job 59294608] /tmp/tmpBDFnet$ docker run -i --volume=/cwl-data/workflows/snapr/inputs/G20466.5637.2.bam:/tmp/job138427945_inputs/G20466.5637.2.bam:ro --volume=/tmp/tmpgNBWPv/genome-index/OverflowTable:/tmp/job138427945_genome-index/OverflowTable:ro --volume=/cwl-data/workflows/snapr/inputs/annotation.gtf:/tmp/job138427945_inputs/annotation.gtf:ro --volume=/tmp/tmpgNBWPv/genome-index/GenomeIndex:/tmp/job138427945_genome-index/GenomeIndex:ro --volume=/tmp/tmpgNBWPv/genome-index/Genome:/tmp/job138427945_genome-index/Genome:ro --volume=/tmp/tmpgNBWPv/genome-index/GenomeIndexHash:/tmp/job138427945_genome-index/GenomeIndexHash:ro --volume=/tmp/tmpp8ejy3/transcriptome-index/GenomeIndexHash:/tmp/job138427945_transcriptome-index/GenomeIndexHash:ro --volume=/tmp/tmpp8ejy3/transcriptome-index/Genome:/tmp/job138427945_transcriptome-index/Genome:ro --volume=/tmp/tmpp8ejy3/transcriptome-index/GenomeIndex:/tmp/job138427945_transcriptome-index/GenomeIndex:ro --volume=/tmp/tmpp8ejy3/transcriptome-index/OverflowTable:/tmp/job138427945_transcriptome-index/OverflowTable:ro --volume=/tmp/tmpBDFnet:/tmp/job_output:rw --volume=/tmp/tmpbzjTOZ:/tmp/job_tmp:rw --workdir=/tmp/job_output --user=0 --rm --env=TMPDIR=/tmp/job_tmp isbbheavner/snapr_1.0dev57_v2:latest snapr single genome-index transcriptome-index /tmp/job138427945_inputs/annotation.gtf /tmp/job138427945_inputs/G20466.5637.2.bam -o G20466.5637.2.single.bam > /tmp/tmpBDFnet/snapr-single-end-alignment.out
'docker' not found
[job 59294608] completed permanentFail
[job 59294608] {}
[workflow 56151952] step 40244304 completed
Output is missing expected field file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-pipeline2.cwl#run_single_end_alignment.output
Output is missing expected field file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-pipeline2.cwl#run_single_end_alignment.stdout
Workflow step file:///home/abby/bioinformatics-pipelines/cwl-examples/snapr/snapr-pipeline2.cwl#run_single_end_alignment completion status is permanentFail
[job 59294608] Removing temporary directory /tmp/tmpbzjTOZ
[job 59294608] Removing empty output directory /tmp/tmpbzjTOZ
[workflow 56151952] outdir is /home/abby/bioinformatics-pipelines/cwl-examples/snapr
Final process status is permanentFail
Workflow error:
  Process status is ['permanentFail']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cwltool/main.py", line 437, in main
    move_outputs=args.move_outputs
  File "/usr/local/lib/python2.7/dist-packages/cwltool/main.py", line 165, in single_job_executor
    raise workflow.WorkflowException("Process status is %s" % (final_status))
WorkflowException: Process status is ['permanentFail']
```

And the output of "sudo docker version" in case that's relevant:

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

Just as a note (in case anyone tries to run this example) -- the index generation steps are very memory intensive, and need ~48-60 GB of memory to perform reasonably.

EDIT:  I probably should've mentioned the memory requirement applies to runs with the _human_ genome.  I'm not sure how much the memory requirement can be reduced if you use a FASTA+GTF+BAM combination from another organism.

**Comment by ntijanic** [comment]
Did you try manually running the docker command after the failure happens? The temporary files should still be there at the time, so just running it from shell should work.

@tetron Any idea why docker runner would work for first two steps but not for third? It seems like the log came from this line (caught OSError code 2):

https://github.com/common-workflow-language/cwltool/blob/6f6feebd2cf18d38667830ff865a1d639348d8b4/cwltool/job.py#L169

**Comment by vardaofthevalier** [comment]
@ntijanic , I tried re-running the final docker command, but instead of the "docker not found" error, I ended up getting an error from the command line program executing inside of it.  There is still a problem using CreateFileRequirement to implicitly create a directory for use as an input parameter, because it looks like all of those directories that are created have the string "jobXXXXXXXXX_" inserted at the beginning, where the "X"s are digits.  Therefore, the tool is unable to find the input directories because I have coded it to look for a directory name that doesn't contain that inserted portion of the string.  Is there any way to reference the job number from the job object or the context object in an expression, so that I can construct the correct directory name as an input parameter?

**Comment by vardaofthevalier** [comment]
I have just recently gotten past this error, and I think I may have narrowed this down to some bit of code above line 129 in the "try" block in job.py.  One of my colleagues had originally suspected that "docker not found" might be a result of the way that subprocess was being used to spawn the docker processes, but placing a call to _logger.info(...) right above that line per his recommendation caused it not to be printed out at all.  

Interestingly, I was able to get the third step to run after removing the instances of CreateFileRequirement in that step.  I had originally thought that using CreateFileRequirement would be necessary for being able to sort the inputs into their appropriate directories to use as input to the third step, but I realized that I actually didn't need it because I noticed that I was already creating the files implicitly inside of the correct directories in the previous steps, which I must've forgotten about while I was coding.  Instead I was able to construct the correct directory names from the existing path values as they were when they were outputted by steps 1 and 2.

I would propose maybe splitting up that try block so that errors produced within the first half of it aren't confused for errors associated with the runtime, as that is a bit misleading.  I will work on narrowing down exactly where the issue occurred and update this issue when I have more information.

**Comment by tetron** [comment]
Hi @vardaofthevalier this sounds like more of an issue with the error reporting  behavior of the reference implementation, could you open a bug on [cwltool](https://github.com/common-workflow-language/cwltool) ?

**Comment by mr-c** [comment]
Ping @vardaofthevalier Is this still an issue?

**Comment by hellymac** [comment]
Hello @tetron and @mr-c,
I have the same kind of issue when I use "DockerOutputDirectory".
`ERROR 'docker' not found: [Errno 2] No such file or directory: '/root/cwl-workflow-SARS-CoV-2/Variation/data/NC_045512.2' -> '/tmp/nt4l4snj/ovid19/genes.gbk'`
I don't get where does the "ovid19" come from because in the cwl file I don't mention it :
```
class: CommandLineTool
cwlVersion: v1.0
baseCommand: [snpEff, build]
arguments:
  - -v #verbose
  - -dataDir /data
  - -configOption $(inputs.dbname).genome=$(inputs.dbname)
inputs:
  - id: dbname
    type: string
    inputBinding:
      prefix: -genbank
      position: 1000
  - id: bankfile
    type: File
outputs:  []
requirements:
  - class: DockerRequirement
    dockerPull: biocontainers/snpeff:v4.1k_cv3
    dockerOutputDirectory: /data/
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - entry: "$({class: 'Directory', listing: []})"
        entryname: $(inputs.dbname)
        writable: true
      - entryname: $(inputs.dbname)/genes.gbk
        entry: $(inputs.bankfile)
```
and the command is : 
```
 [job snpeff_build.cwl] /tmp/nt4l4snj$ docker \
    run \
    -i \
    --mount=type=bind,source=/tmp/nt4l4snj,target=/data/ \
    --mount=type=bind,source=/tmp/frr88klb,target=/tmp \
    --mount=type=bind,source=/tmp/zxa9hq00/covid19,target=/data/covid19 \
    --mount=type=bind,source=/root/cwl-workflow-SARS-CoV-2/Variation/data/NC_045512.2,target=/data/covid19/genes.gbk,readonly \
    --workdir=/data/ \
    --read-only=true \
    --user=0:0 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/data/ \
    --cidfile=/tmp/kkmyf93x/20200424150246-258688.cid \
    biocontainers/snpeff:v4.1k_cv3 \
    snpEff \
    build \
    -v \
    '-dataDir /data' \
    '-configOption covid19.genome=covid19' \
    -genbank \
    covid19
```
When I don't use "dockerOutputDirectory", no error... but the tool doesn't work
Do you have an idea of what can causes this error ?
