### ISSUE TITLE
Add `cwl:requirements` field to input document for overrides

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#210]
Will be useful for overriding DockerRequirement with custom image name. HPC/grid computing users could use it to give site-specific guidance as well.

**Comment by mr-c** [comment]
PR for cwltool: https://github.com/common-workflow-language/cwltool/pull/99

**Comment by mr-c** [comment]
Does it make sense to allow hints in the input document as well?

**Comment by seandavi** [comment]
Just a thought, but I have seen other workflow systems use a separate config for this.  This makes the separation of concerns clear and results in 3 files:

1. CWL--the workflow itself
2. inputs--in the strict sense
3. environment-specific config--hints, requirements

Just a thought....

**Comment by mr-c** [comment]
PR with the proposed spec changes: https://github.com/common-workflow-language/common-workflow-language/pull/304

**Comment by mr-c** [comment]
@seandavi A specific implementation could follow that route. Since the input document often has local paths anyhow we felt it was fine to combine them. One could import 3 into 2 or vice versa for more separation, but I would prefer to keep things simple for now.

**Comment by tetron** [comment]
Thinking about this feature, I think this needs to include a way to do targeted overrides on specific workflow steps or CommandLineTools.  Setting requirements at the top level doesn't work when different steps have different requirements.

**Comment by tetron** [comment]
For example:

```
cwl:requirements:
  workflow.cwl#step1:
    DockerRequirement:
      dockerPull: dockerImageA
  workflow.cwl#step2:
    DockerRequirement:
      dockerPull: dockerImageB
```

**Comment by mr-c** [comment]
@tetron I like it; what about overall reqs?

**Comment by tetron** [comment]
@mr-c 

Set requirements at the workflow level by referencing the workflow.

Consider renaming it `cwl:override` since the syntax would be a bit different from the normal `requirements` field.

```
cwl:override:
  workflow.cwl:
    DockerRequirement:
      dockerPull: dockerImageA
  workflow.cwl#step2:
    DockerRequirement:
      dockerPull: dockerImageB
  tool_used_by_workflow.cwl:
    DockerRequirement:
      dockerPull: dockerImageC
```

Perhaps `override` could be a legal Workflow field?

```
class: Workflow
requirements:
  tool_used_by_workflow.cwl:
    DockerRequirement:
      dockerPull: dockerImageA
override:
  tool_used_by_workflow.cwl:
    DockerRequirement:
      dockerPull: dockerImageC
```

**Comment by tetron** [comment]
Now implemented in cwltool, with addition of "requirements" field between the target and the list of requirements (so that override of other fields can be supported in the future).

```
cwl:override:
  workflow.cwl:
    requirements:
      DockerRequirement:
        dockerPull: dockerImageA
  workflow.cwl#step2:
    requirements:
      DockerRequirement:
        dockerPull: dockerImageB
  tool_used_by_workflow.cwl:
    requirements:
      DockerRequirement:
        dockerPull: dockerImageC
```

**Comment by tom-tan** [comment]
I am curious about how to disable `DockerRequirement`.
This feature can override `hints` by `requirements` to force the platforms to use containers.
Is there a way to override `hints` by `requirements` not to use containers?

**Comment by mr-c** [comment]
@tom-tan Currently that is achievable via platform specific configuration. For example, `cwltool --no-containers …`.

I guess we could consider an override `DockerRequirement` whose contents are empty to be equivalent to removing that requirement, however for some of the other requirements types that usage would look equivalent to specifying that it **should** be used.

**Comment by ionox0** [comment]
Hi cwltool team, 

I had to add the following lines to [`ref_resolver.py`](https://github.com/common-workflow-language/cwltool/blob/master/cwltool/schemas/v1.1.0-dev1/salad/schema_salad/ref_resolver.py#L865)
```
                    if isinstance(base_url, list):
                        base_url = base_url[0]
```
Because I was receiving this error:
```
Traceback (most recent call last):
  File "/Users/johnsoni/Desktop/virtualenv/msk/bin/toil-cwl-runner", line 11, in <module>
    sys.exit(main())
  File "/Users/johnsoni/Desktop/virtualenv/msk/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 962, in main
    options, sys.stdin, None, [], options.job_order)
  File "/Users/johnsoni/Desktop/virtualenv/msk/lib/python2.7/site-packages/cwltool/main.py", line 140, in load_job_order
    overrides.extend(resolve_overrides(job_order_object, file_uri(job_order_file), tool_file_uri))
  File "/Users/johnsoni/Desktop/virtualenv/msk/lib/python2.7/site-packages/cwltool/load_tool.py", line 356, in resolve_overrides
    ret, _ = ovloader.resolve_all(ov, baseurl)
  File "/Users/johnsoni/Desktop/virtualenv/msk/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 869, in resolve_all
    val, base_url+subscope, file_base=file_base, checklinks=False)
TypeError: can only concatenate list (not "str") to list
```
When supplying this overrides parameter to toil-cwl-runner in my inputs.yaml:
```
cwltool:overrides:
  # Todo: can use relative path?
  file:///Users/johnsoni/Desktop/code/Innovation-Pipeline/cwl_tools/abra/abra.cwl:
    requirements:
    - class: ResourceRequirement
      ramMin: 5000
      coresMin: 1
```
### Versions:
cwltool 1.0.20180306140409
toil 3.15.0

I can try with a newer version of cwltool if need be, but this is the version installed with toil 3.15.0. Let me know if this is an appropriate place for this type of comment, I can move it to an issue if need be.
