### ISSUE TITLE
shortcut proposal: File subtypes stdout & stderr 

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#218]
To replace the common pattern (using the draft4.dev1 syntax):

```
outputs:
  output_file:
    type: File
    outputBinding:
      glob: stdout_file

stdout: stdout_file
```

with

```
outputs:
  output_file:
    type: stdout
```

the `outputBinding` & `glob` to a randomly chosen filename are implied along with the stdout redirection to the filename.

`type: stderr` would likewise be supported

**Comment by tetron** [comment]
In keeping with the trend in making common cases easier, this seems like a good idea.

**Comment by tetron** [comment]
I suggest also being able to name the Ffile from stdout the normal way:

```
outputs:
  output_file:
    type: stdout
stdout: blahblah.txt
```
