### ISSUE TITLE
Should we require ports to always define type or always specify "depth" property?

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#22]
(or perhaps neither of those?)

Avro is pretty strict when defining types. If port schemas are required and data dimensions determined from the schema (as is the case with the reference implementation at the moment), this disallows generic  or flexible (e.g. "this input is a dict of whatever configuration") tools. Example:

```yaml
class: ExpressionTool
description: Flatten a list of lists of things to a single list of things.
inputs:
  - id: "#list"
outputs:
  - id: "#flattened"
script:
  class: JavascriptExpression
  value: "return {flattened: [].concat.apply([], $job.inputs.list)}"
```

I don't think there's a way to specify input/output type in Avro for the above example (List\<List\<T>> and List\<T>), but the dimensionality needs to be known for implicit parallel-for-each.

One way to resolve this would be to explicitly define a "depth" property of each input/output and not require a schema at all. Any other suggestions?
