### ISSUE TITLE
Trouble linking output

### ISSUE THREAD

**Issue by thomasyu888** [common-workflow-language/common-workflow-language#226]
Hello all,

Thanks in advance for your time.  I'm having linking output with this [gunzip cwl](https://github.com/Sage-Bionetworks/SMC-RNA-Examples/blob/master/rsem/cwl/gunzip.cwl)  in a CWL workflow.  The workflow file is [here](https://github.com/Sage-Bionetworks/SMC-RNA-Examples/blob/master/workflow/smcIsoform-rsem-workflow.cwl#L35)

Initially I had the glob output as:
```
outputs:
  - id: output
    type: File
    outputBinding:
      glob: $(inputs.input.path.split(".").slice(0,-1).join("."))
```
But this was the error:
```
[job gunzip] /home/ubuntu/97f054d0c37ab170d7f18761f2399489$ gunzip \
    /home/ubuntu/dryrun5_mergeSort_1.fq.gz
Error while running job: Error collecting output for parameter 'output': glob patterns must not start with '/'
```
I changed the output to be 
```
outputs:
  - id: output
    type: File
    outputBinding:
      glob: $(inputs.input.path.split(".").slice(0,-1).join(".").split("/").slice(-1)[0])
```
and I get this error:
```
 Error while running job: Error collecting output for parameter 'output': Did not find output file with glob pattern
: '[u'dryrun5_mergeSort_1.fq']'
```
However, the above file definitely exists in my directory and gunzip.cwl works on a file like so:
```
cwl-runner gunzip.cwl --input foo.txt.gz
```

**Comment by mr-c** [comment]
Hello @thomasyu888, thank you for using CWL and for sharing your issue.

Is the error during workflow execution or while running the standalone tool?

Are you using the reference implementation or another implementation. What version?

With the reference implementation, `cwltool`, this runs with no errors for me:
``` shell
$ gzip hello.tar
$ cwltool gunzip.cwl --input hello.tar.gz 
/home/michael/common-workflow-language/env/bin/cwltool 1.0.20160531173804
[job gunzip.cwl] /home/michael/common-workflow-language/draft-3/draft-3$ gunzip \
    /home/michael/common-workflow-language/draft-3/draft-3/hello.tar.gz
Final process status is success
{
    "output": {
        "size": 10240, 
        "path": "/home/michael/common-workflow-language/draft-3/draft-3/hello.tar", 
        "checksum": "sha1$bf757d2cf23320f3321761286c0d0deea446acf2", 
        "class": "File"
    }
}
$ ls hello.tar*
hello.tar
```

**Comment by thomasyu888** [comment]
Hello @mr-c 

Thank you for your assistance.

Please clone this repository: https://github.com/thomasyu888/test_CWL.git and run workflow.cwl and workflow2.cwl (gzip the file in there in between runs) Please provide the full path to your file as input:

workflow1
```
cwl-runner workflow.cwl --input /home/ubuntu/test_CWL/temp.txt.gz
/usr/local/bin/cwl-runner 1.0.20160531173804
[job gunzip] /tmp/tmp6PLl3L$ gunzip \
    /home/ubuntu/test_CWL/temp.txt.gz
Error while running job: Error collecting output for parameter 'output': glob patterns must not start with '/'
[job gunzip] completed permanentFail
Output is missing expected field file:///home/ubuntu/test_CWL/workflow.cwl#gunzip/output
[step gunzip] completion status is permanentFail
Workflow error, try again with --debug for more information:
  Output for workflow not available
```

workflow2
```
gzip /home/ubuntu/test_CWL/temp.txt.gz
cwl-runner workflow2.cwl --input /home/ubuntu/test_CWL/temp.txt.gz
/usr/local/bin/cwl-runner 1.0.20160531173804
[job gunzip] /tmp/tmpYFNGF9$ gunzip \
    /home/ubuntu/test_CWL/temp.txt.gz
Error while running job: Error collecting output for parameter 'output': Did not find output file with glob pattern
: '[u'temp.txt']'
[job gunzip] completed permanentFail
Output is missing expected field file:///home/ubuntu/test_CWL/workflow.cwl#gunzip/output
[step gunzip] completion status is permanentFail
Workflow error, try again with --debug for more information:
  Output for workflow not available
```

It is able to run by itself when I do:

```
cwl-runner gunzip.cwl --input /home/ubuntu/test_CWL/temp.txt.gz
/usr/local/bin/cwl-runner 1.0.20160531173804
[job gunzip.cwl] /home/ubuntu/test_CWL$ gunzip \
    /home/ubuntu/test_CWL/temp.txt.gz
Final process status is success
{
    "output": {
        "size": 5, 
        "path": "/home/ubuntu/test_CWL/temp.txt", 
        "checksum": "sha1$aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d", 
        "class": "File"
    }
}
```

**Comment by tetron** [comment]
Hi @thomasyu888 

The problem is that `gunzip` is not a well behaved program by CWL standards.  It creates a file in the input directory (not the output directory) and deletes the original file.  Both of these are generally not allowed by CWL.  Here's a version of the gunzip wrapper which uses `gunzip -c` which should work:

```
#!/usr/bin/env cwl-runner

cwlVersion: "draft-3"

class: CommandLineTool

description: "command line: gunzip"

requirements:
  - class: InlineJavascriptRequirement

inputs:

  - id: input
    type: File
    inputBinding:
      position: 0

outputs:
  - id: output
    type: File
    outputBinding:
      glob: $(inputs.input.path.split("/").slice(-1)[0].split(".").slice(0,-1).join("."))

baseCommand: [gunzip, -c]
stdout: $(inputs.input.path.split("/").slice(-1)[0].split(".").slice(0,-1).join("."))
```
