### ISSUE TITLE
ExpressionTool incorrectly extends interface Process

### ISSUE THREAD

**Issue by mayacoda** [common-workflow-language/common-workflow-language#239]
Another bug that came up while [mapping CWL to TypeScript](https://github.com/rabix/cwl-ts) :). The definition of an [ExpressionTool](https://github.com/common-workflow-language/common-workflow-language/blob/master/draft-4/Workflow.yml#L80) specifies that it extends Process and specializes OutputParameter to ExpressionToolOutputParameter.

```
- type: record
  name: ExpressionTool
  extends: Process
  specialize:
    - specializeFrom: "#OutputParameter"
      specializeTo: "#ExpressionToolOutputParameter"
```

However, the definition of [ExpressionToolOutputParameter](https://github.com/common-workflow-language/common-workflow-language/blob/master/draft-4/Workflow.yml#L53) specifies that it extends Parameter, not OutputParameter. There is a type mismatch because Process expects an array of OutputParameter, but gets an array of ExpressionToolOuputParameter which extends Parameter.

```
- name: ExpressionToolOutputParameter
  type: record
  extends: Parameter
```
