### ISSUE TITLE
reusing custom record types: what to do about inputBindings?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#241]
Currently the only place to specify the inputBindings for a custom record is in the definition of the record type itself (in the`SchemaDefRequirement`).

However, if we want to reuse these custom types between different tools then we have a problem if the the inputBindings need to be different.

Any solution I can imagine is too complicated for v1.0, so this will have to wait for v1.1.

Example:

```
class: SchemaDefRequirement
types:
 - name: paired-reads
   type: record
   fields:
     - name: left-reads
       type: File
       inputBinding:
         position: 2
     - name: right-reads
       type: File
       inputBinding:
         position: 3
```
