### ISSUE TITLE
SoftwareRequirement discussion

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#245]
A few quick thoughts of the SoftwareRequirement/SoftwareSpec additions.

The thing I would most like to add would be some explicit notion of the runtime corresponding to the package, and the idea that there may be several ways to satisfy the dependency, and the implementation should pick one based on the environment, e.g.:

```
SoftwareRequirement:
  - id: bwa
    satisfiedBy:
      - runtime: [conda, debian]
        package: bwa
      - runtime: configure-make-install
        package: http://path-to-tarball
```
