### ISSUE TITLE
Add Example Tool Demonstrating Fictitious Platform Extensions 

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-language/common-workflow-language#26]
Possible Extensions:
- UI hints on input parameters.
- Runtime modifications to the command-line.
- Tool-level metadata (Platform X certification-level, location in the UI, etc...)

**Comment by ntijanic** [comment]
I'm not sure what you mean by "Runtime modifications to the command-line". Can you give an example?

For UI hints and custom metadata I'd suggest something like this:

```yaml
class: CommandLineTool
galaxy:toolbox_categories: [NGS, Aligners]
galaxy:process_version_cmd: ["mytool", "--version"]
inputs:
  - id: "#text"
    type: "string"
    galaxy:form_element: textbox
# ...
```
