### ISSUE TITLE
How can I use glob to get files not relative to output directory ?

### ISSUE THREAD

**Issue by EcoRIIHC** [common-workflow-language/common-workflow-language#280]
Thank you for your time :)
I write a program to create testing data to workdir , the .cwl and .yml like this , but when I run the cwl , I got this : glob patterns must not start with '/' , then I want to know , how can get files which is not relative to the output(current) directory , becacuse sometimes our workflow's inputs are the outputs of the last step , and I don't know how to give the output to the step .

```
#cwl
cwlVersion: cwl:draft-3
class: CommandLineTool
baseCommand: scala
inputs:
  - id: makeDataProgram
    type: File
    inputBinding:
      position: 1
  - id: dataPath
    type: string
    inputBinding:
      position: 2
#outputs: []
outputs:
  - id: dataFile
    type: File
    outputBinding:
      glob: $(inputs.dataPath)
```
# yml

```
makeDataProgram:
    class: File
    path: "/root/workspace/SampleData.scala"
dataPath: '/root/sample_age_data.txt'
```
