### ISSUE TITLE
access files through ExpressionTool

### ISSUE THREAD

**Issue by jeremiahsavage** [common-workflow-language/common-workflow-language#296]
Should I be able to copy a file array from inputs to outputs using ExpressionTool?

I've created an attempt at this, but the output contains the output dir as the file location rather than the starting location paths:

https://github.com/jeremiahsavage/common-workflow-language/tree/test/file-expression/v1.0/v1.0
```

$ cwltool --debug file-expression-workflow.cwl file-expression-workflow-job.json 
/home/ubuntu/.virtualenvs/cwl_gdc/bin/cwltool 1.0
[workflow file-expression-workflow.cwl] initialized step from file:///home/ubuntu/common-workflow-language/v1.0/v1.0/file-expression-workflow.cwl
[workflow file-expression-workflow.cwl] workflow starting
[workflow file-expression-workflow.cwl] starting step file_expression
[job step file_expression] job input {
    "file:///home/ubuntu/common-workflow-language/v1.0/v1.0/file-expression-workflow.cwl#file_expression/INPUT": [
        {
            "basename": "example_human_Illumina.pe_1.fastq", 
            "class": "File", 
            "location": "file:///home/ubuntu/common-workflow-language/v1.0/v1.0/example_human_Illumina.pe_1.fastq"
        }, 
        {
            "basename": "example_human_Illumina.pe_2.fastq", 
            "class": "File", 
            "location": "file:///home/ubuntu/common-workflow-language/v1.0/v1.0/example_human_Illumina.pe_2.fastq"
        }
    ]
}
[job step file_expression] evaluated job input to {
    "file:///home/ubuntu/common-workflow-language/v1.0/v1.0/file-expression-workflow.cwl#file_expression/INPUT": [
        {
            "basename": "example_human_Illumina.pe_1.fastq", 
            "class": "File", 
            "location": "file:///home/ubuntu/common-workflow-language/v1.0/v1.0/example_human_Illumina.pe_1.fastq"
        }, 
        {
            "basename": "example_human_Illumina.pe_2.fastq", 
            "class": "File", 
            "location": "file:///home/ubuntu/common-workflow-language/v1.0/v1.0/example_human_Illumina.pe_2.fastq"
        }
    ]
}
Output is missing expected field file:///home/ubuntu/common-workflow-language/v1.0/v1.0/file-expression-workflow.cwl#file_expression/OUTPUT
[step file_expression] produced output {}
[step file_expression] completion status is permanentFail
Workflow error, try again with --debug for more information:
  Output for workflow not available
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/cwl_gdc/local/lib/python2.7/site-packages/cwltool/main.py", line 725, in main
    **vars(args))
  File "/home/ubuntu/.virtualenvs/cwl_gdc/local/lib/python2.7/site-packages/cwltool/main.py", line 212, in single_job_executor
    for r in jobiter:
  File "/home/ubuntu/.virtualenvs/cwl_gdc/local/lib/python2.7/site-packages/cwltool/workflow.py", line 410, in job
    for w in wj.job(builder.job, output_callback, **kwargs):
  File "/home/ubuntu/.virtualenvs/cwl_gdc/local/lib/python2.7/site-packages/cwltool/workflow.py", line 381, in job
    raise WorkflowException("Output for workflow not available")
WorkflowException: Output for workflow not available
(cwl_gdc)ubuntu@frontend001:~/common-workflow-language/v1.0/v1.0$ 

```

**Comment by tetron** [comment]
There is a bug in your workflow.

```
expression: |
   ${
      var output = inputs.INPUT;
      return [ {'OUTPUT': output} ]
}
```

This should be

```
expression: |
   ${
      var output = inputs.INPUT;
      return {'OUTPUT': output}
}
```

**Comment by jeremiahsavage** [comment]
Thank you.

Do you know how one would return multiple outputs?
```

#!/usr/bin/env cwl-runner

cwlVersion: v1.0

requirements:
  - class: InlineJavascriptRequirement

class: ExpressionTool

inputs:
  - id: INPUT
    type:
      type: array
      items: File

outputs:
  - id: OUTPUT
    type:
      type: array
      items: File

  - id: SORTED
    type:
      type: array
      items: File

expression: |
   ${
      var output = inputs.INPUT;
      var sorted = output.sort(function(a,b) { return a.location > b.location } )
      return {'OUTPUT': output}, {'SORTED': sorted }
    }
```


only returns SORTED, and not OUTPUT.
