### ISSUE TITLE
Add links to implementation extensions to website

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#323]
- [x] Seven Bridge main: https://github.com/rabix/bunny/wiki/CWL-draft-2-extensions
- [ ] Seven Bridges UI
- [ ] Arvados
- [ ] Galaxy

**Comment by pr80ik** [comment]
the ICA link has moved to https://support-docs.illumina.com/SW/ICA/Content/SW/ICA/RequestResources.htm

an example usage is:

```yaml
hints:
- class: ResourceRequirement

  ilmn-tes:resources:
    tier: <economy or standard tier>
    type: <resource type>
    size: <size> 
```
