### ISSUE TITLE
ExpressionTool output files problem

### ISSUE THREAD

**Issue by michael-kotliar** [common-workflow-language/common-workflow-language#325]
Hello CWL community! I'm trying to use the following cwl tool, which is on 99% the same as from https://github.com/common-workflow-language/workflows/blob/master/tools/join-bam-with-index.cwl 

``` yaml
#!/usr/bin/env cwl-runner
cwlVersion: v1.0

class: ExpressionTool

doc: Produces a BAM with with its index as a secondaryFile from two distinct
 inputs.

requirements:
 - class: InlineJavascriptRequirement

inputs:
  bam:
    type: File
  bam-index:
    type: File

outputs:
  bam-with-index:
    type: File

expression: >
  ${
    inputs.bam.secondaryFiles = [ inputs["bam-index"] ];
    return { "bam-with-index": inputs.bam };
  }
```

The job file is

``` yaml
{
  "bam": {"class": "File", "location": "../star/starAlignReads/Aligned.sortedByCoord.out.bam"},
  "bam-index": {"class": "File", "location": "../samtoolsIndex/Aligned.sortedByCoord.out.bam.bai"}
}
```

After running this workflow
`cwl-runner --debug join-bam-with-index.cwl join-bam-with-index-job.json`

I receive the following output

``` yaml
/home/michael_kotliar/.local/bin/cwl-runner 1.0.20160930152149
Final process status is success
Removing intermediate output directory /tmp/tmpa8kUOX
{
    "bam-with-index": {
        "secondaryFiles": [
            {
                "path": "/mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/workflows/test/test-files/expressionTools/Aligned.sortedByCoord.out.bam.bai", 
                "basename": "Aligned.sortedByCoord.out.bam.bai", 
                "class": "File", 
                "location": "file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/workflows/test/test-files/expressionTools/Aligned.sortedByCoord.out.bam.bai"
            }
        ], 
        "basename": "Aligned.sortedByCoord.out.bam", 
        "path": "/mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/workflows/test/test-files/expressionTools/Aligned.sortedByCoord.out.bam", 
        "class": "File", 
        "location": "file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/workflows/test/test-files/expressionTools/Aligned.sortedByCoord.out.bam"
    }
}
```

And everything would be nice if I could see the output files in a folder where I run workflow.
Does it suppose to be like this?
If yes, and we don't actually copy files from one location to other (which looks logical), shouldn't we change the location field in output that we receive to the real one? Because in my case all of the locations direct to the place where I run cwl, but not to the actual place on my harddrive.
When I tried to integrate this tool into my workflow I received an error 
`Missing input file [Errno 2] No such file or directory: '/tmp/tmplsZjU6/Aligned.sortedByCoord.out.bam.bai'`

If it's not a bug, and I'm just using this ExpressionTool in a wrong way, I would appreciate if you give me links to the working examples.

**Comment by StarvingMarvin** [comment]
Tool outputs must come from the working dir. The way to work around it is to use 
[InitialWorkDirRequirement](http://www.commonwl.org/v1.0/CommandLineTool.html#InitialWorkDirRequirement)

    requirements:
      - class: InitialWorkDirRequirement
        listing:
          - $(inputs.bam)
          - $(inputs.bam-index)

By default, files should be linked to working dir, unless `writable: true` is set on listing items:

requirements:
      - class: InitialWorkDirRequirement
        listing:
          - entry: $(inputs.to_be_changed)
          - writable: true

Only then you should get a copy.

**Comment by michael-kotliar** [comment]
Thanks for the advice, but not sure if it can help me. According to the log it first removes input staging directory and then moves results to the folder where cwl was run. So I can't return any file that was staged into output directory.

This is how I tested it:
1. Create empty input file
`touch ./data/Hello1.txt`
2. Run cwl in a current folder
`cwl-runner --debug stage_input.cwl job.json`, which should

-      stage `Hello1.txt` into output directory
-      copy `Hello1.txt` into `Hello2.txt`
-      return `Hello1.txt` and `Hello2.txt`

The only result that I received was `Hello2.txt`.



stage_input.cwl
```yaml
cwlVersion: v1.0
class: CommandLineTool
hints:
  DockerRequirement:
    dockerPull: ubuntu
baseCommand: cp

requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - $(inputs.src)

inputs:
  src:
    type: File
    inputBinding:
      position: 1
      valueFrom: $(self.basename)

  target:
    type: string
    inputBinding:
      position: 2

outputs:
  out_src:
    type: File
    outputBinding:
      glob: "Hello1.txt"
  out_target:
    type: File
    outputBinding:
      glob: "Hello2.txt"
```

job.json
```json
{
  "src": {
    "class": "File",
    "path": "./data/Hello1.txt"
  },

  "target": "Hello2.txt"
}
```
Important part of log
```
Final process status is success
[job stage_input.cwl] Removing input staging directory /var/folders/sd/41rg42_16q72_2yzl_vvgsbw0000gn/T/tmpjBDYCd
[job stage_input.cwl] Removing temporary directory /var/folders/sd/41rg42_16q72_2yzl_vvgsbw0000gn/T/tmpUMP3kD
Moving /var/folders/sd/41rg42_16q72_2yzl_vvgsbw0000gn/T/tmpYMQzmO/Hello2.txt to /Users/kot4or/workspaces/cwl_ws/sandbox/stage_input/Hello2.txt
```

**Comment by michael-kotliar** [comment]
There is another problem of running this ExpressionTool (the first one that I put in this issue) inside workflow.
According to what Peter Amstutz told on gitter:
> if you run it as part of the workflow, it would not copy/move the files, but would use symlinks or docker bind mounts to make the files appear to be in the same directory

So if the next step of workflow tries to get secondaryFiles from the same place where the primary file is, it gets error because of different locations, despite the fact that both primary and secondaryFiles will be mounted in the same folder, when cwl-runner runs docker container for this step.

Example of step's input which waits primary and secondaryFiles to be placed in the same folder. Locations are different.
```yaml
        "checksum": "sha1$14a6131e63111ae46be347dc3173b5e46edeb36a", 
        "basename": "Aligned.sortedByCoord.out.bam", 
        "location": "file:///tmp/tmp_eGMO3/Aligned.sortedByCoord.out.bam", 
        "secondaryFiles": [
            {
                "checksum": "sha1$3e5462afb7b9586853d2c91a72c7a4f904dd56f4", 
                "basename": "Aligned.sortedByCoord.out.bam.bai", 
                "location": "file:///tmp/tmpZu07Kw/Aligned.sortedByCoord.out.bam.bai", 
                "class": "File", 
                "size": 984
            }
        ], 
        "class": "File", 
        "size": 38321
    }, 
```
