### ISSUE TITLE
Type mismatch between source and sink when using merge_nested for single-item list of input link

### ISSUE THREAD

**Issue by michael-kotliar** [common-workflow-language/common-workflow-language#330]
Hello! Noticed one problem, that could be a bug or just my misunderstanding.
Following example runs only one step which requires File [ ] to be set as an input. Workflow has two File inputs, which I combine using MultipleInputFeatureRequirement. The problem is that if I set only one file as input for the step, it gives me error:

```
  Type mismatch between source 'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/sandbox/mergedInput/workflow.cwl#fileA' (File) and sink 'file:///mnt/data/HOME/michael_kotliar/workspaces/cwl_ws/sandbox/mergedInput/workflow.cwl#concat/files' ({u'items': 'File', u'type': u'array'})
```

According to the manual it should work:

> If "merge_nested" is specified with a single link, the value from the link must be wrapped in a single-item list.

``` yaml
cwlVersion: v1.0
class: Workflow

requirements:
  - class: MultipleInputFeatureRequirement

inputs:
  fileA:
    type: File
  fileB:
    type: File

outputs:
  FileC:
    type: File
    outputSource: concat/outputFile

steps:
  concat:
    run: ./concat.cwl
    in:
      files: [fileA, fileB] # works fine
    # files: [fileA] # doesn't work
    out: [outputFile]
```

Example that I tested https://github.com/michael-kotliar/cwl_sandbox/tree/master/mergedInput
