### ISSUE TITLE
new construct to turn a CWL object into a File

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#333]
Usecase: passing the runtime configuration to a tool via a json File

**Comment by jmchilton** [comment]
We've found this useful in Galaxy-land (xref https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-configfiles-inputs) so this is probably a good idea. I'd just encourage moderation on the part of tool authors however :).

**Comment by StarvingMarvin** [comment]
What's the difference between this and and job.json file? I'm not completely sure I understand what is this about?

**Comment by mr-c** [comment]
@StarvingMarvin An input job document describes the inputs to running a CWL process; this is to transform any CWL object into a file fed to a command line tool. It is the flip side to the `cwl.output.json` feature -- it allows CWL aware tools to parse complex *inputs*

**Comment by pgrosu** [comment]
@mr-c But you have the [SchemaDefinedType](https://github.com/common-workflow-language/common-workflow-language/blob/e831c206023e611e462146580fc8a0f07186167f/v1.0/salad/schema_salad/metaschema/metaschema.yml#L206-L225), which gets implemented by the [SaladRecordSchema](https://github.com/common-workflow-language/common-workflow-language/blob/e831c206023e611e462146580fc8a0f07186167f/v1.0/salad/schema_salad/metaschema/metaschema.yml#L242-L277) for this.  Am I not correct?

**Comment by mr-c** [comment]
This should be possible now, but due to a [bug in cwltool](https://github.com/common-workflow-language/cwltool/issues/242) I can't test it yet:

``` yaml
class: CommandLineTool
cwlVersion: v1.0
baseCommand: [ls, -l]
requirements:
  InitialWorkDirRequirement:
    listing:
      - entryname: fancy-input.json
        entry: $(inputs.fancy)
inputs:
  fancy:
    type:
      type: record
      fields:
        - name: one
          type: string
        - name: two
          type: int
        
outputs:
  outfile:
    type: File
    outputBinding:
      glob: fancy-input.json
```

**Comment by StarvingMarvin** [comment]
@mr-c OK, so this is a feature that got lost in mists of pre draft-2 times, but I thought it's still part of the spec. My proposal would just be to always write job.json into app's temp dir.

**Comment by mr-c** [comment]
@StarvingMarvin Yeah, we had agreed this was a good idea prior, but it got lost :-P

I like the simplicity of `job.json` but it might be the wrong default to always have a file present in the current working directory..

I think we are talking about two features: an easy way to communicate the entire input object, and how to do so for a subset.

For the entire object I suggest we add a `CWL_INPUT_OBJECT` environment entry with the path to the input object JSON serialization. Optionally this can be written to the working directory using the existing method (I think `inputs.json` might be a better name):

``` yaml
requirements:
  InitialWorkDirRequirement:
    listing:
      - entryname: inputs.json
        entry: $(inputs)
```

For the subset we can fix the reference implementation (and add a conformance test) so that the existing method works. As we get more usage we can return and tighten the design (if needed).

**Comment by mr-c** [comment]
Good news, I was wrong: you can [apply this workaround today](https://github.com/common-workflow-language/cwltool/issues/242#issuecomment-283966762)

**Comment by mr-c** [comment]
@ThomasHickman Interesting! Does that work with any runner besides `cwltool`? I'm not sure the spec is explicit that this is part of CWL v1.0

**Comment by dshepelev15** [comment]
Hi!
Can you explain me about InitialWorkDirRequirement? Can I put some files/shell scripts in the folder where cwl script will be executed without putting them into input parameters?

```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool
baseCommand: ["sh", "script.sh"]
requirements:
 - class: InitialWorkDirRequirement
   listing:
    - entryname: script.sh
inputs:
  message:
    type: string
    inputBinding:
      position: 1
outputs: []
```
