### ISSUE TITLE
valueFrom boolean input

### ISSUE THREAD

**Issue by karl616** [common-workflow-language/common-workflow-language#345]
Hi,

I needed to use valueFrom to fix a boolean input of a workflow step. Is it correct that you have to resort to a javascript expression for this?

```
steps:
- id: step1
  run: tool.yml
  in:
  - id: booleanParameter
    valueFrom: $( true )
```

Part of the problem is that the tool has a default value for this setting, which seems to take precedence over a default value set in the workflow.

Two things:

 1. Would it make sense to have true to be recognized as a boolean if the parameter have type: Boolean?
 2. I would prefer that the default value "closest" to the user is used (closest <- main workflow <- sub-workflow <- tool definition). I never tested this and if I misunderstood it, please excuse my ignorance.

**Comment by mr-c** [comment]
Hello @karl616 

You've found a bug in the specification -- the type for the `valueFrom` field should be `CWLType`, `Expression` -- thanks!

I also agree that workflow default values should override tool default values. If you construct an example I'll turn that into a conformance test we can use to fix the implementations.

**Comment by karl616** [comment]
Hi @mr-c 

happy to be able to help.

I set up a small example. It is not complete, but only tests tool vs (sub-) workflow and sub-workflow vs master-workflow

defaultBehaviour.yml:
```
cwlVersion: "v1.0"

class: Workflow

requirements:
- class: SubworkflowFeatureRequirement

inputs:
- id: missedMessage
  type: string

outputs:
- id: output
  type: File
  outputSource: "#echo/output"

steps:
- id: echo
  run: defaultBehaviourSub.yml
  in:
  - id: message2
    default: ", but there is only one master workflow"
  out:
  - id: output
```

defaultBehaviour_input.yml:
```
missedMessage: "Forgotten"
```

defaultBehaviourSub.yml:
```
cwlVersion: "v1.0"

class: Workflow

inputs:
- id: message2
  default: "and subWorkflows are the real deal"
  type: string

outputs:
- id: output
  type: File
  outputSource: "#echo/output"

steps:

- id: echo
  run: "echo.yml"
  in:
  - id: message1
    default: "Workflows are cooler"
  - id: message2
    source: "#message2"
  out:
  - id: output
```
echo.yml:
```
cwlVersion: "v1.0"

class: CommandLineTool

stdout: output.txt

baseCommand: echo

inputs:

- id: message1
  type: string
  default: "Tools rules!"
  inputBinding:
    position: 1

- id: message2
  type: string
  inputBinding:
    position: 2

outputs:

- id: output
  type: stdout
```

With cwltool (v1.0.20161110155008) output.txt contains:
```
Tools rules! and subWorkflows are the real deal
```

As a side-note; I wasn't allowed to upload a zip file although github states that it supports it. (yml-files were directly banned)

**Comment by mr-c** [comment]
FYI, we fixed the bug in the reference runner where tool level defaults overwrote workflow step level defaults, so the correct fix is to use a workflow step level default:

```
steps:
- id: step1
  run: tool.yml
  in:
  - id: booleanParameter
    default: true
```
