### ISSUE TITLE
Source string should be structured data

### ISSUE THREAD

**Issue by dionjwa** [common-workflow-language/common-workflow-language#352]
Problem:

Example cwl step
```
  - id: finalize
    run: clean_and_convert.cwl
    inputs:
      - id: mdtfile
        source: "#read_file/mol"
    outputs:
      - id: pdbfile
```

The `source` field is a string, yet contains structured data. You start with a structured document, able to be parsed by any YAML parser, but then you have to parse and process the `"#read_file/mol"` string. This is not a good design, since strings should not contain internal structured data. If they are, they should be broken out into YAML/JSON structures, e.g. 

```
  source:
    step: "read_file"
    out: "mol"
```

Strings containing structured data means that every CWL parser implementation might contain parser errors, since the format of the string prevents `#` characters, and '/' characters in certain places. That's a lot of logic and potential errors, and requirements for extra documentation to describe this very special format when a proper data structure is almost self documenting and immune to implementation specific parsing errors.
