### ISSUE TITLE
Staging into output directory doesn't work properly

### ISSUE THREAD

**Issue by michael-kotliar** [common-workflow-language/common-workflow-language#357]
Hey!
It looks like I can't return any file that was staged into output directory.

This is how I tested it:
1. Create empty input file
`touch ./data/Hello1.txt`
2. Run cwl in a current folder
`cwl-runner --debug stage_input.cwl job.json`, which should
   - stage `Hello1.txt` into output directory
   - copy `Hello1.txt` into `Hello2.txt`
   - return `Hello1.txt` and `Hello2.txt`

The only result that I received was `Hello2.txt`.

Link to github 
https://github.com/michael-kotliar/cwl_sandbox/tree/master/stage_input

stage_input.cwl

``` yaml
cwlVersion: v1.0
class: CommandLineTool
hints:
  DockerRequirement:
    dockerPull: ubuntu
baseCommand: cp

requirements:
  - class: InlineJavascriptRequirement
  - class: InitialWorkDirRequirement
    listing:
      - $(inputs.src)

inputs:
  src:
    type: File
    inputBinding:
      position: 1
      valueFrom: $(self.basename)

  target:
    type: string
    inputBinding:
      position: 2

outputs:
  out_src:
    type: File
    outputBinding:
      glob: "Hello1.txt"
  out_target:
    type: File
    outputBinding:
      glob: "Hello2.txt"
```

job.json

``` json
{
  "src": {
    "class": "File",
    "path": "./data/Hello1.txt"
  },

  "target": "Hello2.txt"
}
```
