### ISSUE TITLE
/tmp/tmpXXX directory created 

### ISSUE THREAD

**Issue by Joon-JL** [common-workflow-language/common-workflow-language#372]
When I run any CWL, the output directory is generated /tmp/tmpXXXXX
```
$ /homes/joonlee/.local/bin/cwl-runner 1st-tool.cwl 1st-tool.yml
/homes/joonlee/.local/bin/cwl-runner 1.0.20161020211257
[job 1st-tool.cwl] **/tmp/tmpd2m_dX**$ echo \
    'Hello CWL!'
Hello CWL!
Final process status is success
{}
```
As you can see, /tmp/tmpd2m_dX is created.

**How can I set the output directory or the current directory, simply.**  
In the same reason, 
as the below cwl is generating some output files, which are generated by Clustal Omega, in the temp directory, so I have difficulty with the output files to get or pass to the next pipeline. 

```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: [/homes/workflow-example/tools/clustalo_soaplite.pl ]

inputs:
  param_1: 
    type: File
    inputBinding:
      position: 1
      prefix: --seqfile
  param_2: 
    type: string
    inputBinding:
      position: 2
      prefix: --email

outputs: []
```
Results;
```
$ /homes/.local/bin/cwl-runner 2nd-work.cwl 2nd-work.yml
/homes/.local/bin/cwl-runner 1.0.20161020211257
[job 2nd-work.cwl] **/tmp/tmpmPW6I_**$ /homes/workflow-example/tools/clustalo_soaplite.pl \
    --seqfile \
    /tmp/tmp3v2wLN/stg616d1022-b35f-459f-82b2-5ea66d837b61/comega_all.input \
    --email \
    'email@gmail.com'
Unknown option: seqfile
JobId: clustalo-S20170117-120810-0313-97773044-oy
FINISHED
Creating result file: clustalo-S20170117-120810-0313-97773044-oy.out.txt
Creating result file: clustalo-S20170117-120810-0313-97773044-oy.error.txt
Creating result file: clustalo-S20170117-120810-0313-97773044-oy.sequence.txt
Creating result file: clustalo-S20170117-120810-0313-97773044-oy.aln-clustal.clustal
```
All they're stored in `**/tmp/tmpmPW6I_**`
