### ISSUE TITLE
Expressions in default filed

### ISSUE THREAD

**Issue by AleksandrSl** [common-workflow-language/common-workflow-language#377]
Is there a reason why expressions are not processed in default field? 
e.g. If I don't specify output_file_name it will be inferred from input_name
```
output_file_name:
    type: string
    inputBinding:
      position: 1
      prefix: -o
    default: $("trimmed" + inputs.sorted_aligned_reads_w_index.basename)
```

**Comment by StarvingMarvin** [comment]
That's a good question. You can get desired behavior by using `valueFrom`:

```yaml
output_file_name:
    type: string
    inputBinding:
      position: 1
      prefix: -o
    valueFrom: | $(
       output_file_name? output_file_name:
       "trimmed" + inputs.sorted_aligned_reads_w_index.basename
    )
```

(haven't tried this snippet, so sorry if I messed something syntactically)

I guess answer to your question would be that focus for v1 was making sure that important things are possible, but there are ways for making them more ergonomic.

**Comment by AleksandrSl** [comment]
I've tried it different ways and even if cwl-runner accepts cwl file and runs it, there is an error samtools_sort.cwl:44:3: Missing required input parameter `output_file_name`. 
I came with this solution in the end and it seems to work: 
```
output_file_name:  # Moved to arguments
    type: string
    inputBinding:
      position: 1
      prefix: -o
      valueFrom: |
        $(self? self : "trimmed_" + inputs.sorted_aligned_reads_w_index.basename)
    default: ""
```
Thanks for the answer! Somehow it is hard to understand that such simple things will work in cwl)
