### ISSUE TITLE
Type mismatch when using enum in workflow

### ISSUE THREAD

**Issue by michael-kotliar** [common-workflow-language/common-workflow-language#379]
Hi all!
Found `Type mismatch between source and sink` when trying to pass enum from workflow to task. Commented line in a workflow below causes a problem. My solution to bypass an error is to use source and valueFrom fields. 

**workflow.cwl**
```yaml
class: Workflow
cwlVersion: v1.0

requirements:
  - class: StepInputExpressionRequirement

inputs:

  enum_workflow_input:
    type:
      name: "foo"
      type: enum
      symbols: ["a","b","c"]

outputs: []

steps:
  task:
    in:
      #enum_task_input: enum_workflow_input  # DOESN'T WORK
      enum_task_input:
        source: enum_workflow_input
        valueFrom: $(self)
    out: []
    run: task.cwl
```
**task.cwl**
```yaml
class: CommandLineTool
cwlVersion: v1.0
inputs:

  enum_task_input:
    type:
      name: "foo"
      type: enum
      symbols: ["a","b","c"]

outputs: []

arguments: [echo, $(inputs.enum_task_input) ]
```
**job.json**
```json
{
  "enum_workflow_input": "b"
}
```
