### ISSUE TITLE
allow multiple parameter references and string concatenation w/o JS engine

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#389]
Inspired by https://www.biostars.org/p/234804/#238901

Implementers, does the following seem reasonable?
Note the lack of `InlineJavascriptRequirement`
```
cwlVersion: v1.0
class: Workflow
requirements:
   ScatterFeatureRequirement: {}
   StepInputExpressionRequirement: {}
inputs:
   bam: File
   intervals: string[]
outputs: []
steps:
  hc:
    run: dummy_HC.cwl
    scatter: [interval_string]
    in:
      inputBam: bam
      interval_string: intervals
      outputVcf:
        valueFrom: $(inputs.inputBam.nameroot).$(inputs.interval_string).vcf
```
