### ISSUE TITLE
easy nested input parameters for Workflows

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#390]
One common CWL modality is to treat workflows as fairly opaque objects, converting carefully named workflow level inputs into the forms and names needed by the underlying tools. CWL 1.0 makes this fairly easy

Another common CWL modality is to wire the steps together and expose all the parameters for tweaking, but this becomes tedious with lots of verbose input names.

Inspired by [a conversation](https://gitter.im/common-workflow-language/common-workflow-language?at=58b32963f1a33b627551d31b) with @cnjr2 I would like us to think about the following:

If Workflow level inputs are inferred from the underlying steps: #86 (possibly recursively) then they could be exposed not using a flat namespace, but a nested one:

```
build_reference:
  download_reference:
    release: '128'
  trim_forward:
    forward_primer: ['AAAACCATCGTGCGCCCGTATCT']
    discard_untrimmed: true
    minimum_length: 32
    overlap: 15
    adaptor_error_rate: 0.25
  trim_reverse:
    reverse_primer: ['TATATTAGCCGCTATATCGGATC']
    discard_untrimmed: true
    minimum_length: 32
    overlap: 15
    adaptor_error_rate: 0.25
```
(Example courtesy of @cnjr2)

Thoughts?

This could be implemented using a `NestedInputsRequirement` (or other suitable name) but then converted to pure CWL v1.0 for execution.

**Comment by StarvingMarvin** [comment]
So semantically, it would be as if workflow has an input of a type record for each step, and than inputs of each step are connected to appropriate record + field?

**Comment by mr-c** [comment]
@StarvingMarvin Yep! Or the names could be flattened; many processing options available

**Comment by cnjr2** [comment]
Perhaps it would be useful to see the situation that I am facing in more detail.

In order not to get the parameters mixed up, I name them according to the steps that they are involved in. This becomes cumbersome with multiple nested workflows. Perhaps I am not using `cwl` as intended; at least is is much less neat than the power workflow from [h3abionet16S](https://github.com/h3abionet/h3abionet16S) :)


This is the workflow hierarchy:
```
main.cwl
|__build_references.cwl
  |__silva_reference.cwl
  |__greengenes_reference.cwl
```

This would be my `main-job.cwl` file:

```yaml
build_references.silva_reference.download_silva_reference.silva_release: '128'
build_references.silva_reference.trim_forward.forward_primer: ['AGTGYCAGCMGCCGCGGTAA']
build_references.silva_reference.trim_forward.discard_untrimmed: true
build_references.silva_reference.trim_forward.minimum_length: 32
build_references.silva_reference.trim_forward.overlap: 15
build_references.silva_reference.trim_forward.adaptor_error_rate: 0.25
build_references.silva_reference.trim_reverse.reverse_primer: ['ATTAGAWACCCBDGTAGTCC']
build_references.silva_reference.trim_reverse.discard_untrimmed: true
build_references.silva_reference.trim_reverse.minimum_length: 32
build_references.silva_reference.trim_reverse.overlap: 15
build_references.silva_reference.trim_reverse.adaptor_error_rate: 0.25
build_references.greengenes_reference.download_greengenes.greengenes_release: '1.2'
```

Here would be the a part of the `main.cwl`

```yaml
inputs:

  build_references.silva_reference.download_silva_reference.silva_release: string
  build_references.silva_reference.trim_forward.forward_primer: string[]
  build_references.silva_reference.trim_forward.discard_untrimmed: boolean
  build_references.silva_reference.trim_forward.minimum_length: int
  build_references.silva_reference.trim_forward.overlap: int
  build_references.silva_reference.trim_forward.adaptor_error_rate: double
  build_references.silva_reference.trim_reverse.reverse_primer: string[]
  build_references.silva_reference.trim_reverse.discard_untrimmed: boolean
  build_references.silva_reference.trim_reverse.minimum_length: int
  build_references.silva_reference.trim_reverse.overlap: int
  build_references.silva_reference.trim_reverse.adaptor_error_rate: double


steps:

  build_references:
    run: build_references.cwl
    in:
      silva_reference.download_silva_reference.silva_release: build_references.silva_reference.download_silva_reference.silva_release
      silva_reference.trim_forward.forward_primer: build_references.silva_reference.trim_forward.forward_primer
      silva_reference.trim_forward.discard_untrimmed: build_references.silva_reference.trim_forward.discard_untrimmed
      silva_reference.trim_forward.minimum_length: build_references.silva_reference.trim_forward.minimum_length
      silva_reference.trim_forward.overlap: build_references.silva_reference.trim_forward.overlap
      silva_reference.trim_forward.adaptor_error_rate: build_references.silva_reference.trim_forward.adaptor_error_rate
      silva_reference.trim_reverse.reverse_primer: build_references.silva_reference.trim_reverse.reverse_primer
      silva_reference.trim_reverse.discard_untrimmed: build_references.silva_reference.trim_reverse.discard_untrimmed
      silva_reference.trim_reverse.minimum_length: build_references.silva_reference.trim_reverse.minimum_length
      silva_reference.trim_reverse.overlap: build_references.silva_reference.trim_reverse.overlap
      silva_reference.trim_reverse.adaptor_error_rate: build_references.silva_reference.trim_reverse.adaptor_error_rate
      greengenes_reference.download_greengenes.greengenes_release: build_references.greengenes_reference.download_greengenes.greengenes_release
    out: [taxonomy_db, taxconfs]

...
```

Then in `build_references.cwl`

```yaml
inputs:

  silva_reference.download_silva_reference.silva_release: string
  silva_reference.trim_forward.forward_primer: string[]
  silva_reference.trim_forward.discard_untrimmed: boolean
  silva_reference.trim_forward.minimum_length: int
  silva_reference.trim_forward.overlap: int
  silva_reference.trim_forward.adaptor_error_rate: double
  silva_reference.trim_reverse.reverse_primer: string[]
  silva_reference.trim_reverse.discard_untrimmed: boolean
  silva_reference.trim_reverse.minimum_length: int
  silva_reference.trim_reverse.overlap: int
  silva_reference.trim_reverse.adaptor_error_rate: double


steps:

silva_reference:
  run: silva_reference.cwl
  in:
    download_silva_reference.silva_release: silva_reference.download_silva_reference.silva_release
    trim_forward.forward_primer: silva_reference.trim_forward.forward_primer
    trim_forward.discard_untrimmed: silva_reference.trim_forward.discard_untrimmed
    trim_forward.minimum_length: silva_reference.trim_forward.minimum_length
    trim_forward.overlap: silva_reference.trim_forward.overlap
    trim_forward.adaptor_error_rate: silva_reference.trim_forward.adaptor_error_rate
    trim_reverse.reverse_primer: silva_reference.trim_reverse.reverse_primer
    trim_reverse.discard_untrimmed: silva_reference.trim_reverse.discard_untrimmed
    trim_reverse.minimum_length: silva_reference.trim_reverse.minimum_length
    trim_reverse.overlap: silva_reference.trim_reverse.overlap
    trim_reverse.adaptor_error_rate: silva_reference.trim_reverse.adaptor_error_rate
  out: [silva_db]

...
```

And finally the lowest level at the `silva_reference.cwl` subworkflow.

```yaml
inputs:

  download_silva_reference.silva_release: string
  trim_forward.forward_primer: string[]
  trim_forward.discard_untrimmed: boolean
  trim_forward.minimum_length: int
  trim_forward.overlap: int
  trim_forward.adaptor_error_rate: double
  trim_reverse.reverse_primer: string[]
  trim_reverse.discard_untrimmed: boolean
  trim_reverse.minimum_length: int
  trim_reverse.overlap: int
  trim_reverse.adaptor_error_rate: double


steps:

  download_silva_reference:
    run: ../tools/download_silva_reference.cwl
    in:
      release: download_silva_reference.silva_release
    out: [silva]

```
