### ISSUE TITLE
Encode some features as Requirements

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#40]
To keep the core spec simple, we can encode certain features as Requirements. For example, instead of specifying defined schemas, files and env vars through top-level properties, they can be encoded as:

```yaml
requirements:
  - class: SchemaDefRequirement
    types: [{"type": "record", "name": "MyType", "fields": []}]
  - class: EnvVarsRequirement
    vars: [{"key": "SOME_VAR": "value": "string or expression"}]
  - class: CreateFileRequirement
    fileName: "script.sh"
    fileContent: "./something $@"
```
