### ISSUE TITLE
Undefined (and slightly inconsistent) behavior: cli for empty list argument

### ISSUE THREAD

**Issue by StarvingMarvin** [common-workflow-language/common-workflow-language#442]
Example tool:

```yaml
#!/usr/bin/env cwl-runner

cwlVersion: v1.1.0-dev1

class: CommandLineTool

hints:
  - class: ResourceRequirement
    coresMin: 4
  - class: DockerRequirement
    dockerPull: python:2-slim

inputs:
  - id: min_std_max_min
    type: { type: array, items: int }
    inputBinding:
      position: 1
      prefix: -I
      itemSeparator: ","

  - id: args.py
    type: File
    default:
      class: File
      location: args.py
    inputBinding:
      position: -1

outputs:
  - id: args
    type:
      type: array
      items: string

baseCommand: python

```

inputs:

```json
{
    "min_std_max_min": []
}
```

cwltool result:

```json
{
    "args": [
        "-I", 
        ""
    ]
}
```

rabix result:

```json
{
  "args" : [ "-I" ]
}
```
