### ISSUE TITLE
proposal for "splittable" feature

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#446]
Proposed syntax via example: `InterProScan.cwl`:
``` yaml
cwlVersion: v1.0
# this feature is backwards compatible, can be implemented via Polyfill for vanilla v1.0
class: CommandLineTool

hints:
  Splittable:
    proteins:  # the name of the input that is splittable, repeat for each splittable input
      splitter: fasta_chunker.cwl  # relative path or public HTTP[S] IRI
      combiner:  concatenate.cwl  # relative path or public HTTP[S] IRI
      default: 10000  # default maximum units (records, fields, characters, etc.) per shard

inputs:
  proteins: File  # most likely a file, but could be a complex data type too
# …
```
Example splitter:
``` yaml
cwlVersion: v1.0
class: CommandLineTool  # or any other type of Process (Workflow, ExpressionTool)

inputs:
  input: File  # always named input
  threshold: int  # always named threshold

outputs:
  shards: File[] # always of type T[] where T is the type of the input, always named shards
# …
```
Example combiner:
``` yaml
cwlVersion: v1.0
class: CommandLineTool  # or any other type of Process (Workflow, ExpressionTool)

inputs:
  shards: File[] # always of type T[] where T is the type of the output, always named shards

outputs:
  combined: File  # always named combined
# …
```
Proposed specification for overrides in user input object (other out of band configuration would also be acceptable)
``` yaml
cwl:tool: InterProScan.cwl  # optional
cwl:split_overrides: 
    proteins:  5000  # overriding the default threshold
```
``` yaml
cwl:tool: a_big_workflow.cwl
cwl:split_overrides:
  functional_analysis:   # this step in a_big_workflow.cwl runs InterProScan.cwl
    proteins:
      splitter: my_better_splitter.cwl  # overriding the splitter
```

Questions for all:
- [ ] better name suggestions for any part of the new syntax: `Splittable`, `splitter`, `combiner`, `default`, `input`, `threshold`, `shards`, `combined`, `cwl:split_overrides`
- [ ] should we also allow mapping of the fixed input & output names for the splitter & combiner to any name? This would support reuse of existing CWL descriptions at the cost of some complexity

**Comment by mr-c** [comment]
[added an introduction in response to a useful question from @psafont, made explicit the order of combining in response to a query from @stain]

**Comment by stain** [comment]
It's a nice proposal, particularly as the splitter and combiner can be arbitrary CWL tools (with certain fixed inputs/outputs).

I think we can support multiple outputs by having `Combinable` as a separate section.

I don't think it makes sense to have `default: 10000` per port, as the number needs to be the same (or some kind of multiple) across all split inputs. Also `default` is confusing..

```yaml
hints:
  Splittable:
    split:
      # the name of the input that is splittable, repeat for each splittable input
      proteins:  fasta_chunker.cwl 
    at: 10000
  Combinable:
    combine:
      # the name of the output to combine, repeat for each combinable output
      alignments:  concatenate.cwl
      reports:  concatenate.cwl
    order: any
```

Here the ports are listed under `split`, with other `Splittable` options neighbouring. `default` changed to `at` - here the threshold needs to be the same for all inputs.

I'm not suggesting to add `order: any` now (e.g. allowing combination in any order), but having also `Combinable`'s port listing a level down allow you to add such options later.
