### ISSUE TITLE
Add possibility to reference all workflow inputs in step expressions

### ISSUE THREAD

**Issue by hcraT** [common-workflow-language/common-workflow-language#449]
**Problem**: only the workflow inputs that are passed down to a step are accessible from the expressions. For example:
```yaml
#!/usr/bin/env cwl-runner

cwlVersion: v1.0

class: Workflow

requirements:
  - class: InlineJavascriptRequirement
  - class: StepInputExpressionRequirement

inputs:
  a: string
  b: string?

steps:
  step1:
    run: step1.cwl
    in:
      parm1:
        valueFrom: $( b != null ? b : a )
      parm2:
        valueFrom: $( inputs.b != null ? inputs.b : inputs.a )
```
If I tried to run this I would get a reference error for `parm1` and an undefined value for `parm2`.
In order to be able to access such parameters I would need to add them as parameters for the step like:
```json
...
  step1:
    ...
      a:
        source: a
      b:
        source: b
```
In this case `parm2` would get correctly valued. The problem is that parameters `a` and `b` are added to the step just to be able to evaluate the expression and are not needed by the step.

**Solution**: allow step expressions to refer to the top-level inputs of the workflow.

This was acknowledged and discussed on gitter [here](https://gitter.im/common-workflow-language/common-workflow-language?at=592ee572fcbbe1891c62afff).

**Comment by mr-c** [comment]
For the given example I think the following might work without artificial inputs added to `step1.cwl`:
```
requirements:
  InlineJavascriptRequirement: {}
  StepInputExpressionRequirement: {}
  MultipleInputFeatureRequirement: {}

# […]

steps:
  step1:
    run: step1.cwl
    in:
      parm1:
        source: [a, b]
        valueFrom: $( self[1] != null ? self[1] : self[0] )
```
