### ISSUE TITLE
Expressions in dockerPull DockerRequirement

### ISSUE THREAD

**Issue by bosonogi** [common-workflow-language/common-workflow-language#476]
The scenario that is relevant to me here is when one of the inputs is which version of the wrapped tool to use; and I would like to be able to map that version to a docker image tag in a DockerRequirement using an expression.

Are there any reasons why changing the dockerPull value type from `string` to `string | Expression` would be a bad idea?

**Comment by mr-c** [comment]
Personally I don't think a version should be an input as a violation of the "seperate of concerns" that we aim for.

Does `SoftwareRequirement` and it's explicit listing of versions meet your needs? The reference implementation of the CWL standards now can use this to select an appropriate container, see https://github.com/common-workflow-language/cwltool/blob/master/README.rst#leveraging-softwarerequirements-beta

Other implementations are likely to also leverage this requirement. I know that support for Toil is in progress.

**Comment by mr-c** [comment]
For your scenario, a user could specify/override with their own `DockerRequirement` (or `SoftwareRequirement`) at the workflow step or input object levels.

**Comment by mr-c** [comment]
If these are acceptable solutions then I would suggest that allowing an `Expression` here is indeed a bad idea as it encourages the seperate of concerns violation I mentioned and there are better ways to model the intent and get the desired behavior. If not, or if other compelling use cases emerge, then I would be open to re-examining the proposal.

**Comment by bosonogi** [comment]
@mr-c Thanks for the prompt response.

`SoftwareRequirement` doesn't solve my problem of separating out which version of a docker image to pull. What I want to avoid is the need to have a separate CWL document for every version (of which many can be generated daily) that will be used for jobs of a particular type; as in my case everything apart from the tag would be the same.

As things stand now, the only way to accomplish this would be to use CWL document templates with a preprocessor -- something which seams ugly bolted on to the otherwise highly flexible CWL.

The concerns you are wishing to separate in excluding a version value from inputs are IMHO valid when different versions can mean different interfaces. This is not always the case; and when it's not, an explicit version to use can meaningful as an input.

There are plenty of ways for shooting oneself in the foot with any language; separation of concerns and other good practices are probably impossible to enforce on the language level. For example `dockerPull` being a string doesn't prevent people from using the "latest" tag (or some other tag that is overwritten) and defeating the whole purpose of that value being static for reproducibility.

**Comment by mr-c** [comment]
Hey @bosonogi 

I think I didn't explain the `DockerRequirement` override feature very well.

Start with `my_tool.cwl`:
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool
hints:
  DockerRequirement:
    dockerPull: my-stuff/my-tool:stable_version
inputs: []
baseCommand: []
outputs: []
```

when you invoke that in a workflow you can provide your own `requirements` that override any conflicting `hints` or `requirements` inside the tool description.

my_workflow.cwl
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: Workflow
inputs: []

steps:
  my_step:
    run: my_tool.cwl
    requirements:
      DockerRequirement:
        dockerPull: my-stuff/my-tool:dev_version  # note the different version
    in: { } 
    out: [ ]

outputs: []
```

Would that solve your specific issue?
