### ISSUE TITLE
Proposal for loops in v1.1 

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#495]
Design sketch for loops.

The distinction between loops and scatter is that loops are explicitly sequential, whereas scatter is a parallel operation.

A looping step consists of a `while` condition and a `loop` specification.  The `loop` specification describes how to update the input object for the next iteration.  The output of the step defaults to the output of the last iteration, but could also be constructed using the `result` field describe in #494 .

```
  step3:
    in:
      a: a
    out: [out]
    while: $(self.a < 5)
    run: blah.cwl
    loop:
      a: $(self.a + 1)
```

**Comment by mr-c** [comment]
Gathering some real world workflows that use looping, for inspiration:

1. https://www.myexperiment.org/groups/643/workflows
2. https://pubmed.ncbi.nlm.nih.gov/26335531-scientific-workflow-optimization-for-improved-peptide-and-protein-identification/ 
3. https://pubmed.ncbi.nlm.nih.gov/22411703-scientific-workflow-management-in-proteomics

**Comment by lukasheinrich** [comment]
our REANA example has this requirement

https://awesome-workshop.github.io/reproducible-analyses/07-higgstotautau-parallel/index.html

**Comment by mr-c** [comment]
Thanks @lukasheinrich , which bit is the loop? Is it "do the same thing to each of these inputs" or is it "run this part until a condition is met"?

**Comment by Karel-van-de-Plassche** [comment]
We are looking at workflow engines for a possible project. This would be a prerequisite for our usecase (e.g. time-loops, optimization, etc.).

@daanvanvugt @nielsdrost

**Comment by mr-c** [comment]
Hello @Karel-van-de-Plassche ! Do you need loops within the workflow (repeat these steps, folding their outputs into their inputs) or loops over entire workflow (run this simulation workflow until the critical threshold is met)?

**Comment by mr-c** [comment]
To @lukasheinrich @tiborsimko @clelange @Karel-van-de-Plassche @DaanVanVugt @nielsdrost : the point of my questions is to better understand both where loops are desired and what types of operations between iterations are needed.

I can imagine many different types of scenarios, but we should design for specific and not theoretical needs. If incrementing a counter is sufficient, then @tetron design is good enough. If the outputs of one round of the loop need to become inputs, perhaps with a complicated transformation, then I'm not sure the current design is sufficient.

There could be other considerations based on real, specific use cases. But we don't have those use cases to study, which makes it difficult to sketch how these loops would work.

However, do not despair! The loop construct would be a small percentage of a typical scientific/research workflow. The easiest way to advance this proposal would be to implement @tetron 's design as an extension to CWL v1.2 in a fork of [the CWL reference runner](https://github.com/common-workflow-language/cwltool). This would give us a lot of experience in what works and what does not.

That extension could look like:

``` cwl
  step3:
    in:
      a: a
    out: [out]
    run: blah.cwl
    requirements:
      cwltool:Loop:
        while: $(self.a < 5)
        loop:
          a: $(self.a + 1)
```

I (@mr-c) and others would help you implement and test such an extension, but I can't do it alone :-)

**Comment by mr-c** [comment]
An open question is how to incorporate the results of the previous iteration in the next round.

One approach using the current proposal: the references to the previous iteration's results could occur in the `loop` CWL Expression using a new `out` or `result` object.

**Comment by tetron** [comment]
That's what the `loop` field is intended to do, it defines the input object of the next iteration, with the ability to reference the input and output objects of the last iteration.

I realize that's not totally clear in the original proposal, here's a revised one, this feeds the value of "out" back into "b":

```
  step3:
    in:
      a: a
      b: b
    out: [out]
    while: $(self.a < 5)
    run: blah.cwl
    loop:
      a: $(inputs.a + 1)
      b: $(outputs.out)
```

**Comment by tetron** [comment]
Thank you for this very thoughtful proposal!

> use `when` for loops

I agree with this

> `LoopInput` based on `WorkflowStepInput` 

The version I proposed was basically only `valueFrom` but I see value in making it behave like the `inputs` section.  One detail, you probably want qualify the source with the step name (the same as if you had a 2nd step consuming the output).

```
optimization:
  in:
      a: a
      threshold: threshold
    when: $(outputs.error > inputs.threshold)
    run: optimize.cwl
    out: [value, error]
    loop:
      a: optimization/value
    outputMethod: last
```

> `last` and `all_concat` output mode

These both makes sense.  `all_concat` would be like a serial version of scatter.

> `all_propagate`

This I have concerns about.  It has significant implications for the current CWL model of computation.  There's certainly value in being able to being able to start computation of downstream steps before all iterations/instances of a loop or scatter step has completed, but I think we should try to address that as a separate proposal.

**Comment by GlassOfWhiskey** [comment]
Few comments here:

> Removing the `all_propagate` output mode

This is not a big problem, as the `all_propagate` is basically an optimization path for `all_concat` -> `scatter`. We can then allow only two values for the `outputMethod` field: the `last` value, which behaves as described above, and the `all` value, which behaves as `all_concat`. Then the possibility to apply optimization patterns to the `all` -> `scatter` combination is left to the WMS implementors, without forcing the behaviour in the standard.

> Qualify the `source` with the step name

I am a bit scared about that, as the next syntactical step here would be to specify outputs from other steps as `loop` inputs, while I strongly suggest to allow only outputs of the same step to be used in the `loop` field (users can still define subworkflows as I did in the Arbitrary Cycles example).

Allowing cross-step loops would be obviously more intuitive for users, but from an implementation point of view it would require huge changes in the way CWL processes dependencies, much more than the `all_propagate` case (I know because I tried several times to "simulate" loops in the current CWL implementation by injecting circular dependencies between steps, but with painful results XD).

**Comment by GlassOfWhiskey** [comment]
Plus, I would like to start a discussion about two remaining open points in the `loop` behaviour: `default` values and `scatter` behaviour.

## The `default` behaviour

Suppose a user defines a loop like this:

```
  step3:
    in:
      a: a
      b:
        source: b
        default: 3
    when: $(inputs.a < 5)
    run: blah.cwl
    out: [out]
    loop:
      a:
        valueFrom: $(inputs.a + 1)
      b: out
```

Suppose now that in a given iteration the `out` value is `null`. We have two options here:

 - Pass `3` to the next loop iteration, applying the `default` value to the output of the prevous iteration;
 - Pass `null` to the next loop iteration, applying the `default` value only to the first iteration of the loop;

In the second case, we will probably have to allow something like this to explicitly replicate the first behaviour:
```
  step3:
    in:
      a: a
      b:
        source: b
        default: 3
    when: $(inputs.a < 5)
    run: blah.cwl
    out: [out]
    loop:
      a:
        valueFrom: $(inputs.a + 1)
      b:
        source: out
        default: 3
```
Honestly I don't have specific use cases to prefer one solution to the other. The only thing I can think is that second option with the `default` keyword added to the `LoopInput` schema is more verbose but more flexible, as it can specify both behaviours. Conversely, with the first, more concise syntax I cannot have `default` values only in the first loop iteration.

## The `scatter` behaviour

The `loop` + `scatter` combination is maybe the most difficult scenario to deal with.

### Case 1: scatter over input variables

The first case is when the `scatter` directive does not involve variables coming from the step outputs. The idea here is to first scatter, then apply a loop on any combination of the input variables, and then gather on the loop outputs, **without applying the scatter over the intermediate values**. This means that the same variable will have different types in the `in` and `loop` contexts, but the latter type can be automatically inferred from the `scatter` scheme so this should not undermine the static validation of the workflow.

Here is an example with a `scatter` over a single variable, but the same reasoning applies whenever none of the involved variables comes from the step outputs.

```
  step3:
    in:
      a: a
      b: b
    when: $(inputs.a < 5)
    run: blah.cwl
    out: [out]
    scatter: a
    loop:
      a:
        valueFrom: $(inputs.a + 1)
      b: out
```

This is probably the most straightforward case. The `when` clause must be evaluated after the `scatter` operation, so if we have `a = [0, 1, 2]` we will start three different loops:

 - One iterating over `a = [0, 1, 2, 3, 4]`
 - One iterating over `a = [1, 2, 3, 4]`
 - One iterating over `a = [2, 3, 4]`

If the `outputMethod` is `last` we will have `{out: [4, 4, 4]}`, while if the `outputMethod` is `all` we will have `{out: [[0, 1, 2, 3, 4], [1, 2, 3, 4], [2, 3, 4]]}`.

The most delicate part here is that the `a` input will have type `int[]` in the `in` schema, while it will have type `int` in the `loop` schema. The type can be easily inferred by removing one level of `array`, but it is something that should be taken into account.

### Case 2: scatter over output variables

When the `scatter` involves at least one variable coming from step outputs, things are less straightforward. Consider this example:

```
  step3:
    in:
      a: a
      b: b
    when: $(inputs.a < 5)
    run: blah.cwl
    out: [out]
    scatter: b
    loop:
      a:
        valueFrom: $(inputs.a + 1)
      b: out
```

Assume the initial value of `b` is again an array `[0, 1, 2]`. Here we can do three things:

- Scatter only the first time, to be consistent with the previous behaviour. In this case everything works as soon as `out` is coherent with the `b` type in the `loop` context, i.e. if `out` is a single `int` value. If `out` is of type `int[]`, we cannot scatter over it. Nevertheless, this can be achieved with an external `loop` + internal `scatter` steps, introducing two level of subworkflows.
- Scatter every time. This behaviour allows to support nested `scatter` automatically, but it is not consistent with the previous behaviour and it is very counter-intuitive in my opinion, also because it should require a proper scatter combination between all the involved `loop` variables. It could be evaluated as an explicitly induced behaviour (e.g. by a specific flag), but cannot be the default.
- Forbid `loop` + `scatter` combination in the same step. This could make sense because both behaviours can be explicitly induced by the user with two level of nested subworkflows. An external `scatter` + internal `loop` will induce the first behaviour, while an external `loop` + internal `scatter` will induce the second one. Still, it sounds a bit artificial and forces user to put a lot of boilerplate code.

Again, I don't have use cases to force a specific solution. I would probably suggest the first approach by reasoning purely on code clarity and usability: it keeps the straightforward behaviour easy to read and implement, but the more complex behaviour can still be achieved with a more complex syntax:

```
  outer-loop:
    in:
      a: a
      b: b
    when: $(inputs.a < 5)
    run:
      class: Workflow
      inputs:
        a: Any
        b: Any[]
      outputs:
        out:
           type: Any[]
           outputSource: inner-scatter/out
      steps:
        inner-scatter:
          in:
            a: a
            b: b
          scatter: b
          run: blah.cwl
          out: [out]
    out: [out]
    loop:
      a:
        valueFrom: $(inputs.a + 1)
      b: out
```
