### ISSUE TITLE
Define behaviour of parsing references when some object has dot in id

### ISSUE THREAD

**Issue by d1skort** [common-workflow-language/common-workflow-language#501]
Ok, we have some schema: 

```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: [echo]
inputs:
  tarfile:
    type: File
    inputBinding:
      position: 1
  tarfile.path:
    type: string
    inputBinding:
      position: 2
outputs:
  example_out:
    type: File
    outputBinding:
      glob: _ $(inputs.tarfile.path)
```

and values file:

```
tarfile:
  class: File
  path: hello.tar
tarfile.path: goodbye.txt
```

What value will be in glob field? tarfile.path as input or path field in tarfile?

So, I have two questions:

1. What standard says about this situation? I've not found answer in documentation;
2. Is it correct situation? Because, we don't have access to the second input at all or field in first input;
