### ISSUE TITLE
Custom output path

### ISSUE THREAD

**Issue by d1skort** [common-workflow-language/common-workflow-language#504]
Hello, I can not understand how to set a custom output directory.

For example, I have the next schema bellow:

```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: [tar, xf]
inputs:
  tarfile:
    type: File
    inputBinding:
      position: 1
outputs:
  example_out:
    type: File
    outputBinding:
      glob: hello.txt
```

File hello.txt will be created in directory where we ran this job. But I want to specify custom output directory, for example `/home/user/pipelines/outputs/hello.txt`

Thanks!
