### ISSUE TITLE
Is array of dictionary allowed in `expressionLib`?

### ISSUE THREAD

**Issue by otiai10** [common-workflow-language/common-workflow-language#516]
Reading [this document](http://www.commonwl.org/v1.0/CommandLineTool.html#InlineJavascriptRequirement), `expressionLib` in `InlineJavascriptRequirement` is always `array<string>`.

On the other hand in [this example](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/template-tool.cwl#L6-L8), one of the `expressionLib` is described as dictionary, it means `array<string|object>`.

Which is correct? or am I wrong?

**Comment by mr-c** [comment]
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool
requirements:
  - class: InlineJavascriptRequirement
    expressionLib:
      - { $include: underscore.js }
```
@otiai10 Yeah, that is weird. I wonder if that works without the `{` …`}`?
