### ISSUE TITLE
Contradiction between descriptions for CommandInputParameter

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#518]
There exists an contradiction between the descriptions for CommandInputParameter in the document.

[Introduction section in Command Line Tool Description v1.0.2](http://www.commonwl.org/v1.0/CommandLineTool.html#Introduction_to_CWL_Command_Line_Tool_standard_v1.0.2) describes that the following notation for input arguments is allowed:

```yaml
inputs:
 one:
  type: string
  doc: First input parameter
 two:
  type: int
  doc: Second input parameter
```
and [examples in the repository](https://github.com/common-workflow-language/common-workflow-language/tree/master/v1.0/examples) use this notation.

However, [CommandInputParameter section](http://www.commonwl.org/v1.0/CommandLineTool.html#CommandInputParameter) says that `id` field is mandatory and the above notation should be rejected.

Which description is correct?

**Comment by mr-c** [comment]
Hello @tom-tan,

The ID field is still there in the name of the input.
At http://www.commonwl.org/v1.0/CommandLineTool.html#CommandLineTool `inputs` is defined as
```
 array<CommandInputParameter>  | map<CommandInputParameter.id, CommandInputParameter.type> | map<CommandInputParameter.id, CommandInputParameter>
```
Which means that both versions of the syntax are valid. The list with the explicit `id` or a dictionary mapping of the `id` value to the either the type or a full `CommandInputParameter` entry.

Sorry for the confusion!

**Comment by tom-tan** [comment]
Thank you for the reply.

I know both of the array and dictionary mapping are valid.
I mean that the definition of dictionary mapping says:

```
... | map<CommandInputParameter.id, CommandInputParameter>
```

and I expect the following syntax is valid because each value should be a complete `CommandInputParameter` in the definition:

```yaml
inputs:
  one:
    id: one
    type: string
    doc: First input parameter
  two:
    id: two
    type: string
    doc: Second input parameter
```

and also I expect that the following syntax is rejected because the definition does not say that `map<CommandInputParameter.id, CommandInputParameter-id>` (i.e. its value type does not contain `id` field) is accepted.

```yaml
inputs:
  one: # It lacks `id` field in the value!
    type: string
    doc: First input parameter
  two:
    type: string
    doc: Second input parameter
```

If the mapping can accept `CommandInputParameter` without `id` when we use `id` for keys, the definition should be revised to accept this notation.
