### ISSUE TITLE
References inside the defaults?

### ISSUE THREAD

**Issue by serge2016** [common-workflow-language/common-workflow-language#521]
Hello!
If I have understood the 1.0.2 specification correctly, then I can use something like this:
```
default: $(inputs.in_file).md5
```
But it doesn't work as expected! I think this is useful thing to have...

Schema:
```
class: CommandLineTool
cwlVersion: v1.0
id: md5sum-tool
doc: A tool to calculate md5
baseCommand: [bash, -c, "cd $HOME; md5sum $0 > $1"]
inputs:
- id: "#in_file"
  doc: Input file to calculate md5
  type:
  - File
  inputBinding:
    position: 1
- id: "#out_filename"
  doc: Output md5 sum filename
  type:
  - string
  inputBinding:
    position: 2
  default: $(inputs.in_file).md5
outputs:
- id: "#outfile"
  type:
  - File
  outputBinding:
    glob: $(inputs.out_filename)
requirements:
- class: DockerRequirement
  dockerPull: 1science/alpine
```
Values:
```
in_file:
  class: File
  path:  index.html
```

**Comment by tetron** [comment]
You can't do that, but you should be able to accomplish the same behavior with an expression:

```
- id: "#out_filename"
  doc: Output md5 sum filename
  type:
  - "null"
  - string
  inputBinding:
    position: 2
    valueFrom: ${if (self) { return self; } else { return inputs.in_file.basename+".md5"; } }
```
