### ISSUE TITLE
Map mode needs clarification via internal hyperlink

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#529]
In the [specification of CommandLineTool](http://www.commonwl.org/v1.0/CommandLineTool.html#CommandLineTool), `CommandInputParameter` is defined as follows:
```
... | map<CommandInputParameter.id, CommandInputParameter>
```
It means that each value in the map should be a complete `CommandInputParameter`.
(I skipped another mapping `map<CommandInputParameter.id, CommandInputParameter.type>` because it is not the case for this issue)

Also, the [specification of CommandInputParameter](http://www.commonwl.org/v1.0/CommandLineTool.html#CommandInputParameter) says that it should have a field named `id`.

However, some of the examples lacks the `id` field for `CommandInputParameter`.
For example, [1st-tool.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/examples/1st-tool.cwl) has the following `inputs` field:

```yaml
inputs:
  message:
    type: string
    inputBinding:
      position: 1
```

Here are possible ways to fix this issue but I'm not sure which is the correct way for that.

a. Fix the examples by adding `id` field:
```yaml
inputs:
  message:
    id: message # added to make a CommandInputParameter complete
    type: string
    inputBinding:
      position: 1
```

b. Fix the description as follows:
```
... | map<CommandInputParameter.id, CommandInputParameter-id> # pseudo notation
```
i.e. each value in the map is a `CommandInputParameter` without `id` field.

- [x] Move `map<>` syntax explanation out of the [CWL v1.0.2 changelog](https://www.commonwl.org/v1.0/CommandLineTool.html#Introduction_to_CWL_Command_Line_Tool_standard_v1.0.2) into another (or its own) section for v1.1.* https://github.com/common-workflow-language/cwl-v1.1/pull/47
- [x] hyperlink all usage of `map<>` to this explanation https://github.com/common-workflow-language/schema_salad/pull/238
