### ISSUE TITLE
Multilingual label & doc fields

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#546]
`label_${Language-Tag}` & `doc_${Language-Tag}`

like
```
label_en:  reference
label_ro: referinţă
label_zh-Hant: 参考
```

Language-Tag is from https://tools.ietf.org/html/bcp47

**Comment by tetron** [comment]
Here is how json-ld does it: https://www.w3.org/TR/json-ld/#string-internationalization

Your proposal is possible but requires enumerating all languages.  The "language map" syntax seems like a better fit.

**Comment by tetron** [comment]
So that would look like:

```
label
  en: reference
  ro: referinţă
  zh-Hant: 参考
```

**Comment by tom-tan** [comment]
I guess it is not scalable to add labels with translated messages to CWL files directly.

For example, my linux machine supports 280 locales.
(I saw the result of `cat /usr/share/i18n/SUPPORTED | awk '{print $1}' | grep -v '¥.' G -v @ | wc -l`)

In the extreme case, it is impossible to read the CWL file that supports all 280 locales.
IMO, i18n supports should be done by IDEs or editors.

How about specifying a field to supports the i18n supports?
For instance,
```cwl
label:
  gettext: reference
```

If CWL spec said that the value of `gettext` should be unique, IDEs and editors may use their own i18n supports such as [gettext](https://en.wikipedia.org/wiki/Gettext) and the resulted CWL file is still readable for users.

Note: we have to choose more generic name than `gettext`.

**Comment by mr-c** [comment]
Hello @tom-tan,

I am curious as to why you think that this isn't scalable?

I don't think any tool or workflow will come with more than a handful of languages.

Certainly consumers of CWL descriptions might make use of automatic translation for users. However if someone wants to provide a CWL tool or workflow description with multiple languages for the help text I think we should allow for that within the document.

This reminds me, we should add a top-level "lang" field to set a default language for all `doc`, `label` fields.

**Comment by tom-tan** [comment]
I completely agree on that CWL should support i18n supports in some way.
I am against just the above implementation to achieve it.

> I don't think any tool or workflow will come with more than a handful of languages.

Even if a CWL file initially supports a few languages, it will grow up to support more and more languages, especially in the big project.

Please consider the following scenario:
- Imagine the case of the examples in common-workflow-language/common-workflow-language.
   After CWL spec supports i18n supports, it would be great if the examples contain multiple language texts.
```yml
cwlVersion: v1.0
class: CommandLineTool
doc: the first example
baseCommand: echo
inputs:
  message:
    type: string
    label: the first argument
    inputBinding:
      position: 1
outputs: []
```
- If someone sends a pull request to support the language A, it will be merged because there are no reason not to support the language A in the official examples.
```yml
cwlVersion: v1.0
class: CommandLineTool
doc:
  en: the first example
  ja: 最初の例
baseCommand: echo
inputs:
  message:
    type: string
    label:
      en: the first argument
      ja: 最初の引数
    inputBinding:
      position: 1
outputs: []
```

- If another person sends a pull request to support the language B, C, D, ..., it *should* be merged because there are no reason to support the language A but not to support the other languages.
```yml
cwlVersion: v1.0
class: CommandLineTool
doc:
  en: the first example
  ja: 最初の例
  cn: 第一个例子
  ru: первый пример
  ne: पहिलो उदाहरण
  pt: o primeiro exemplo
  ar: المثال الأول
  # and other language labels...
baseCommand: echo
inputs:
  message:
    type: string
    label:
      en: the first argument
      ja: 最初の引数
      cn: 第一个参数
      ru: первый аргумент
      ne: पहिलो तर्क
      pt: o primeiro argumento
      ar: الوسيطة الأولى
      # and other language labels...
    inputBinding:
      position: 1
outputs: []
```

I think this scenario is realistic because CWL is an open project.

Obviously, the more language labels are added, the less readable the CWL file is.
That is the reason why I said that just adding a new label for each language is not scalable.

We need a way to support i18n that is still readable even if it supports many languages.

**Comment by mr-c** [comment]
@tom-tan Thank you. Yes, I think we've identified two use cases: casual collaboration with a few languages and prominent, community curated CWL documents with too many translations to include inline.

Perhaps we have have two methods for these two use cases? @tetron 's proposal for the simple case and external translations for the mega-multi-lingual CWL documents.

**Comment by tetron** [comment]
@mr-c I think what @tom-tan is looking for is the ability to add i18n as overlays and not having to change the original workflow.  Maybe something like the "overrides" capability recently added to cwltool could be generalized to a mechanism for patching CWL files, for example to provide translations?

**Comment by tom-tan** [comment]
@tetron Thank you for clarifying my opinion. Yes, I prefer an overriding approach for i18n support.
It will be nice If we have a translator from the original CWL file, a file(s) that stores language labels and the language you like to the CWL file with your preferred language labels.

Another reason why I prefer an overriding approach is that the labels can be used not only for just the description of tools or arguments but also for additional information.
For example, you may want to add information to the original CWL file (e.g. [1st-tool.cwl in user_guide](https://github.com/common-workflow-language/user_guide/blob/gh-pages/_includes/cwl/1st-tool.cwl)) such as:

```yml
cwlVersion: v1.0
class: CommandLineTool
doc: the first example. If you cannot run this example, check `which echo`. # add extra info
baseCommand: echo
...
```

If you want to follow the upstream, it is not good practice to copy and modify the upstream file directly.
But obviously this extra information is not worth adding to the original repository.
An overriding (or pluggable?) approach will satisfy such use cases.
