### ISSUE TITLE
v1.0/scatter-wf1.cwl is failed validation by schema-salad-tool , Is this OK ?

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/common-workflow-language#552]
cwftest test number 30 and 34 using `v1.0/scatter-wf1.cwl` .
but this is not valid 
schema-salad-tool version is `2.6.20171116190026`

Is this OK ?

I think this test case is not design to invalid format test.
So I hope it should be schema-salad-tool valid.

In conformance_test_v1.0.yaml this section is number 30

```yaml
- job: v1.0/scatter-job1.json
  output:
    out: ["foo one", "foo two", "foo three", "foo four"]
  tool: v1.0/scatter-wf1.cwl
  doc: Test workflow scatter with single scatter parameter
```

number 34

```yaml
- job: v1.0/scatter-empty-job1.json
  output:
    out: []
  tool: v1.0/scatter-wf1.cwl
  doc: Test workflow scatter with single empty list parameter
```

schema-salad-tool `2.6.20171116190026` output

```console
$ schema-salad-tool ~/.local/lib/python2.7/site-packages/schema_salad/tests/test_schema/CommonWorkflowLanguage.yml scatter-wf1.cwl
/home/vagrant/.local/bin/schema-salad-tool Current version: 2.6.20171116190026
Document `scatter-wf1.cwl` failed validation:
scatter-wf1.cwl:14:1: checking field `steps`
scatter-wf1.cwl:15:3:   checking object `scatter-wf1.cwl#step1`
scatter-wf1.cwl:16:5:     checking field `in`
scatter-wf1.cwl:17:7:       checking object `scatter-wf1.cwl#step1/echo_in`
scatter-wf1.cwl:23:9:         object id `scatter-wf1.cwl#step1/echo_in` previously defined
```

and `v1.0/scatter-wf1.cwl` is

```cwl
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: Workflow
inputs:
  inp: string[]
outputs:
  out:
    type: string[]
    outputSource: step1/echo_out

requirements:
  - class: ScatterFeatureRequirement

steps:
  step1:
    in:
      echo_in: inp
    out: [echo_out]
    scatter: echo_in
    run:
      class: CommandLineTool
      inputs:
        echo_in:
          type: string
          inputBinding: {}
      outputs:
        echo_out:
          type: string
          outputBinding:
            glob: "step1_out"
            loadContents: true
            outputEval: $(self[0].contents)
      baseCommand: "echo"
      arguments:
        - "-n"
        - "foo"
      stdout: "step1_out"
```
