### ISSUE TITLE
Staging an optional file

### ISSUE THREAD

**Issue by dtitov** [common-workflow-language/common-workflow-language#559]
Hi! I'm trying to stage an optional file. Tried two ways:

1. 
```
  cfg:
    type: File?
    inputBinding:
      prefix: -cfg
      valueFrom: $(self.basename)
```

2.
```
  cfg:
    type:
    - "null"
    - type: File
      inputBinding:
        prefix: -cfg
        valueFrom: $(self.basename)
```

First time a get an error: 
> E           cwltool.errors.WorkflowException: cwl/stereogene/tool.cwl:57:7: Expression evaluation error:
E           cwl/stereogene/tool.cwl:57:7: self is a NoneType, cannot index on string 'basename'

The second time I got another error:
>E           :56:7:               - tried CommandInputEnumSchema but
E                                    * missing required field `symbols`
E           cwl/stereogene/tool.cwl:56:7:                   * the `type` field is not valid
E                                                           because
E                                                               the value 'File' is not a valid Enum_symbol,
E                                                               expected 'enum'
E           :56:7:               - tried CommandInputArraySchema but
E                                    * missing required field `items`
E           cwl/stereogene/tool.cwl:56:7:                   * the `type` field is not valid
E                                                           because
E                                                               the value 'File' is not a valid Array_symbol,
E                                                               expected 'array'

**Comment by mr-c** [comment]
This is an error in `cwltool`

Here's a work around

```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool

requirements: { InlineJavascriptRequirement: {} }

inputs:
  cfg:
    type: File?
    inputBinding:
      prefix: -cfg
      valueFrom: |
        ${ if(self === null) { return null;} else { return self.basename; } }

baseCommand: echo

outputs: []
```

**Comment by anton-khodak** [comment]
Moved to https://github.com/common-workflow-language/cwltool/issues/621

**Comment by anton-khodak** [comment]
I could actually run the tool Michael provided with `$(self.basename)`, it can be already fixed by now. Is it still an issue, @dtitov ?

**Comment by mr-c** [comment]
@anton-khodak Did you run the tool without providing the optional input file?

```
$ cwltool bug.cwl 
/home/michael/cwltool/env/bin/cwltool 1.0.20180125111222
Resolved 'bug.cwl' to 'file:///home/michael/cwltool/bug.cwl'
Workflow error, try again with --debug for more information:
:1:1: Expression evaluation error:
      self is a NoneType, cannot index on string 'basename'
```

bug.cwl
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool

inputs:
  cfg:
    type: File?
    inputBinding:
      prefix: -cfg
      valueFrom: $(self.basename)

baseCommand: echo

outputs: []

```
