### ISSUE TITLE
Workflows with inlined definitions of tools or workflows can not be validated by `schema-salad-tool`

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#564]
It is combined with:
- #551, #552, #553, #554, #555, #556

Currently, `schema-salad-tool` fails validation of the workflows with inlined definition of tools or workflows.
The reason is that there are duplicated identifiers `#step2/parseInt_file1` that should be unique.

```yml
#!/usr/bin/env cwl-runner
class: Workflow
cwlVersion: v1.0
...
steps:
  ...
  step2:
    in:
      parseInt_file1: step1/wc_output
    out: [...]
    run:
      inputs:
        parseInt_file1:
          type: File
          inputBinding: { loadContents: true }
      ...
```
