### ISSUE TITLE
new conformance test needed: refuse to run a workflow with multiple inbound links to a single parameter without MultipleInputFeatureRequirement

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#569]
Inspiration:

https://github.com/common-workflow-language/cwltool/issues/579
https://github.com/rabix/composer/issues/287

Will require `cwltest` to support "must fail" tests.

**Comment by pimpim** [comment]
I am currently making my first simple workflow with rabix-composer and seem to hit the same issue. 

Maybe it is the way rabix composer creates cascading command line options but it seems that even when using different id's for the command line option in the step vs the workflow, it fails without said requirement. 

I understand that using the same input id multiple times is an issue, but shouldn't cascading input id's be supported by default? Example of a simple workflow that fails if the MultipleInputFeatureRequirement is left out is pasted below.

Expected behaviour IMHO: by defining in steps input as source for input_for_reverse_step should be connected as a cascading, rather than a multiple, inbound feature. Actual behaviour: cwltool throws the MultipleInputFeatureRequirement error.

reverselinesflow.cwl
```
class: Workflow
cwlVersion: v1.0
id: reverselinesflow
label: ReverseLinesFlow
inputs:
  - id: input
    type: File
outputs:
  - id: output
    outputSource:
      - reverselines/output
    type: File
steps:
  - id: reverselines
    in:
      - id: input_for_reverse_step
        source:
          - input
    out:
      - id: output
    run: /home/mipmip/rabix-workspace/reverselines.cwl
    label: ReverseLines

```

reverselines.cwl
```
class: CommandLineTool
cwlVersion: v1.0
id: reverselines
baseCommand:
  - /usr/bin/rev
inputs:
  - id: input_for_reverse_step
    type: File
    inputBinding:
      position: 0
outputs:
  - id: output
    type: File?
    outputBinding:
      glob: output_from_reverse_step.*
label: ReverseLines
requirements:
  - class: ResourceRequirement
    ramMin: 100
    coresMin: 1
stdout: output_from_reverse_step.txt
```
