### ISSUE TITLE
proposal: PartitionRequirement

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#581]
PartitionRequirement:

Select preferred compute partition or queue on which to run jobs (site specific).

Field | Type
-- | -- 
partition | string or array of strings

**Comment by LourensVeen** [comment]
Should this be part of the ResourceRequirement, rather than a separate one?

**Comment by tetron** [comment]
No,  because ResourceRequirement isn't site specific, but this is.  Also for backwards compatibility I believe it is better to introduce new requirement types than to add fields to existing ones.

Alternate name would be "QueueRequirement" (I used "Partition" because that's what slurm uses).

**Comment by LourensVeen** [comment]
Ah, that makes sense.

**Comment by tetron** [comment]
See #661

**Comment by kaushik-work** [comment]
@tetron not clear why this goes into the workflow/tool. This should be a per run setting - a variable.

**Comment by michael-kotliar** [comment]
**The following might be related to the discussed question, so I'll explain how we define queues in CWL-Airflow**

When running CWL-Airflow on the Celery Cluster all the tasks are sent to the `default` queue. All the workers are subscribed to the same `default` queue and pick up tasks randomly. To solve this problem and  to be able to assign tasks to the different queues I decided to use `ResourceRequirement` field of the workflow step. So my step looks like this
```yaml
  bam_to_bigwig:
    hints:
      ResourceRequirement:
        coresMin: 1
        ramMin: 1024
    run: ../subworkflows/bam-bedgraph-bigwig.cwl
    in:
      bam_file: samtools_sort_index_after_rmdup/bam_bai_pair
      chrom_length_file: chrom_length
      mapped_reads_number: get_stat/mapped_reads
      fragment_size: macs2_callpeak/macs2_fragments_calculated
    out: [bigwig_file]
```
Available queues are described in the separate yaml file
```yaml
advanced:
  cpus: 2
  ram: 2048
default:
  cpus: 1
  ram: 1024
```
In order to define the appropriate queue we should sort all available queue by  `cpus` and `ram` and chose the lowest possible that satisfies  `ResourceRequirement` of the step. If `ResourceRequirement` is not specified or is not compete - use the lowest queue.
