### ISSUE TITLE
Ambiguity in `hints` and `DockerRequirement`

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#588]
The [specification](http://www.commonwl.org/v1.0/CommandLineTool.html#DockerRequirement) says: `If a CommandLineTool lists DockerRequirement under hints (or requirements), it may (or must) be run in the specified Docker container.`

This sentence seems ambiguous in some cases.
Let's consider the following definition:

```yml
class: CommandLineTool
cwlVersion: v1.0
baseCommand: cat
hints:
  - class: DockerRequirement
    dockerPull: ubuntu
inputs:
  file:
    type: File
    inputBinding: {}
outputs:
  output:
    type: stdout
stdout: output
```

For me, the specification seems to allow the all platforms below.
- A platform prefers executing the tool in the container.
  - I mean that it executes the tool in the container if the image and docker are available.
- A platform prefers executing the tool in the machine directly.
  - I mean that it executes the tool without container if the command is installed in the machine.
- A platform that executes the tool in the container or without container randomly.
  - It is not practical but this behavior seems to be accepted by the spec.

The specification should clarify how to support `hints` and `DockerRequirement` or am I missing something?
