### ISSUE TITLE
Type transformation not happening for types inside the items property

### ISSUE THREAD

**Issue by ThomasHickman** [common-workflow-language/common-workflow-language#608]
If you have a CWL file of:
```yaml
cwlVersion: v1.0
class: CommandLineTool

inputs:
  param:
    type:
      type: array
      items: string[]

outputs: []
```
and run cwltool:
```
$ cwltool test.cwl 
/usr/local/bin/cwltool 1.0.20180111185617
Resolved 'test.cwl' to '.../test.cwl'
Tool definition failed validation:
test.cwl:4:1: checking field `inputs`
test.cwl:5:3:   checking object `test.cwl#param`
test.cwl:8:7:     Field `items` references unknown identifier `string[]`, tried .../test.cwl#string[]
test.cwl:6:5:     checking field `type`
test.cwl:8:7:       Field `items` references unknown identifier `string[]`, tried .../test.cwl#string[]
```
the type `string[]` is not getting converted to `{"type": "array", "items": "string"}`. This conversion is documented in the cwl schema salad specification, so I think this is not a problem with cwltool, but a problem with the cwl schema salad specification.

**Comment by mr-c** [comment]
Here is a workaround:
```
inputs:
  param:
    type:
      type: array
      items:
        type: array
        items: string
```
