### ISSUE TITLE
About specification when output class is File

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/common-workflow-language#629]
conformance test 7

[common\-workflow\-language/cat3\-tool\.cwl at master · common\-workflow\-language/common\-workflow\-language](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/cat3-tool.cwl)

This cwl outputs type is 'File'

```
outputs:
  output_file:
    type: File
    outputBinding: {glob: output.txt}
```

And expected result of this test is about file information.

[common\-workflow\-language/conformance\_test\_v1\.0\.yaml at master · common\-workflow\-language/common\-workflow\-language](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/conformance_test_v1.0.yaml#L51-L56)

```
  output:
    output_file:
      class: File
      checksum: sha1$47a013e660d408619d894b20806b1d5086aab03b
      location: output.txt
      size: 13
```

But I can not find in specification about output class is "File" required output is information of File.
Am I missing something?

If there is no description about this, please write about this.
