### ISSUE TITLE
Expected behavior of outputBinding on array of file

### ISSUE THREAD

**Issue by buchanae** [common-workflow-language/common-workflow-language#643]
Slightly modifying the `array-outputs.cwl` example, we get:
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: touch
inputs:
  touchfiles:
    type:
      type: array
      items: string
    inputBinding:
      position: 1
outputs:
  output:
    type:
      type: array
      items: File
      outputBinding:
        glob: "*.txt"
```

```
cwltool array-outputs.cwl array-outputs-job.yml
/Users/buchanae/src/github.com/buchanae/cwl/venv/bin/cwltool 1.0.20180225105849
Resolved 'array-outputs.cwl' to 'file:///Users/buchanae/src/github.com/buchanae/cwl/examples/array-outputs.cwl'
[job array-outputs.cwl] /private/tmp/docker_tmpFnbu_9$ touch \
    foo.txt \
    bar.dat \
    baz.txt
[job array-outputs.cwl] completed success
{
    "output": []
}
Final process status is success
```

Is this the expected behavior? Can someone explain the expected behavior in the spec? I'm not sure how to interpret this.
