### ISSUE TITLE
address Workflow.InputParameter.inputBinding situation

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#655]
- [x] test in inputBinding on workflow level input combined with WorkflowStepInput.valueFrom with `cwltool`; if that doesn't work then remove `inputBinding` from the Workflow `InputParameter`.
- [ ] uh-oh, that worked, move the example into a v1.0 and v1.1.0-dev1 conformance test
- [ ] add field `deprecated` to schema_salad
- [x] eliminate all fields from `WorkflowInput.inputBinding` except `loadContents`, but mark both `WorkflowInput.inputBinding` and `WorkflowInput.inputBinding.loadContents` as deprecated for `v1.1.0-dev1`
- [x] add `WorkflowStepInput.loadContents` for v1.1.0-dev1

```
cwlVersion: v1.0
class: Workflow
requirements:
  StepInputExpressionRequirement: {}
  InlineJavascriptRequirement: {} 
inputs:
  my_file:
    type: File
    inputBinding:
      loadContents: True

steps:
  one:
    run:
      class: ExpressionTool
      requirements: { InlineJavascriptRequirement: {} }
      inputs: { my_number: int }
      outputs: { my_int: int }
      expression: |
        ${ return { "my_int": inputs.my_number }; }
    in:
      my_number:
        source: my_file
        valueFrom: $(parseInt(self.contents))
    out: [ my_int ]
   
outputs:
  my_int:
    type: int
    outputSource: one/my_int
```
```
echo -n 42 > answer
cwltool demo.cwl --my_file answer
```
