### ISSUE TITLE
Types don't match when using type definition import in multiple files

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/common-workflow-language#666]
If I use a custom type like the following:
```
requirements:
  SchemaDefRequirement:
    types:
      - $import: ../types/types.yaml

inputs:
  thingy:mycustomtype
```

and use the same input type in another CWL file, the types don't match. This is counterintuitive since the type is actually properly resolved. The solution is to add the file namespace, but that looks ugly to me and it would be easier if it is not a requirement.
