### ISSUE TITLE
optional enum (enum?)

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/common-workflow-language#667]
While all types can be made optional by appending a "?", to make an enum optional it needs to be defined as:

```
type:
  - "null"
  - type: enum
     symbols: [bla, bliep]
```

Which is confusing and inconsistent.
