### ISSUE TITLE
proposal: File metadata handling and propagation

### ISSUE THREAD

**Issue by ghost** [common-workflow-language/common-workflow-language#710]
Example use case
=============
1. We are running many instances of a fastq -> VCF pipeline
1. We like to batch by "sample_id"
1. We like to place the sample id in the VCF, so we'd like to inject it into the workflow
1. We are using a particular metadata schema to go with each file - say the [GDC](https://gdc.cancer.gov/developers/gdc-data-model) data model
1. The pipeline has been developed with another, popular schema in mind, where the equivalent of the "sample_id" field is "sampleid"
1. We'd like some or all of the original fastq metadata to be propagated to the VCF

Requirements
==========
1. We'd rather not have a manifest file that is typical of lab settings which is a large spreadsheet with metadata information (like sample_id). This is cumbersome and error prone
2. We'd like the compute engine to fetch this metadata and consume it automatically, without user intervention, when a file is supplied
3. The workflow should be able to copy over input file metadata, modify it and then apply it to an output as the creator wishes.
4. We should be able to automatically map between related metadata schemes given a translation dictionary.

Current SBG solution
===============
The SBG platform currently employs a solution satisfying 1. - 3.: Have a side-car file (`<filename>.metadata`) that carries the metadata information that has been entered manually or automatically, once, on file upload. Information in this side-car file is made available to the compute engine and to CWL scripts under a `.metadata` tag.

We have no automated solution for 4

Possible interface with CWL solution
==========================
1. Formalize the sidecar file solution
1. Allow workflows to declare they need a metadata file
1. Allow workflows to declare what fields of metadata they need
1. Allow workflows to carry javascript that validates the metadata
1. Allow workflows to declare what metadata schema they are expecting
1. Have CWL organization keep a list of mappings from one schema to another that workflow runners can access and use to convert schema as needed to run a workflow

(@tetron I used "metadata" - I thought about putting in "properties" but most of the data I'm thinking about is indeed called "metadata" in the context of genomics. Hopefully we can come up with a clearer nomenclature that emphasizes this is functional metadata 😄 )

**Comment by tetron** [comment]
Here's a few design sketches:

# Explicit metadata propagation

Tool specification:
```
inputs:
  fq: File
outputs:
  bam:
    type: File
    outputBinding:
      addMetadata: $(inputs.fq.metadata) 
```

Input document:
```
fq:
  class: File
  metadata:
    sample_id: 123
```

The `addMetadata` field specifies that the metadata from the input `fq` is copied to the output `bam.

# Implicit propagation

Tool specification:
```
requirements:
  MetadataPropagation:
    propagateMetadata: true
inputs:
  fq: File
outputs:
  bam: File
```

When propagateMetadata is true, metadata from input files is automatically copied to output files that don't specify `addMetadata`.  Makes it possible to include metadata in a workflow where some tools don't metadata.

# Validating metadata

Tool specification:
```
requirements:
  SchemaDefRequirement:
    types:
      HasSampleId:
        type: record
        fields:
          sample_id: string
inputs:
  fq:
    type: File
    metadata_type: HasSampleId
outputs:
  bam:
    type: File
    metadata_type: HasSampleId
    outputBinding:
      addMetadata: $(inputs.fq) 
```

Use `metadata_type` to specify (via SchemaDefRequirement) a schema for what metadata is expected.

**Comment by tetron** [comment]
Via $schemas (which probably should have been called $ontologies) we could enable the user to provide OWL mappings between ontologies.

**Comment by tetron** [comment]
Notes from discussion https://docs.google.com/document/d/1wIjazegFpodToBvaLTN_QkJC4iWXz2CWS5pUBF6CI6U/edit#

SBG said they will take the lead on prototyping the design sketch above and give feedback.

**Comment by bogdang989** [comment]
Following up on the idea from the meeting, of adding metadata just based on input parameter reference. I was thinking we could use the same field `addMetadata` and if it's string(s) those should be input ids to inherit from. Something like this:
```
    - name: addMetadata
      type:
        - "null"
        - string
        - Expression
        - string[]
      doc: |
        If the value is an expression, expression should return a key-value map. 
        Returned map should be set as the `metadata` property of the output file 
        or files. The same map should be set as the `metadata` property of all 
        secondary files. 

        If the value is a string or an array of strings, these must be input 
        parameter references. The list of all files from the referenced inputs is flattened, 
        their `metadata` maps are intersected and the resulting key-value map is set as the `metadata` 
        property of the output file or files. The same map should be set as the 
        `metadata` property of all secondary files. 
```
This way `addMetadata` can just point to input(s) for simple straight-forward propagation or use expressions to do any custom metadata setting or propagation, e.g.
```
outputs:
  output_id:
    type: File
    outputBinding:
      glob: foo
      addMetadata: input_id
```
would be a shorter syntax than
```
outputs:
  output_id:
    type: File
    outputBinding:
      glob: foo
      addMetadata: ${ return inputs.input_id.metadata)
```

and a much shorter syntax when the input_id field is a list (JS expression borrowed from Rabix Composer's metadata inheritance)

```
outputs:
  output_id:
    type: File
    outputBinding:
      glob: foo
      addMetadata: |-
        var inheritMetadata = function(o1, o2) {
            var commonMetadata = {};
            if (!Array.isArray(o2)) {
                o2 = [o2]
            }
            for (var i = 0; i < o2.length; i++) {
                var example = o2[i]['metadata'];
                for (var key in example) {
                    if (i == 0)
                        commonMetadata[key] = example[key];
                    else {
                        if (!(commonMetadata[key] == example[key])) {
                            delete commonMetadata[key]
                        }
                    }
                }
            }
            if (!Array.isArray(o1)) {
                o1 = setMetadata(o1, commonMetadata)
            } else {
                for (var i = 0; i < o1.length; i++) {
                    o1[i] = setMetadata(o1[i], commonMetadata)
                }
            }
            return o1;
        };
        
        return inheritMetadata(self, inputs.input_id)['metadata']

```

This would also allow selecting multiple inputs (e.g. tumor/normal pairs which share the same `case ID`, sequencing platform info, etc.)
```
outputs:
  output_id:
    type: File
    outputBinding:
      glob: foo
      addMetadata: ["tumor_bam", "normal_bam"]
```

**Comment by bogdang989** [comment]
Following yesterday's meeting, here is a small realistic example that uses metadata propagation.
This dummy workflow uses two steps:
#### Quality scale adjusting - adjust_qual_scale.cwl
Reads fastq file quality scale and converts to the standard sanger(here it is just `cat` command). Quality scale information is attached to the output metadata field `quality_scale`.
```yaml
#!/usr/bin/env cwl-runner

class: CommandLineTool
cwlVersion: v1.1.0-dev1
baseCommand:
  - cat
inputs:
  fastq_in:
    type: File
    inputBinding:
      position: 1
outputs:
  fastq_out:
    type: File
    outputBinding:
      glob: $(inputs.fastq_in.basename).adjusted.fastq
      addMetadata: ${  var out = inputs.fastq_in.metadata; out['quality_scale'] = 'sanger'; return out}
requirements:
  - class: InlineJavascriptRequirement
stdout: $(inputs.fastq_in.basename).adjusted.fastq
```

#### Alignment - align.cwl 
Uses `paired_end` metadata to position pe1 and pe2 reads in the command line. Output BAM file has the metadata intersection from the two `paired_end` reads.
```yaml
#!/usr/bin/env cwl-runner

class: CommandLineTool
cwlVersion: v1.1.0-dev1
baseCommand:
  - cat
arguments:
  - position: 0
    valueFrom: |-
      ${
          var first = '';
          var second = '';
          for (var i = 0; i < inputs.fastq_list.length; i++) { 
              if(inputs.fastq_list[i].metadata['paired_end'] == 1) first = inputs.fastq_list[i].path;
              if (inputs.fastq_list[i].metadata['paired_end'] == 2) second = inputs.fastq_list[i].path;
          };
          return first + ' ' + second;
      }
    shellQuote: false
  - position: 1
    valueFrom: "> out.bam && touch out.bam.bai"
    shellQuote: false
inputs:
  fastq_list:
    type: File[]
outputs:
  bam:
    type: File
    secondaryFiles:
      - .bai
    outputBinding:
      glob: out.bam
      addMetadata: fastq_list
requirements:
  - class: InlineJavascriptRequirement
  - class: ShellCommandRequirement
```

### Workflow - alignment_wf.cwl
Quality adjusting step is scattered and connected to alignments step.
```yaml
#!/usr/bin/env cwl-runner

class: Workflow
cwlVersion: v1.1.0-dev1
id: alignment_wf
label: alignment_wf
inputs:
  fastq_list:
    type: File[]
outputs:
  bam:
    outputSource: align/bam
    type: File
steps:
  adjust_qual_scale:
    in:
      fastq_in:
        source: fastq_list
    out:
      - id: fastq_out
    run: adjust_qual_scale.cwl
    scatter: fastq_in
  align:
    in:
      fastq_list:
        source: adjust_qual_scale/fastq_out
    out:
      - id: bam
    run: align.cwl
requirements:
  - class: ScatterFeatureRequirement
```
#### Inputs - alignment_wf.inputs.yml
The metadata fields are taken from a real public dataset. Any files can be used for running, as the contents are not important in this dummy wf.
```yaml
fastq_list:
  - class: File
    location: sm_test.pe_1.fastq
    metadata:
      sample_id: sm_test
      library_id: lib_test_1
      platform_unit_id: pu_test_1
      experimental_strategy: wgs
      platform: illumina
      investigation: brca
      sample_type: tumor
      case_id: brca_test_1
      gender: f
      race: white
      ethnicity: hispanic
      paired_end: 1
  - class: File
    location: sm_test.pe_2.fastq
    metadata:
      sample_id: sm_test
      library_id: lib_test_1
      platform_unit_id: pu_test_1
      experimental_strategy: wgs
      platform: illumina
      investigation: brca
      sample_type: tumor
      case_id: brca_test_1
      gender: f
      race: white
      ethnicity: hispanic
      paired_end: 2
```

If anyone wants to run this workflow, this is how:
```
git clone git@github.com:bogdang989/cwltool.git
cd cwltool
git checkout feature/file-metadata
python cwltool.py --enable-dev alignment_wf.cwl alignment_wf.inputs.yml
```

#### Output BAM and BAI files
Both files have the metadata that describes these files.
```json
{
    "bam": {
        "checksum": "sha1$cf34aa41f5e5288ac5b0dd391ace512eef94bb66",
        "basename": "out.bam",
        "location": "file:///Users/bgavrilovic/Documents/cwl1.1-dev/cwl-v1.1/out.bam",
        "path": "/Users/bgavrilovic/Documents/cwl1.1-dev/cwl-v1.1/out.bam",
        "secondaryFiles": [
            {
                "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
                "basename": "out.bam.bai",
                "location": "file:///Users/bgavrilovic/Documents/cwl1.1-dev/cwl-v1.1/out.bam.bai",
                "path": "/Users/bgavrilovic/Documents/cwl1.1-dev/cwl-v1.1/out.bam.bai",
                "size": 0,
                "class": "File",
                "metadata": {
                    "library_id": "lib_test_1",
                    "platform": "illumina",
                    "gender": "f",
                    "platform_unit_id": "pu_test_1",
                    "case_id": "brca_test_1",
                    "race": "white",
                    "investigation": "brca",
                    "sample_id": "sm_test",
                    "experimental_strategy": "wgs",
                    "quality_scale": "sanger",
                    "ethnicity": "hispanic",
                    "sample_type": "tumor"
                }
            }
        ],
        "metadata": {
            "library_id": "lib_test_1",
            "platform": "illumina",
            "gender": "f",
            "platform_unit_id": "pu_test_1",
            "case_id": "brca_test_1",
            "race": "white",
            "investigation": "brca",
            "sample_id": "sm_test",
            "experimental_strategy": "wgs",
            "quality_scale": "sanger",
            "ethnicity": "hispanic",
            "sample_type": "tumor"
        },
        "class": "File",
        "size": 72866
    }
}
```

**Comment by mr-c** [comment]
@bogdang989 This is great, thanks!

Now we need to make new versions of this using:
- [ ] Using the CWL v1.1 metadata proposed constructs
- [ ] Pure CWL v1.0 with custom records
- [ ] An extension of CWL v1.x using custom records and yet-to-be-proposed constructs to improve the ease-of-use.

**Comment by tetron** [comment]
From discussion today, a counter-proposal for enhancing records.
```
type: record
fields:
  input_file:
    type: File
    jsonldPredicate: “@id”
  first_metadata_field:
    type: string
    jsonldPredicate: my_namespace:my_semantic_identifier1
  second_metadata_field:
    type: string?
    jsonldPredicate: my_namespace:my_semantic_identifier2
```

The record has a File field marked `jsonldPredicate: “@id"` which means the File is the RDF subject, ie the rest of the fields semantically describe that File.  This means a platform can automatically fill out metadata by copying metadata known about the subject File into the other fields of the record.  This is consistent with json-ld.

Input would look like:

```
my_parameter:
    input_file:
        location: http://xyz/my_file.txt
    first_metadata_field: abc
```

**Comment by kaushik-work** [comment]
@tetron What happens when we have a tool (you mentioned this too) when a output file needs to inherit metadata of one of the input files that it doesn't use in a processing step. What if we want to blanket copy all the metadata over even if we don't know all the fields. Thanks!

**Comment by tetron** [comment]
@kaushik-work yes, it seems like we want a workflow step feature that copies metadata from an input parameter to an output parameter.  Maybe something like this?

```
step1:
  in:
    input_record: my_input_record
    input_file: {valueFrom: $(inputs.input_record.my_file)}
  run: my_tool.cwl
  out:
    output_file:
      valueFrom:  $(withMetadata("my_file", self, inputs.input_record))
```

This could be a javascript standard library function, which returns an object with "my_file" set to self, and the remaining fields taken from the third parameter (input_record).  I'm going back and forth on whether this would be better as javascript or as new syntax.  Here's a possible approach with new syntax:

```
  out:
    output_file:
      withMetadata:
        subjectField: my_file  # 'self' is assigned to this
        metadata: $(inputs.inputs.input_record)  # take the rest of the fields from here
```
