### ISSUE TITLE
Proposal: Optional secondary files

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/common-workflow-language#717]
Topic we discussed on one of the CWL meetings, finally got to do more about it.
### Use cases
Indexers. If optional secondary file exists don't run indexing.
Consecutive indexers. First tool creates `.fai`, second creates `^.dict`. Currently it can be done by propagating the `.fai`, but it's not a neat solution as it may not exist if the order of the tools is switched in a different workflow
Multiple options, e.g. idx or tbi.

### Proposed solution
Allow the item in secondaryFiles to be a custom structure `SecondaryFilesSchema` (or some nicer name).
<img width="1142" alt="screen shot 2018-06-28 at 7 10 22 am" src="https://user-images.githubusercontent.com/24608085/42014437-a32def10-7aa2-11e8-9e8a-0dd6b32e9d3a.png">
The structure would consist of `pattern` which would have the value same as the current `string`/`expression`; and an optional boolean field `required` which is by default `true`(or `false`)
<img width="1157" alt="screen shot 2018-06-28 at 7 10 33 am" src="https://user-images.githubusercontent.com/24608085/42014446-ab83dab2-7aa2-11e8-90c8-937bc1bb7ef2.png">

This means that: 
```
secondaryFiles:
  - .fai
``` 
would be equivalent to:
```
secondaryFiles:
  - pattern: .fai
    required: true
```
as well as to:
```
secondaryFiles:
  - pattern: .fai
```
Previous definitions would still be valid. 
```
     secondaryFiles:
      - ^.dict
      - pattern: .fai
        required: true
      - pattern: .blablai
        required: false
      - pattern: .blablai2
```
