### ISSUE TITLE
Collecting use cases for workflow level conditionals

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#725]
(See also #494 for proposals for implementing conditionals.)

Please share below real world use cases

**Comment by kghosesbg** [comment]
# Conditional execution of node
(This is second hand - I did not use this workflow)

- I have a read alignment workflow that gives me a VCF from a FASTQ
- The sample may or may not be contaminated
- There is a diagnostic tool that determines the level of contamination
- There is a filter that removes contamination. It is expensive to run
- It would be pleasant for the user to be able to trigger the filter based on the diagnostic. 
   - If there is no contamination, just pass the BAM file on
   - If there is sufficient contamination process the BAM through the filter

Salient points
- Downstream nodes always get a file
- The file type is consistent
- The workflow behavior is implicitly data driven (rather than by an input switch)

**Comment by kghosesbg** [comment]
# Parameter level conditional

(I made this up from over-hearing some vague discussions. I actually haven't seen/used this workflow)

- I have a workflow that works for both Mouse and Human samples
- There are different optimum parameter sets for the two classes of data
- It is unpleasant to maintain two copies of the workflow just with different parameters baked in
- It would be pleasant for the user to be able to switch in one or the other parameter set based on a (meta)data field value "Mouse" or "Human"

**Comment by AleksandrSl** [comment]
We have workflow similar to @kghosesbg **Conditional execution of node**.
In some target panels we use additional tools to infer CNV genotypes/sex of the sample and inject this information in VCF file, but general workflow is the same. 

Simplified examples:
```
out:
  vcf: inject_analysis_metadata/vcf

steps:
  get_CNV_genotype:
    in: 
      some_data: some_step_1/coverage
    out: [genotype]

  inject_genotype:
    in: 
      CNV_genotype: get_CNV_genotype/genotype
      vcf: some_step_2/vcf
    out: [vcf]

  inject_analysis_metadata:
    in: 
      inject_genotype/vcf
      metadata: metadata
    out: [vcf]
```

```
out:
  vcf: inject_analysis_metadata/vcf

steps:
  inject_analysis_metadata:
    in: 
      some_step_2/vcf
      metadata: metadata
    out: [vcf]
```
