### ISSUE TITLE
Difference between location and path and conformance test 21

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/common-workflow-language#742]
conformance test 21

```
- job: v1.0/cat-job.json
  output:
    output:
      checksum: sha1$47a013e660d408619d894b20806b1d5086aab03b
      class: File
      location: output
      size: 13
  tool: v1.0/cat-tool.cwl
  label: stdinout_redirect
  id: 21
  doc: Test command execution in with stdin and stdout redirection
  tags: [ required, command_line_tool ]
```

but

```
#!/usr/bin/env cwl-runner

class: CommandLineTool
cwlVersion: v1.0

inputs:
  file1: File

outputs:
  output:
    type: File
    outputBinding: { glob: output }

baseCommand: [cat]

stdin: $(inputs.file1.path)
stdout: output
```

using `inputs.files1.path`
but

`cat-job.json` is

```
{
    "file1": {
        "class": "File",
        "location": "hello.txt"
    }
}
```

It only specified about `location`
I want to know relation about `location` and `path`

If there is already described at spec, please teach me.

If spec already described about that, doc will be updated about `location` and `path`
