### ISSUE TITLE
Suggested conformance test to be added, testing InitialWorkDirRequirement with directories as output

### ISSUE THREAD

**Issue by whlavina** [common-workflow-language/common-workflow-language#749]
I am proposing an additional conformance test to be added to the Jenkins suite and applied to various CWL runners (this github repo seems to be the. The following example succeeds in the reference runner, cwltool, but other runners like Toil exhibit failures.

## Expected Behavior
I believe this example workflow should succeed.

## Actual Behavior
This example workflow does succeed with cwltool, but fails with e.g. Toil - see [Toil issue #2310](https://github.com/DataBiosphere/toil/issues/2310).

## Workflow Code
# test.cwl
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow

requirements:
  - class: SubworkflowFeatureRequirement

inputs: []

steps:
  directory_output_step:
    run: mkdir.cwl
    in: []
    out: [my_output]

  initial_work_dir_step:
    run: initial_work_dir.cwl
    in:
        my_input: directory_output_step/my_output
    out: [my_output]
 
outputs:
  my_final_output:
    type: Directory
    outputSource: initial_work_dir_step/my_output
```

# test.yaml
```
{}
```

# mkdir.cwl
```
cwlVersion: v1.0 
class: CommandLineTool

baseCommand: [bash, '-c', 'mkdir "$1" && touch "$1/my_file"', '-']

inputs:
  my_input:
    type: string
    default: my_dir
    inputBinding:
      position: 1

outputs:
  my_output:
    type: Directory
    outputBinding:
        glob: $(inputs.my_input)
```

# initial_work_dir.cwl
```
cwlVersion: v1.0
class: CommandLineTool

requirements:
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.my_input)
        writable: False

baseCommand: 'true'

inputs:
  my_input:
    type: Directory
    inputBinding:
      position: 1

outputs:
  my_output:
    type: Directory
    outputBinding:
      glob: $(inputs.my_input.basename)  
```

## Full Traceback
Succeeds with the reference cwltool, but fails with e.g. Toil.

## Your Environment
* cwltool version: 1.0.20180623165811
* toil version: 3.16.0
* OS: MacOS
