### ISSUE TITLE
Multiple sets of exclusive_parameters allowed?

### ISSUE THREAD

**Issue by IanMcDowell** [common-workflow-language/common-workflow-language#752]
Is it permissible to have multiple sets of `exclusive_parameters`? For example, in `v1.0/examples/record.cwl` :

```
cwlVersion: v1.0
class: CommandLineTool
inputs:
  dependent_parameters:
    type:
      type: record
      name: dependent_parameters
      fields:
        itemA:
          type: string
          inputBinding:
            prefix: -A
        itemB:
          type: string
          inputBinding:
            prefix: -B
  exclusive_parameters:
    type:
      - type: record
        name: itemC
        fields:
          itemC:
            type: string
            inputBinding:
              prefix: -C
      - type: record
        name: itemD
        fields:
          itemD:
            type: string
            inputBinding:
              prefix: -D
# ------------>
    type:
      - type: record
        name: itemE
        fields:
          itemE:
            type: string
            inputBinding:
              prefix: -E
      - type: record
        name: itemF
        fields:
          itemF:
            type: string
            inputBinding:
              prefix: -F
# <------------
outputs: []
baseCommand: echo
```
