### ISSUE TITLE
Better  validation constraints on parameter values

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#76]
For example, min/max values for numbers, regular expression matches for strings.

**Comment by ntijanic** [comment]
Perhaps re-introduce JSON-Schema assertions in ports and TypeDef objects, along with an expression property? Example for array of 3+ ints that must add up to 10:

```yaml
type:
  type: array
  items: int
  minItems: 3
  validateWith:
    engine: "#python-engine"
    script: reduce(lambda a, b: a + b, self) == 10
```

Sadly, there's a clash in terms used between Avro and JSON-Schema. Most can be resolved in favor of Avro, but cannot e.g. use JSON-Schema's `items` assertions.
