### ISSUE TITLE
Add conformance test(s) for staging array of files in a subdir

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/common-workflow-language#777]
CWL developer wants to stage array of File inputs in working directory in a subdir like this:
```
  - class: InitialWorkDirRequirement   
    listing: 
      - entryname: input_dir
        entry: "${ return {class: 'Directory', listing: inputs.list_inputs} }" 
        writable: true
```
As I understand from the spec, this is possible. Implementations may miss implementing this as it is currently not covered by conformance test (I think). From reading the spec, detailed interpretation is required to figure out that this is possible (at least for me, I will keep open the option that maybe I am just not that bright 😃).

I suggest adding test with the syntax above, and one more test using `basename` property of `Directory` instead of `entryname` and possibly one more to check if `entryname` overrides `basename` if both are set.
