### ISSUE TITLE
Proposal: Switch statement

### ISSUE THREAD

**Issue by kaushik-work** [common-workflow-language/common-workflow-language#789]
# Use cases
The two use cases from surveying bioinformatics people at SBG and the clients we help out (NIH institutes, private clients) are
1. Conditionally running a processing step, like an indexer, based on whether a file is present or not
1. Selecting one of several downstream sub-workflows based on an explicit or computed value. The downstream workflows mostly have the same inputs and outputs

# Why skip conditionals
A switch would be a superset of conditional that would serve additional use cases.

# User requirements
1. Make syntax as congruent to existing CWL concepts as possible
1. Make syntax clearly document intent of the workflow for easy auditing
1. Syntax as succinct as we can make it
1. We should be able to "drop" any workflow/commandline tool into a switch slot, just like we can do for a workflow step, without having to change any port names.

# Specifications
1. Introduces a new type of execution unit called a `Switch`
1. The `Switch` appears as a step in the outer workflow just like existing process types like `CommandLineTool`, `Workflow` and `ExpressionTool` and can be run on it's own
1. To the outer workflow the step that happens to be a switch behaves like any other step - taking in inputs and producing outputs
1. Instead of steps the `Switch` has `cases`. The `id` of each case can be anything though the id `default` has a reserved meaning. 
1. Each `case` is a workflow or tool which runs if the value of `switch` matches the value in the `case` field. If no `case` field matches the `switch` value, the case with id `default` is run. A `default` case is required.  
1. Workflows that are part of the switch can share zero or more inputs and zero or more outputs
1. Un-shared outputs have to be of optional type
1. The `Switch` has a `passThrough` field applicable to each `case` output that indicates that that output will directly pass through the given `Switch` input.

# Proposed syntax

## Main workflow

```
steps:
  ...
  - id: my_switch_step
    in:
      input1:
        source: A
      input2:
        source: B
      input3:
        source: C
    out:
      - id: output1?
      - id: output2
      - id: output3?
    run: ./my-switch.cwl
  ...
```

## Switch component

![switch abstract example](https://user-images.githubusercontent.com/6299530/51336160-dc2b2900-1a51-11e9-8dfe-75d20550f8e0.png)

`my-switch.cwl`

```
class: Switch
cwlVersion: v2.0
id: my_switch
label: Example of a Switch

inputs:
  input1:
    type: File?
  input2:
    type: string
  input3:
    type: int?


outputs:
  output1:
    outputSources:
      - case1/out1
      - caseTwo/outA
    type: File? 

  output2:
     outputSources:
       - case1/out1
       - caseTwo/oB
       - c_3/passA 
       - default/oP
     type: string 

  output3:
     outputSources:
       - caseTwo/pt1
       - c_3/passB
       - default/oQ
     type: int?


switchValue: ${if (inputs.input3 > 5) return "case three"; }

switch:
  case1:
    case: text for case 1
    in:
      in1:
        source: input1
      in2:
	    source: input2
    run: wf1.cwl

  caseTwo:
    case: 22
    in:
      inA:
        source: input1
      inB:
        source: input2
    passthrough:
      pt1:
        source: input3   
    run: wf2.cwl

  c_3:
    case: "case three"
    passthrough:
      passA:
        source: input2
      passB:
        source: input3

  default:
    in:
      iY:
        source: input2
      iZ:
        source: input3
    run: wf3.cwl     
```

# Questions arising
1. Should we forbid recursion, which allows people to build a loop (see note below in comments)
1. Should it be "workflows share at least one input and output", or is that too restrictive? - NO
1. Should we have an explicit pass through option that would feed inputs to outputs. This would address a common use case where a filter/converter is run on an input OR the input is passed as is. - YES

- [x] Write up use cases
- [x] Why we should go straight to this rather than conditionals
- [x] Write up requirements

Relates to 
- #725 
- #494 

2019.02.05 - Do we forbid recursion?
2019.01.17 - Added example diagram, fixed syntax text, new syntax without `out` field, new syntax for pass through
2019.01.16 - Removed reserved `switch` input, replaced with `switchValue`
2019.01.16 - Added `switchValueFrom`, fixed typos

**Comment by psafont** [comment]
Is this for conditional steps or for selecting the input parameters on runtime?

**Comment by mr-c** [comment]
@psafont, I think this is a request for a workflow level switch statement

**Comment by kaushik-work** [comment]
# Use cases
The two use cases from surveying bioinformatics people at SBG and the clients we help out (NIH institutes, private clients) are
1. Conditionally running a processing step, like an indexer, based on whether a file is present or not
1. Selecting one of several downstream sub-workflows based on an explicit or computed value. The downstream workflows mostly have the same inputs and outputs

# Why skip conditionals
A switch would be a superset of conditional that would serve additional use cases.

# User requirements
1. Make syntax as congruent to existing CWL concepts as possible
1. Make syntax clearly document intent of the workflow for easy auditing
1. Syntax as succinct as we can make it
1. We should be able to "drop" any workflow/commandline tool into a switch slot, just like we can do for a workflow step, without having to change any port names.

# Specifications
1. The switch introduces a new type of execution unit called a `SwitchWorkflow`
1. The `SwitchWorkflow` appears as a step in the outer workflow just like existing types like `CommandLineTool`, `Workflow` and `ExpressionTool` 
1. To the outer workflow the step that happens to be a switch behaves like any other simple step - taking in inputs and producing outputs
1. The `SwitchWorkflow` has one required integer input called `switch`. This input is reserved.
1. Workflows are selected on the basis of the value of the `switch` which is expected to be a positive non-zero integer. It is an error to supply any other type, or value beyond this range. 
1. A `default` case must be supplied. This workflow will run if the value of `switch` does not match 
1. Workflows that are part of the switch can share zero or more inputs and zero or more outputs
1. Un-shared outputs have to be of optional type

# Proposed syntax

Main workflow

```
steps:
  ...
  - id: my_switch_step
    in:
      - id: switch
         source: Z
      - id: in1
        source: A
      - id: in2?
        source: B
      - id: in3?
        source: C
    out:
      - id: out1
      - id: out2?
      - id: out3?
    run: ./my-switch.cwl
  ...
```

`my-switch.cwl`

```
class: SwitchWorkflow
cwlVersion: v2.0
id: my_switch
label: Example of a Switch

inputs:
  - id: in1
    type: File
  - id: in2
    type: string?
  - id: in3
    type: int?

outputs:
  - id: out1
    outputSource:
      - wf1/outA
      - wf2/outA
      - wf3/outA
    type: File 
  - id: out2
     outputSource:
      - wf1/outB
     type: File? 
  - id: out3
    outputSource:
      - wf2/outB
      - wf3/outB
     type: string?

switch:
   case1:
       in:
          - id: wf1_a
             source: in1
         - id: wf1_b
            source: in2
       out:
         - id: outA
         - id: outB
      run: ./wf1.cwl
    
   case2:
       in:
          - id: wf2_a
             source: in1
         - id: wf2_b
            source: in3
       out:
         - id: outA
         - id: outB
      run: ./wf2.cwl

    default:
       in:
          - id: wf3_a
             source: in1
         - id: wf3_b
            source: in2
       out:
         - id: outA
         - id: outB
      run: ./wf3.cwl
```

# Questions arising
1. Should it be "workflows share at least one input and output", or is that too restrictive?

**Comment by tetron** [comment]
I think making conditions a type of process object rather than extending workflow step is a really good idea.  It is more verbose but it fits into the architecture much better.

**Comment by stain** [comment]
Agree that making it a process type makes much more sense, as this enforces the input/output contract of the conditional, as well as making it clearer if an implementation support this or not, rather than deep-nested inside a workflow step.

Where I am a bit confused is that you say `switch` is required and must be an integer, and so presumably would need to be calculated with javascript on the outside and then used to select the case, yet inside you have `switch.. case1 ... case2` -- but what is `case1` and `case2` here compared to the `switch` input?  Should they be `1`, `2` ?   Is `default` equivalent to `0`? 

Do I understand it correctly that in your proposal for `outputSource` as a list you mean that case 0 picks the first item, case 1 second item, unmatched cases `null`? (and hence the type must inclued `?`)  I think this is a nice approach to enforce the typing is correct.

In small cases using integer-based cases is probably OK, but It can be challenging to maintain this if many cases come along, then named cases might be better. 

Your `outputSource` use references like `wf2/outA` - what is `wf2` here? Is this meant to refer to the outputs of `case2` that happens to run `wf2.cwl`?

**Comment by kaushik-work** [comment]
@stain sorry, did not see your comments before.

> Where I am a bit confused is that you say switch is required and must be an integer, and so presumably would need to be calculated with javascript on the outside and then used to select the case, yet inside you have switch.. case1 ... case2 -- but what is case1 and case2 here compared to the switch input? Should they be 1, 2 ? Is default equivalent to 0?

> In small cases using integer-based cases is probably OK, but It can be challenging to maintain this if many cases come along, then named cases might be better.

Agreed. Changed this to be a string. So the switch statement mandatory `switch` input would be a string and the workflow that matched the case string (in the field `match`) would run. If nothing matched, the case with id `default` would run.

> Do I understand it correctly that in your proposal for outputSource as a list you mean that case 0 picks the first item, case 1 second item, unmatched cases null? (and hence the type must inclued ?) I think this is a nice approach to enforce the typing is correct.

Yes, unless each case feeds into an `outputSource` the type has to be optional (`?`) since there is a code path where that output will not get anything.

> Your outputSource use references like wf2/outA - what is wf2 here? Is this meant to refer to the outputs of case2 that happens to run wf2.cwl?

Thanks for catching that! That was a mistake. I've replaced that with the case id which puts it in line with the same mechanism for `Workflow`

**Comment by tetron** [comment]
Formatting error:

```
        out:
           -id: outA
           -id: outB
             passThrough: wf3_B
```

I think you meant
```
        out:
           - id: outA
           - id: outB
             passThrough: wf3_B
```

**Comment by tetron** [comment]
My one comment is that there should be an optional expression that evaluates before evaluating `match`.  This would be something like `switchValueFrom: $(inputs.a > 5)` and then the cases would be `match: true` and `default` (which could also be called `else`).

**Comment by TMiguelT** [comment]
I had some thought on this proposal, and even though most of the comments support having a new base level entity (`SwitchWorkflow`), I really wonder if this is necessary. 

Some of the downsides of this are:
* Much more verbose syntax
* Adding an entirely new construct to the spec
* Duplication of input and output specifications (caused by the need for two separate files here, instead of one single workflow)

If, instead of adding a new construct, we simply added the `match` field of type `Expression` to the `WorkflowStep` element of a normal `Workflow`, you could avoid the need for all of this complexity, with the same power over the workflow. If you wanted to emulate the example above, it might look like this:

```yaml
class: Workflow
cwlVersion: v2.0

inputs:
  switch:
    type: String

steps:
   case1:
       match: $(switch.includes("case1"))
       [...]
  
   case2: 
       match: $(switch.includes("case2"))
       [...]
    
```

If a `match` evaluates to falsey, the step will not run, meaning all its outputs are set to `null`. Can anyone explain to me the issue with a syntax like this?
