### ISSUE TITLE
CWL with R returns empty output directory with "Final process status is success" status

### ISSUE THREAD

**Issue by ranijames** [common-workflow-language/common-workflow-language#823]
Hello All,

I have a CWL script which says it is Final process status is success, but none of the output files are written to the described output directory. The CWL scripts has two input parameter one is input directory where all input file for the HIF_scorefinder.R is defined and second is a designated output directory, where all output files are suppose to be written into.
But currently, my script just runs and finishes with final status Final process status is success, but inside the output directory there is no expected files. Here is what I have the` findscore.cwl` looks like.

```
cwlVersion: v1.0
class: CommandLineTool

doc: "The tool for calculating the score for a given set of input samples"

requirements:
 - class: ShellCommandRequirement
 - class: InlineJavascriptRequirement
 - class: InitialWorkDirRequirement
   listing:
    - entry: "$({class: 'Directory', listing: []})"
      entryname: $(inputs.outputdir)
      writable: true

baseCommand: [Rscript, HIF_scorefinder.R]

inputs:
 sample_input:
  type: Directory
  inputBinding:
   position: 1
 outputdir:
  type: string?
  inputBinding:
   position: 2

outputs:
 Hypoxiaresult:
  type: Directory
  outputBinding:
   glob: $(inputs.outputdir)
```
The YML file,

```
sample_input:
 class: Directory
 path: /cluster/home/user/Projects/Kjo_proct/pocKj
outputdir: HypScore1
```

And this is how I tried to run the CommandLineTool Tool,

`cwltool --debug --preserve-entire-environment hypoxia.cwl moun.yml`

And the Final status after the run says,
`Final process status is success
`
But the designated output directory is empty. Any suggestions are much appreciated.
