### ISSUE TITLE
[Provenance] Store the execution metadata, including command line, when running a job

### ISSUE THREAD

**Issue by hmenager** [common-workflow-language/common-workflow-language#84]
Maybe also include the generated files.

**Comment by ntijanic** [comment]
Is this for reference implementation, or do you think the spec should cover how to do this consistently?

If latter, perhaps we could just specify a few properties to extend [wfprov](http://wf4ever.github.io/ro/#wfprov). Some regular metadata is already handled by PROV-O, but might be missing stuff like command line and environment setup used. It might be worth adding these properties elsewhere in generic form (EDAM?).

**Comment by mr-c** [comment]
+1 for the reference implementation to do so, moved to https://github.com/common-workflow-language/cwltool/issues/9

For the spec, I agree it that it would be useful to expose the metadata to the tools *and* require a specific report available to the user.

**Comment by hmenager** [comment]
+1 on moving this to ref implementation ;)

**Comment by mr-c** [comment]
From @stain [in chat](https://gitter.im/common-workflow-language/common-workflow-language?at=56e2a04e11a3dbf55acb0993)
>I would like to work on how we can have a somewhat common view of provenance from a CWL worflow run - we can use what we've done in Taverna https://github.com/apache/incubator-taverna-engine/tree/master/taverna-prov#structure-of-exported-provenanceand https://w3id.org/ro/2016-01-28/wfprov as a starting point.
I think something like our RO Bundle is needed so you can gather all the files made and used, and include copies of the CWL workflow and tool descriptions at the time of running.
>[...]
>in tavernaprov we added some more technical things that might not be needed in CWL as they could be engine specific
like we included a way to show a snippet of the value within the graph
but obviously you don't want to do that with larger values

**Comment by ntijanic** [comment]
Also from @stain:

> perhaps come up with a decent JSON-LD profile for wfprov

+1.

**Comment by ntijanic** [comment]
Playing around with structure of run snapshots. Starting with the simplest workflow:

```yaml
# wf.yaml
class: Workflow
inputs:
  - id: i1
outputs:
  - id: o1
    source: s1.o1
steps:
  - id: s1
    run: tool.yaml
    inputs:
      - id: s1.i1
        source: i1
```

This one just has a single step - a tool that e.g. increments its input integer.
After running (i1=1), we can get a `wfprov:WorkflowRun` that might be represented in JSON-LD like:

```yaml
class: WorkflowRun                          # type
id: "#run1"
process: wf.yaml                            # describedByProcess
enactedBy: http://example.org/engine
inputs:                                     # reverse of usedInput
  - {port: wf.yaml#i1, value: 1}            # port = describedByParameter
outputs:                                    # reverse of wasOutputFrom
  - {port: wf.yaml#o1, value: 2}
runs:                                       # reverse of wasPartOfWorkflowRun
  - class: ProcessRun
    id: "#run1.s1"
    process: wf.yaml#s1                     # Step, not tool.
    enactedBy: http://example.org/engine
    inputs:
      - {port: wf.yaml#s1.i1, value: 1}
    outputs:
      - {port: wf.yaml#s1.o1, value: 2}
```

Not quite sure how to represent `wfprov:Artifact`s that are just integers, so here they are objects with `value` property.
Also not sure if this is even a valid `wfprov:WorkflowRun`.

The trickiness comes when we nest this workflow in an outer workflow and scatter it:

```yaml
# wf-outer.yaml
class: Workflow
outputs:
  - id: o1
    source: s1.o1
steps:
  - id: s1
    run: wf.yaml
    scatter: s1.i1
    inputs:
      - id: s1.i1
        source: i1
```

Suppose we run this with `[1, 2]` as input.
Should do a scattered increment and get `[2, 3]` as result.
Without any RDF restrictions, I would encode the runs/jobs like this:

```yaml
- class: WorkflowJob
  id: run1
  app: wf-outer.yaml
  parent: null
  inputs: {i1: [1, 2]}
  outputs: {o1: [2, 3]}
- class: ScatterJob
  id: run1.s1
  app: null
  parent: run1
  inputs: {i1: [1, 2]}
  outputs: {o1: [2, 3]}
- class: WorkflowJob
  id: run1.s1.1
  app: wf.yaml
  parent: run1.s1
  inputs: {i1: 1}
  outputs: {o1: 2}
- class: WorkflowJob
  id: run1.s1.2
  app: wf.yaml
  parent: run1.s1
  inputs: {i1: 2}
  outputs: {o1: 3}
- class: CommandLineJob
  id: run1.s1.1.s1
  app: tool.yaml
  parent: run1.s1.1
  inputs: {i1: 1}
  outputs: {o1: 2}
- class: CommandLineJob
  id: run1.s1.2.s1
  app: tool.yaml
  parent: run1.s1.2
  inputs: {i1: 2}
  outputs: {o1: 3}
```

There's a root job (run1), a `ScatterJob` which is a container for iterations,
two nested `WorkflowJob`s, each with own `CommandLineJob`.

Job identifiers are built semantically: `<parent_id>.<step_id>` or `<parent_id>.<iteration_index>`.
This should work since CWL local identifiers should match the `[A-Za-z][A-Za-z0-9]*` pattern.
An improvement would be to have IRIs (e.g. http://example.org/jobs/run1.s1).
It's only a nicety - IDs can be anything (hopefully URLs though).
Likewise, `app` references should be URLs.

Putting this into wfprov is tricky. Best I could come up is:

```yaml
class: WorkflowRun
id: "#run1"
process: wf-outer.yaml
inputs:
  - {port: wf-outer.yaml#i1, valueJson: "[1, 2]"}
outputs:
  - {port: wf-outer.yaml#o1, valueJson: "[2, 3]"}
runs:
  - class: IterationRun
    id: "#run1.s1"
    process: wf-outer.yaml#s1
    inputs:
      - {port: wf-outer.yaml#s1.i1, valueJson: "[1, 2]"}
    outputs:
      - {port: wf-outer.yaml#s1.o1, valueJson: "[2, 3]"}
    runs:
      - class: WorkflowRun
        id: "#run1.s1.1"
        process: wf-outer.yaml#s1
        inputs: [{port: wf.yaml#i1, value: 1}]
        outputs: [{port: wf.yaml#o1, value: 2}]
        runs:
          - class: ProcessRun
            id: "#run1.s1.1.s1"
            process: wf.yaml#s1
            inputs: [{port: wf.yaml#s1.i1, value: 1}]
            outputs: [{port: wf.yaml#s1.o1, value: 2}]
      - class: WorkflowRun
        id: "#run1.s1.2"
        process: wf-outer.yaml#s1
        inputs: [{port: wf.yaml#i1, value: 2}]
        outputs: [{port: wf.yaml#o1, value: 3}]
        runs:
          - class: ProcessRun
            id: "#run1.s1.2.s1"
            process: wf.yaml#s1
            inputs: [{port: wf.yaml#s1.i1, value: 2}]
            outputs: [{port: wf.yaml#s1.o1, value: 3}]
```

Few issues here:
 - Needed to encode the arrays in a `valueJson` property. This is a known issue with CWL though (encoding non-primitive values in RDF).
 - `IterationRun` (not part of wfprov) is a specialization of a `ProcessRun`, similar to the previously mentioned `ScatterJob`. Not sure how I would encode the iterations without it.
 - The `wfprov:wasPartOfWorkflowRun` property doesn't quite fit with `IterationRun`s.
 - For the nested `WorkflowRun`s, there's an inconsistency with `port` properties.
 If this was a non-scattered workflow component, those would point to inputs and outputs of the step in the outer workflow
 (in the previous example `ProcessRun`s had e.g. `{port: wf.yaml#s1.i1, value: 1}` rather than `{port: tool.yaml#i1, value: 1}`).

I'm still confused about `wfdesc:Process` and how it maps to CWL.
It seems to map to `cwl:Step` nicely, but it also maps to `cwl:Workflow` and `cwl:CommandLineTool`.
Perhaps if I found an example `wfdesc:Workflow` that has two instances of the same workflow as components the confusion would be cleared :)
