### ISSUE TITLE
Allow literal content in `Dirent`

### ISSUE THREAD

**Issue by kaushik-work** [common-workflow-language/common-workflow-language#850]
# Use cases

1. I have a local working tool that uses a bash script. I need a painless way to create a `CommandLineTool` from it. I thought the `InitialWorkDirRequirement` would solve this, but bash `$` clashes. I don't want to bundle the script - I find it incredibly convenient and transparent to have the script in the CWL wrapper.

1. I have an R-script that I want to `CWL`-ize. But R has a `$` operator which clashes with CWL. I don't want to bundle the script - I find it incredibly convenient and transparent to have the script in the CWL wrapper.

# Proposed solution
Add a new boolean field `literal` to `Dirent` that prevents CWL engines from doing any processing on the contents.

This is backwards compatible, does not affect existing scripts but solves a major pain point when local prototype tools are being wrapped into CWL.

**Comment by kaushik-work** [comment]
Relates to #422
Discussion in #107 is an interesting history behind the origination of the expression feature.

**Comment by tetron** [comment]
How about a quoting syntax that suppresses any expression evaluation inside it?

**Comment by kaushik-work** [comment]
@tetron that is something @christiansbg suggested too. That might work too, except we run into a "it's turtles all the way down" issue where our quoting syntax is used in someone else's language meaningfully.

From the use cases I've been shown this is for a locally working bash or R or Python script that has it's own way of getting the inputs/files. CWL allows users to set up env variables and stage files already, so all that is needed is a way to attach the existing script literally.

**Comment by tetron** [comment]
```
$//
#!/bin/foo
echo 'Anything up to $// goes here, it will not be quoted'
A=$(inputs.xyz)    # run a program literally called "inputs.xyz"
B=$(cat foobar)
$//
echo "After the second $// things are interpolated again"
A="$(inputs.xyz)"
```

Produces (for inputs.xyz="xyz")
```
#!/bin/foo
echo 'Anything up to $// goes here, it will not be quoted'
A=$(inputs.xyz)    # run a program literally called "inputs.xyz"
B=$(cat foobar)
echo "After the second $// things are interpolated again"
A="xyz"
```

The rational for `$//` is that (a) `$/` is not a shell metavariable and (b) it kind of looks like a javascript line comment.

Another idea is `$/*` and `$*/` or `*/$` but those are not so great because '*' and '$*' are both meaningful to the shell.

**Comment by tetron** [comment]
You're going to tell me that `$//` means something in R, arn't you :laughing: 

I strongly prefer the quoting solution, because it generalizes across all uses of expressions instead of just one narrow case.

**Comment by kaushik-work** [comment]
That's a good example because what happens for:
```
$//
#!/bin/perl
#`[
Valid perl comment
$//
]
say "$(inputs.xyz)";

$//
echo "After the second $// things are interpolated again"
A="$(inputs.xyz)"
```

**Comment by tetron** [comment]
Yea, Perl.

So I see three possible approaches.

# You can turn on quoting but not turn it off.  So nothing needs to be parsed once the start sequence is recognized
# You can specify an arbitrary end sequence (similar to how in bash you do `cat <<EOF ... EOF`)
# For exceptional situations where the end sequence does actually conflict with your script, there's a way to quote it.  (On the assumption that we are careful to pick an end sequence that is unlikely to conflict with any language we care about).

**Comment by bogdang989** [comment]
I think the most important user requirement we should solve here is:
- I as a user have a script I run and test locally. 
- Now I want to copy/paste it into the CWL directly without any additional modifications.
- In future, I want to copy/paste updated version directly and it will work

Right now we can just replace `$(` with `$("$(")` and bash script will work. However, this is pretty annoying for the tool developer, especially 
Introducing custom quotes still would mean additional post-process is required(adding the quotes). And though it might solve the problem for some languages, we never know if that quote can be a part of any other language.

Adding a separate key, e.g. `is_literal` will probably solve the issue (and could probably be reused if there is this issue for other fields, though I don't see where else we have the same nuisance).

**Comment by tetron** [comment]
Another direction is to allow an Expression to be an object, and indicate quoting that way:

```
content:
  quote: "..."
```

**Comment by mr-c** [comment]
How about `$raw: URI` meaning the same as `$import: URI` except that any `$` usage in the file is automatically escaped for the user.

**Comment by mr-c** [comment]
Or a `File` input with a default path

**Comment by tetron** [comment]
Example using $include

```
content:
  quote: {$include: "myscript.sh"}
```

**Comment by stain** [comment]
For shell script, could we not avoid `baseCommand` combined with `InitialWorkDirRequirement` and rather have `script` straight on top?

You could then also have `interpreter` set to  `python` in case you don't want to do `#!/` she-bang (which does not work on Windows) and `scriptname` in case the interpreter is sensitive to file names.

Might become a `ScriptTool` instead of being part of `CommandLineTool` and thus also allow other ways of execution.

**Comment by kaushik-work** [comment]
@stain 

I like your proposal because it makes it explicit that we are running a script in the tool instead of a script hidden in a `CommandLineTool`.

When I look at the verbosity of CWL I balance it with it's explicit nature. This proposal makes things more explicit and uncomplicated, but this makes the spec more complex -> harder to learn (perhaps)

So your's would look like

```
class: ScriptTool
interpreter: "/usr/bin/python3"
inputs:
  in: 
    type: File
    inputBinding:
       ...
script: |-
  import sys
  print(sys.argv)
```

and the command line is `/usr/bin/python3 script.sh /path/to/in.ext`

**Comment by kaushik-work** [comment]
@mr-c the issue with having automatic escaping is that here we now have to parse the semantics of the programming language. I fear we get ourselves into edge cases and bugs via that. (The thumbs down looks harsh, sorry, but wanted to tag it.)

**Comment by stain** [comment]
Right, explicitness here is also making the script a first-class citizen rather than an arbitrary file.

Not sure why it would be much harder to learn? It is like a sibling to `CommandLineTool` and use Docker images the same way. 

If we keep it in `CommandLineTool` then it should work with `baseCommand` - e.g. making the script a numbered input very similar to `type: File` which generated path will be appended to the command line.

**Comment by stain** [comment]
Or could something like this work, by expanding what is allowed in `arguments`?

#!/usr/bin/env cwl-runner
```
cwlVersion: fantasy/850
class: CommandLineTool
label: Run an embedded Python script
hints:
  DockerRequirement:
    dockerPull: python:3

baseCommand: python

arguments: 
  - class: File
    basename: "script.py"
    contents: |-
      print("Hello")
      print("This is my Python script")

outputs:
  results:
    type: stdout
```

.. or would that fail with the same script evaluation happening as under `InitialWorkDirRequirement` and thus also needing a `raw`?

**Comment by stain** [comment]
Here's the current `default` hack avoiding `InitialWorkDirRequirement`, but inadvertently/confusingly also allowing anyone to override the script:

```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
label: Run an embedded Python script
hints:
  DockerRequirement:
    dockerPull: python:3
baseCommand: python

inputs: 
  script: 
    type: File
    inputBinding:
      position: 1
    default:
       class: File
       basename: "script.py"
       contents: |-
         print("Hello")

outputs:
  results:
    type: stdout
```
