### ISSUE TITLE
Proposal: runIf for conditional workflow logic

### ISSUE THREAD

**Issue by TMiguelT** [common-workflow-language/common-workflow-language#853]
*Created in consultation with @kaushik-work*

# Motivation
It is a common desire to support conditional logic in CWL, for these main use-cases:
* I want to run a single step some of the time. For example, I might have a fastq trimming step that can be enabled or disabled depending on whether the input fastqs are pre-trimmed or not
* I want an if-else, or switch case statement. For example, I might want to run a different variant caller depending on if the input sample is somatic or germline
* I want to run multiple parallel steps, but they're all optional. For example, I might have a list of 3+ variant callers, but I want to choose which to run each time. Sometimes I only want to run 1, and sometimes I want all 3

# Proposed Changes
* We add a `runIf` field to the `WorkflowStep` definition, of type `Expression`
* We add a `deps` field to the `WorkflowStep` definition, of type `string[]`
* We extend the `LinkMergeMethod` type to include `chooseFirst`

# New Workflow Logic
* The `deps` field defines a list of step dependencies that can exist without the need for a file to be passed between the two steps. Thus, if one step depends on another using `deps`, we add a new edge to the DAG.
* Before we execute each step, we execute its `runIf` expression, if present. If it evaluates to truthy, then we continue as normal. If it evaluates to falsy, then we skip running this step. Any proceeding steps that depend on the skipped step or its outputs will fail, unless these inputs are defined as optional, or else these inputs are part of an array of inputs
* The `runIf` expression has its `this` value set to the following structure:
```yaml
steps:
  stepA:
    ran: true
    outputs:
      foo: [...]
      bar: [...]

  stepB:
    ran: false
    outputs: {}
```
  This lets a stage query if other stages have finished or were skipped, and query the state of their outputs. Only stages that the `runIf` stage depends on will be present in this `steps` object.
* Having `deps` as a new key allows us to construct if-else or switch case statements by checking if another step ran or didn't run, without the need for a file-based dependency
* `LinkMerge` set to `chooseFirst` means: "choose the first element in this array that isn't null/empty". This allows us to do value passthroughs as you will see in the examples

# Examples
## If else
This demonstrates the example where we want to choose one or the other mutually exclusive variant callers, based on an input boolean. We implement the `else` clause by depending on the first step and only running if it didn't run:
```yaml
class: Workflow
inputs:
  somatic:
    type: boolean
  bam:
    type: File
steps:
  pisces:
    in:
      alignment:
        source: bam
    out:
      variants: <some value>
    runIf: $(inputs.somatic)
  haplotypeCaller:
    in:
      alignment:
        source: bam
    out:
      variants: <some value>
    deps: [pisces]
    runIf: $(!this.steps.pisces.ran) 
```
Note, we could also have `$(!inputs.somatic)` as the second `runIf` expression, and removed the `deps`. This would have been more concise, but wouldn't let me demonstrate these features which you might sometimes need, for example if you want to be very careful that your conditions can't both be true and both steps will execute.

## Conditional skip with passthrough
This implements the first use-case mentioned above, where we want to have a step that only runs sometimes, but we want the next step in the DAG to handle this behaviour:
```yaml
class: Workflow
inputs:
  fastq:
    type: File
steps:
  checkAdapters:
    in:
      fastq:
        source: fastq
    out:
      adaptersFound: <some value>
  trim:
    in:
      fastq:
        source: fastq
    out:
      trimmed: <some value>
    runIf: $(this.checkAdapters.out.adaptersFound)
    deps:
      - checkAdapters
  align:
    in:
      read:
        source:
          - #trim/trimmed
          - fastq
        linkMerge: chooseFirst
```
Note how we didn't need the `deps` key because there is a traditional file-based dependency between `align` and `trim`.

## One or more steps
This implements the third use-case mentioned above, where we want to run 1 or more parallel stages, depending on an input array:
```yaml
class: Workflow
inputs:
  callers:
    type: string[]
  bam:
    type: File
steps:
  callGatk:
    in:
      bam:
        source: bam
    out:
      vcf: <some value>
    runIf: $(inputs.caller.includes("gatk"))
  callFreebayes:
    in:
      bam:
        source: bam
    out:
      vcf: <some value>
    runIf: $(inputs.caller.includes("freebayes"))
  callStrelka:
    in:
      bam:
        source: bam
    out:
      vcf: <some value>
    runIf: $(inputs.caller.includes("strelka"))
```

# Relation to other proposals
This topic has already been discussed at length, for example #494, #789 and in the GoogleGroup: https://groups.google.com/forum/m/?source=mog&gl=us#!topic/common-workflow-language/JU7PSEKr97M. In fact, this very syntax has been suggested in a slightly different form by @LourensVeen and @tetron.

In addition, there is one major competing proposal that also implements conditional logic: #789.

The purpose in writing this issue is to provoke some debate between these two proposals so we as a community can better decide which syntax we really want. I believe my syntax is more concise and adds less to the CWL language, but the switch statement is perhaps more explicit, which has its own advantages.
