### ISSUE TITLE
Proposal: More elegant way to repeat prefix for array input

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/common-workflow-language#857]
## Use cases
Command line tools that allow multiple files/strings/floats for a parameter, most often receive this list of parameters by repeating the prefix multiple times. These inputs are defined in CWL as array of items. Currently there is no easy way to repeat the prefix for each element in the array and developers can go for two approaches(at least from what I saw):
1) break down the type and specify a separate inputBinding for each array. E.g. to repeat a prefix for array of strings, one must write:
```
  input_array_strings:
    type:
      type: array
      items: string
      inputBinding:
        prefix: -B=
        separate: false
    inputBinding:
      position: 2
```
2) Add an argument with a JS expression and add each array element, with attached prefix, via a loop in the expression.

## Proposed solution
Add a CommandLineBinding (https://www.commonwl.org/v1.1.0-dev1/CommandLineTool.html#CommandLineBinding) property `repeatPrefix`, which would only be valid if type array, just as itemSeparator.
Then the syntax
```
  input_array_strings:
    type:
      type: array
      items: string
      inputBinding:
        prefix: -B=
        separate: false
    inputBinding:
      position: 2
```
would be equivalent to
```
  input_array_strings:
    type: string[]
    inputBinding:
      position: 2
      prefix: -B=
      separate: false
      repeatPrefix: true
```
