### ISSUE TITLE
An input with two possible types: string and File with secondaryFiles

### ISSUE THREAD

**Issue by serge2016** [common-workflow-language/common-workflow-language#858]
Hello!
How should I specify the input that can be on of two types: `string` or `File`. When `File`, a `secondaryFiles` parameter is needed. More over, the same `inputBinding` section with `prefix: "-R"` and `position: 1` is needed.
I am trying this way:
```
cwlVersion: v1.0
class: Workflow
requirements:
    - class: SubworkflowFeatureRequirement
    - class: MultipleInputFeatureRequirement
    - class: StepInputExpressionRequirement
    - class: ScatterFeatureRequirement
inputs:
    reference1:
        type:
            - type: string
            - type: File
              secondaryFiles: [.fai, ^.dict]
    reference2:
        type:
            - type: string
              inputBinding:
                  prefix: "-R"
                  position: 1
            - type: File
              secondaryFiles: [.fai, ^.dict]
              inputBinding:
                  prefix: "-R"
                  position: 1
outputs: []
...
```
but it doesn't work... I didn't find any example or explanation.

When I remove `secondaryFiles` it seems to be ok:
```
inputs:
    reference3:
        type:
            - string
            - File
```

**Comment by serge2016** [comment]
It looks very strange, but:
```
inputs:
    reference:
        type:
            - string
            - File
        secondaryFiles: [.fai, ^.dict]
        inputBinding:
            prefix: "-R"
            position: 1
```
seems to work...
