### ISSUE TITLE
Infer inputs/outputs

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#86]
When writing a workflow with a step has many options that should be exposed as workflow inputs, it is currently necessary to copy all the parameters to the outer workflow.  This is verbose and creates a maintenance problem.  I propose a requirement type that instructs the implementation to lift unconnected input and output parameters to the parent workflow.

**Comment by ntijanic** [comment]
Perhaps this is better solved by additional tooling rather than the spec? Not sure.

If by spec, perhaps a step property like `exposeUnconnectedWithPrefix: tool_config_`. I don't like it since we'd be creating objects with identifiers implicitly, so it's no longer fully parsable with RDF without pre-processing.

**Comment by tetron** [comment]
Perhaps the solution is to support cross-referencing to other parameters?  In this example, the workflow input would take the type and default value from one of the 

```yaml
- class: CommandLineTool
  id: example-tool
  inputs:
    - id: count
      type: int
      default: 5
...

- class: Workflow
  id: example-wf
  inputs:
    - id: count
      type: "#example-tool/count"

  steps:
    - run: "#example-tool"
      inputs: [{id: count, source: "#example-wf/count"}]
...
```

**Comment by tetron** [comment]
This also relates to #124, permitting types to reference other type definitions references also allows for more flexible declaration than SchemaDefs.

**Comment by ntijanic** [comment]
Bump. Do we want this for draft4? Seems really useful. Perhaps something like this:

```yaml
class: Workflow
outputs:
  outfile: grep1.outfile
steps:
  grep1:
    run: grep.yaml
    inputs:
      infile: {expose: true}
      pattern: {expose: "first_pattern"}
```

This would make the workflow have two inputs: `grep1.infile` and `first_pattern` which sink into grep1 inputs. Also, the `grep1.outfile -> outfile` datalink would be implicitly created.
