### ISSUE TITLE
Modification of input files

### ISSUE THREAD

**Issue by padix-key** [common-workflow-language/common-workflow-language#875]
I am a Gromacs user who tries to integrate the software into CWL workflow. One of Gromacs' peculiarities is that it directly modifies the input structure topology (*.top file) from the previous step.
I tried to work with this behavior via `InitialWorkDirRequirement`. However, when following the symbolic link in the respective cache directory, the file is not modified. Here is the `CommandLineTool` definition:

```yaml
cwlVersion: v1.0

class: CommandLineTool

baseCommand: [gmx, solvate, -nobackup]

requirements:
  InitialWorkDirRequirement:
    listing:
      - $(inputs.in_topology)

inputs:
  in_structure:
    type: File
    format: [gromacs:pdb, gromacs:gro]
    inputBinding:
      prefix: -cp
  out_structure:
    type: string
    inputBinding:
      prefix: -o
    default: structure.gro
  in_topology:
    type: File
    format: gromacs:top
    inputBinding:
      prefix: -p
      valueFrom: $(self.basename)
  water_structure:
    type: File?
    format: [gromacs:pdb, gromacs:gro]
    inputBinding:
      prefix: -cs
  

outputs:
  out_structure:
    type: File
    format: gromacs:gro
    outputBinding:
      glob: $(inputs.out_structure)
  out_topology:
    type: File
    format: gromacs:top
    outputBinding:
      glob: $(inputs.in_topology.basename)

$namespaces:
  gromacs: http://manual.gromacs.org/documentation/2018/user-guide/file-formats.html
```

I am using cwl-runner 1.0.2.

Is `InitialWorkDirRequirement` the right way to go in this case? If not, is there a way to accomplish overwriting the input file?

**Comment by tetron** [comment]
You might need to ensure that the file is writable:

```
requirements:
  InitialWorkDirRequirement:
    listing:
      - entry: $(inputs.in_topology)
        writable: true
```
