### ISSUE TITLE
Multiple outputs overwrite each other

### ISSUE THREAD

**Issue by tammojan** [common-workflow-language/common-workflow-language#885]
The following workflow creates two outputs, however one file is silently overwritten by the other because they have the same name. Is this a bug or am I overlooking how CWL works?

```
class: Workflow
cwlVersion: v1.0
id: two_files
label: two_files

inputs:
  - id: message
    type: string
  - id: message_1
    type: string
outputs:
  - id: echo_out
    outputSource:
      - 1st_tool_1/echo_out
      - 1st_tool/echo_out
    type: 'File[]'
steps:
  - id: 1st_tool
    in:
      - id: message
        source: message
    out:
      - id: echo_out
    run: ./1st-tool.cwl
  - id: 1st_tool_1
    in:
      - id: message
        source: message_1
    out:
      - id: echo_out
    run: ./1st-tool.cwl
requirements:
  MultipleInputFeatureRequirement: {}
```

The 1st-tool.cwl is:
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs:
  message:
    type: string
    inputBinding:
      position: 1
outputs:
  - id: echo_out
    type: stdout
```
