### ISSUE TITLE
Clarify records with multiple inputBindings

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/common-workflow-language#890]
With CWL v1.1, for a simple record there can be three inputBindings, e.g.
```
inputs:
- inputBinding:
    position: 1
  id: input
  type:
    inputBinding:
      position: 3
      valueFrom: c
    type: record
    fields:
    - name: input_field
      type: string?
      inputBinding:
        position: 2
        valueFrom: b
    name: input
```
where the part
```
    inputBinding:
      position: 3
      valueFrom: c
```
is made available since CWL v1.1. I think the specification and the conformance tests can both be improved to better explain different configurations of inputBindings.

**Comment by mr-c** [comment]
This could be clarified in CWL v1.2.1, thanks!

**Comment by tom-tan** [comment]
Related: #783 that will be clarified how to behave the nested inputBindings.

cwltool 3.1.20230601100705 generates the different result.
IMO we have to wait for #783 to be closed.

```cwl
cwlVersion: v1.1
class: CommandLineTool
baseCommand: touch
inputs:
  touchfiles:
    type:
      type: array
      items: string
      inputBinding:
        position: 2
  input:
    inputBinding:
      position: 1
    type:
      inputBinding:
        position: 3
        valueFrom: c
      type: record
      fields:
      - name: input_field
        type: string?
        inputBinding:
          position: 2
          valueFrom: b
outputs: []
```

```yaml
touchfiles: [foo.txt, bar.dat, baz.txt]
input:
  input_field: "foobar"
```

```console
$ cwltool array-outputs.cwl array-outputs-job.yaml 
INFO /usr/local/bin/cwltool 3.1.20230601100705
INFO Resolved 'array-outputs.cwl' to 'file:///workspaces/cwl-v1.2/array-outputs.cwl'
INFO [job array-outputs.cwl] /tmp/t37hg1jp$ touch \
    foo.txt \
    bar.dat \
    c \
    b \
    baz.txt
INFO [job array-outputs.cwl] completed success
{}INFO Final process status is success
```
