### ISSUE TITLE
Directory loadListing behavior in v1.1 is not backwards compatible

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/common-workflow-language#893]
Example:
Run this tool (provide any directory as the `aa` input) 
```
class: CommandLineTool
cwlVersion: v1.0
baseCommand: ["echo"]
inputs:
- type: Directory
  id: aa
  inputBinding:
    valueFrom: "$(self.listing.length)"
outputs:
  o1:
    type: Directory
    outputBinding:
      glob: $(inputs.aa.basename)
requirements:
- class: InlineJavascriptRequirement
- class: InitialWorkDirRequirement
  listing: 
  - $(inputs.aa)
```
it completes fine. Now switch the cwlVersion to v1.1 and run again. It fails with message
> Cannot read property 'length' of undefined

This is because loadListing is added to v1.1 and the value is set to be `no_listing` by default.

It would make sense for v1.1 behavior to have `deep_listing` as the default value.
