### ISSUE TITLE
Conformance tests for renaming output files with basename

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/common-workflow-language#900]
The [CWL user guide ](https://www.commonwl.org/user_guide/misc/) suggests a feature of renaming output files by changing the basename property in outputEval:
```
outputs:
 otu_table:
    type: File
    outputBinding:
      glob: otu_table.txt
      outputEval: ${self[0].basename=inputs.otu_table_name; return self;}
```
However this kind of behavior is not covered by conformance tests, there should be at least one test for this basic use case
