### ISSUE TITLE
How to specify lower and upper bound for type `array` in WorkflowInputParameter

### ISSUE THREAD

**Issue by emmanuelmathot** [common-workflow-language/common-workflow-language#907]
We would like to know if it is possible to specify a lower and upper boundary in the number of items in array of an input parameter. That specification would of course imply a validation of the number of input parameter.

So the input definition in CWL would be similar to :

```
cwlVersion: v1.0
class: CommandLineTool
inputs:
  main_input:
    type: string
    label: Main input

  correlated_input:
    type:
      type: array
      items: string
      min_items: 2
      max_items: 10
    label: 2 to 10 correlated inputs

baseCommand: echo
outputs: []
```
Thank you for your help.
