### ISSUE TITLE
More custom data types

### ISSUE THREAD

**Issue by stevekm** [common-workflow-language/common-workflow-language#938]
As described here; 

https://www.commonwl.org/v1.0/CommandLineTool.html#SchemaDefRequirement

https://www.commonwl.org/user_guide/19-custom-types/index.html

Right now only `record` and `enum` classes are able to be used as custom data types. 

Would be great if this could be expanded to other types. For example, a `File` type such as this schema we frequently use for a reference genome fasta file

```
- name: RefFasta
  doc: reference genome .fasta file
  type: File
  secondaryFiles:
    - .amb
    - .ann
    - .bwt
    - .pac
    - .sa
    - .fai
    - ^.dict
```

-----
- initial discussion here; https://cwl.discourse.group/t/unable-to-create-a-custom-file-type/569
